import json

with open('data/theme-5.json', 'r') as f:
    data = json.load(f)

new_mock = [
    {
        "id": "t5-m421", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes 'bridging anticoagulation' and when it is NO LONGER routinely recommended?",
        "options": ["A. Bridging with LMWH is recommended for all patients on warfarin undergoing any surgical procedure", "B. Bridging anticoagulation (substituting LMWH during the period warfarin is stopped peri-operatively) is NO LONGER routinely recommended for patients with AF — BRIDGE trial showed bridging increased bleeding without reducing thromboembolism; it remains appropriate for mechanical heart valves and very high-risk patients", "C. Bridging is still recommended for all AF patients with CHA2DS2-VASc ≥2 undergoing any surgery", "D. Bridging is only required for laparoscopic surgery — open procedures do not require bridging", "E. Bridging anticoagulation always requires hospitalisation for IV UFH administration"],
        "correctAnswer": "B",
        "explanation": "BRIDGE trial (2015): landmark RCT of warfarin patients with AF undergoing elective procedures. Bridging with LMWH vs no bridging: NO reduction in arterial thromboembolism; SIGNIFICANTLY MORE major bleeding complications with bridging (3.2% vs 1.3%). Conclusions: bridging is harmful for most AF patients. Current guidance: AF patients on warfarin — STOP warfarin 5 days before; DO NOT bridge (unless very high-risk: mechanical heart valve, recent stroke/TIA within 3 months, or certain high-thrombosis-risk indications). Restart warfarin 12–24 hours post-procedure when haemostasis secured. Mechanical heart valves: bridging IS still recommended (especially mitral position) due to much higher thromboembolism risk without anticoagulation. Bioprosthetic valves: treat as per AF guidance (no routine bridging after 3 months post-implant). Always involve anticoagulation clinic for complex cases."
    },
    {
        "id": "t5-m422", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 20-year-old woman presents with recurrent episodes of rapid regular palpitations that start and stop suddenly, lasting 10–30 minutes. Her ECG during sinus rhythm shows a short PR interval and a delta wave. Which ONE of the following is the MOST appropriate definitive treatment?",
        "options": ["A. Lifelong beta-blocker therapy to prevent episodes of SVT", "B. Catheter ablation of the accessory pathway (Bundle of Kent) — curative treatment for symptomatic WPW syndrome with >95% success rate and low complication rate", "C. Implantable cardioverter defibrillator (ICD) — all WPW patients require an ICD to prevent sudden cardiac death", "D. Digoxin 125 micrograms daily — the first-line pharmacological treatment for WPW-related tachyarrhythmias", "E. Adenosine infusion long-term — daily adenosine prevents accessory pathway conduction"],
        "correctAnswer": "B",
        "explanation": "Wolff-Parkinson-White (WPW) syndrome: congenital accessory pathway (Bundle of Kent) connecting atria and ventricles outside the AV node. ECG: short PR (<120ms — pre-excitation bypasses AV nodal delay), delta wave (slurred QRS upstroke from slow pathway conduction), wide QRS. Tachycardias: AVRT (most common — orthodromic: antegrade AV node, retrograde accessory pathway = narrow QRS tachycardia; or antidromic = wide QRS). Also risk of pre-excited AF (extremely rapid ventricular rate → VF). Definitive treatment: radiofrequency catheter ablation of the accessory pathway — curative in >95% with very low complication rates (<1% serious). Risk stratification: electrophysiology study to assess accessory pathway refractory period — short ERP = high VF risk. Digoxin and verapamil are CONTRAINDICATED in WPW (may accelerate conduction through accessory pathway)."
    },
    {
        "id": "t5-m423", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "Which ONE of the following correctly describes the MOST common cause of intracerebral haemorrhage (ICH) in a 70-year-old patient?",
        "options": ["A. Ruptured berry aneurysm — the most common cause of ICH in all age groups", "B. Hypertensive small vessel disease — chronic hypertension causes lipohyalinosis of small penetrating arteries (lenticulostriate, thalamoperforating) which rupture causing deep haematomas in the basal ganglia, thalamus, pons, and cerebellum", "C. Arteriovenous malformation (AVM) — the most common cause of ICH in the elderly", "D. Anticoagulant-related haemorrhage — warfarin is the most common cause of ICH at all ages", "E. Tumour haemorrhage — all spontaneous ICH in elderly patients is caused by bleeding into a primary brain tumour"],
        "correctAnswer": "B",
        "explanation": "Intracerebral haemorrhage (ICH) causes by age: Young adults (AVM, recreational drugs — cocaine, amphetamines). Middle-aged: hypertension, AVM. Elderly (most common): (1) Hypertensive ICH — most common overall: basal ganglia (putamen most common), thalamus, pons, cerebellum — all in territories of small perforating arteries affected by lipohyalinosis from chronic hypertension; (2) Cerebral amyloid angiopathy (CAA) — increasingly common in elderly; lobar haematomas in cortical/subcortical regions; associated with Alzheimer's pathology; (3) Anticoagulant-related (warfarin, DOACs); (4) Tumour bleeding (less common). Berry aneurysm rupture causes SUBARACHNOID haemorrhage (blood in subarachnoid space) — NOT intracerebral haemorrhage (blood in brain parenchyma). The distinction is clinically and radiologically important. Management of ICH: BP reduction (target <140 mmHg systolic), reverse coagulopathy if present, surgical evacuation for selected cases."
    },
    {
        "id": "t5-m424", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "A patient with known mitral valve prolapse (MVP) is attending for dental extractions. Her cardiologist's letter states 'MVP with trivial MR — no prophylaxis recommended.' Which ONE of the following is the MOST appropriate interpretation?",
        "options": ["A. The letter is incorrect — all patients with MVP require antibiotic prophylaxis before dental extractions", "B. NICE 2016 guidance does not recommend antibiotic prophylaxis for IE for ANY patients undergoing dental procedures, including those with MVP — the letter is consistent with current guidelines; proceed without prophylaxis", "C. MVP with trivial MR still requires amoxicillin 3g prophylaxis before all extractions as it is a valvular abnormality", "D. Proceed without prophylaxis but prescribe a 5-day course of amoxicillin post-operatively as an alternative strategy", "E. Refer back to the cardiologist — the dental team cannot act without specific written prophylaxis instructions"],
        "correctAnswer": "B",
        "explanation": "NICE guideline CG64 (2008, updated 2016): antibiotic prophylaxis against infective endocarditis is NOT recommended for any dental procedure in the UK. This applies to ALL patients including those with high-risk cardiac conditions (prosthetic valves, previous IE, congenital heart disease) and all 'moderate-risk' conditions including MVP. Rationale: (1) Limited evidence that prophylaxis is effective; (2) Risk of antibiotic-related anaphylaxis may exceed the risk of IE from dental procedures; (3) Cumulative bacteraemia from oral hygiene activities exceeds that from dental procedures; (4) Optimal oral hygiene is the most effective IE prevention. MVP with trivial MR: very low IE risk — antibiotic prophylaxis is even less justified. The cardiologist's letter is entirely consistent with NICE. Importantly: ensure the patient has good oral hygiene (the real protective strategy) and is aware of IE symptoms (to present early if symptoms develop)."
    },
    {
        "id": "t5-m425", "theme": 5, "topicTag": "atherosclerosis",
        "question": "Which ONE of the following correctly identifies the MOST important modifiable risk factor for reducing cardiovascular mortality according to the Framingham Heart Study and subsequent meta-analyses?",
        "options": ["A. Reducing LDL cholesterol — statin therapy alone is responsible for most cardiovascular risk reduction in primary prevention", "B. Smoking cessation — smokers have 2–4× the CVD risk of non-smokers; cessation reduces CVD risk to near-normal levels within 2–5 years; at a population level, smoking cessation has the greatest single impact on CVD mortality", "C. Achieving normal BMI — obesity reduction is more important than smoking cessation and BP control combined", "D. Optimal blood glucose control in type 2 diabetes — glycaemia is the primary driver of CVD events in all patients", "E. Stress reduction — psychological interventions have the same magnitude of CVD benefit as all pharmacological treatments combined"],
        "correctAnswer": "B",
        "explanation": "Smoking is one of the most powerful modifiable CVD risk factors: (1) Promotes endothelial dysfunction (acrolein, reactive oxygen species); (2) Increases LDL oxidation; (3) Promotes platelet aggregation; (4) Increases fibrinogen; (5) Causes coronary vasospasm; (6) Increases heart rate and BP. Relative risk of CVD in smokers: 2–4× non-smokers; risk scales with number of cigarettes and duration. Cessation benefit: within 24 hours — CO levels normalise; 1 year — CHD risk halved; 5–15 years — CVD risk approaches that of never-smokers. At population level: smoking cessation campaigns have reduced CVD mortality more than any other single intervention. In individual patients: all risk factors are synergistic — combined management (smoking + BP + cholesterol + glucose) is most effective. But smoking cessation is uniquely powerful because it reverses multiple pathogenic mechanisms simultaneously."
    },
    {
        "id": "t5-m426", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 62-year-old man with HFrEF (EF 25%) on carvedilol, enalapril, and eplerenone requires a dental extraction. He reports no breathlessness at rest but develops breathlessness walking upstairs (NYHA class II). His BP is 105/65 mmHg and SpO2 is 96%. Which ONE of the following is the MOST appropriate approach to his dental care?",
        "options": ["A. Refer to hospital for all dental care — all NYHA class II patients must be treated in hospital", "B. Defer treatment indefinitely until EF improves above 35%", "C. Treat in primary care in a semi-reclined position; minimise adrenaline (maximum 2 cartridges 1:100,000); use paracetamol/codeine for analgesia (avoid NSAIDs); manage anxiety (short appointments, consider oral anxiolytic); confirm current medications and haemoglobin before treatment", "D. Use nitrous oxide sedation as first-line — it is the safest sedation method in all heart failure patients", "E. Full dental clearance under GA is required as NYHA II patients cannot tolerate multiple appointments"],
        "correctAnswer": "C",
        "explanation": "NYHA class II HFrEF with stable BP 105/65 and SpO2 96%: can be treated in primary care with appropriate precautions. Key considerations: (1) Position: semi-reclined (30–45° — avoids supine venous pooling causing orthopnoea); (2) Adrenaline: limit to 2 × 1:100,000 cartridges (72 micrograms) — excessive adrenaline causes tachycardia (worsens HF) and hypertension then reflex hypotension; (3) Analgesics: NSAIDs contraindicated (worsen renal function, cause Na/water retention, worsen HF); use paracetamol ± weak opioid; (4) Anxiety management: stress → catecholamine surge → tachycardia/hypertension → acute HF decompensation; consider oral temazepam or midazolam; (5) Check medications: avoid additional drugs that interact with heart failure medications; (6) Haemoglobin: anaemia worsens HF symptoms and is common. Nitrous oxide sedation is acceptable but not specifically preferred over alternatives in HF."
    },
    {
        "id": "t5-m427", "theme": 5, "topicTag": "cvd-overview",
        "question": "A 55-year-old woman presents with acute severe chest pain radiating to her back described as 'tearing.' Her BP is 185/105 mmHg in the right arm but 155/85 mmHg in the left arm. The chest X-ray shows mediastinal widening. Which ONE of the following is the MOST likely diagnosis?",
        "options": ["A. Acute STEMI — chest pain radiating to the back with hypertension suggests inferior MI", "B. Acute aortic dissection — tearing/ripping chest/back pain, BP discrepancy between arms >20 mmHg, and mediastinal widening on CXR are classic features", "C. Pulmonary embolism — pleuritic chest pain with mediastinal widening from right heart strain", "D. Tension pneumothorax — absent breath sounds on one side with mediastinal shift on CXR", "E. Acute pericarditis — tearing pain with mediastinal widening from a large pericardial effusion"],
        "correctAnswer": "B",
        "explanation": "Acute aortic dissection: tear in the aortic intima → blood dissects into the media creating a false lumen. Classical presentation: sudden-onset severe tearing/ripping chest pain radiating to the back or interscapular region; maximum pain from the start (unlike MI where pain builds). Signs: (1) BP discrepancy between arms >20 mmHg (if dissection involves the origin of the subclavian artery); (2) Mediastinal widening on CXR (from expanding haematoma); (3) Aortic regurgitation murmur if the dissection involves the aortic root; (4) Neurological deficits (if carotid arteries involved); (5) Acute MI (if coronary ostia involved — often the RCA → inferior STEMI). Type A (ascending aorta involved): surgical emergency. Type B (descending aorta only): medical management (BP control with IV labetalol or esmolol — target SBP 100–120 mmHg) unless complicated. CT angiography is the diagnostic investigation of choice. CRITICAL: do NOT give thrombolysis if dissection is suspected mimicking STEMI."
    },
    {
        "id": "t5-m428", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes the mechanism by which erythromycin raises the INR in patients on warfarin?",
        "options": ["A. Erythromycin directly inhibits vitamin K production in the gut, reducing synthesis of clotting factors", "B. Erythromycin inhibits CYP3A4 and CYP2C9, reducing warfarin (particularly S-warfarin) metabolism → elevated plasma warfarin levels → higher INR; it also kills gut bacteria that produce vitamin K", "C. Erythromycin displaces warfarin from plasma protein binding sites, increasing free warfarin concentration", "D. Erythromycin activates the warfarin receptor, increasing its anticoagulant potency without affecting plasma levels", "E. Erythromycin has no interaction with warfarin — macrolides are safe to prescribe without INR monitoring"],
        "correctAnswer": "B",
        "explanation": "Erythromycin-warfarin interaction: dual mechanism. (1) CYP inhibition: erythromycin inhibits CYP3A4 (primarily) and, to some extent, CYP2C9 → reduces warfarin metabolism (particularly S-warfarin — the more potent enantiomer, metabolised by CYP2C9) → elevated warfarin plasma levels → raised INR; (2) Gut flora disruption: broad-spectrum antibiotic effect reduces gut bacteria (Bacteroides, Lactobacillus) that produce vitamin K → less intestinal vitamin K → reduced factor synthesis → higher INR. Effect magnitude: INR can rise significantly (potential bleeding risk). Clinical management: if erythromycin is prescribed to a warfarin patient, check INR within 3–5 days; consider dose reduction; advise patient to watch for bleeding signs. Clarithromycin: stronger CYP3A4/2C9 inhibitor than erythromycin — greater INR elevation. Azithromycin: minimal CYP inhibition — much lower risk. Amoxicillin: lower interaction risk (primarily gut flora effect — minimal CYP interaction)."
    },
    {
        "id": "t5-m429", "theme": 5, "topicTag": "heart-failure",
        "question": "A patient with advanced HFrEF (EF 15%, NYHA class IV) has been refractory to optimal medical therapy including sacubitril/valsartan, carvedilol, spironolactone, and SGLT2 inhibitor. He is 48 years old with no other comorbidities. Which ONE of the following should be considered?",
        "options": ["A. Increase loop diuretic dose indefinitely — this is the only remaining management option", "B. Cardiac transplantation assessment — indicated in patients with refractory HFrEF, NYHA III–IV symptoms despite optimal therapy, who have no contraindications; 1-year survival >90%, 5-year >75%, 10-year >50%", "C. Implantable cardioverter defibrillator (ICD) as the only device therapy option remaining", "D. Continuous IV dobutamine infusion at home — the definitive therapy for NYHA class IV refractory HF", "E. Palliative care referral only — no further therapeutic options exist for refractory NYHA class IV HF in patients under 50"],
        "correctAnswer": "B",
        "explanation": "Cardiac transplantation: the definitive treatment for refractory end-stage HF. Indications: refractory NYHA III–IV HF despite maximum tolerated medical therapy (including neurohormonal blockade, SGLT2 inhibitor, CRT if applicable); peak VO2 <14 mL/kg/min on cardiopulmonary exercise testing; predicted 1-year mortality >50% without transplant. Contraindications: age >65–70 (relative), fixed pulmonary hypertension (PVR >5 Wood units — donor RV cannot function against it), active malignancy, severe renal/hepatic disease, active infection, non-compliance. Outcomes: 1-year survival ~90%, median survival 12 years (modern era). For patients awaiting transplantation: left ventricular assist device (LVAD — Heartmate 3) as bridge-to-transplant or destination therapy if transplant ineligible. LVAD: improves survival, NYHA class, and quality of life in advanced HF — approved for NYHA class IV refractory to medical therapy."
    },
    {
        "id": "t5-m430", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly describes the mechanism of 'torsade de pointes' (TdP) and the MOST appropriate immediate management?",
        "options": ["A. TdP is caused by excessive QT shortening from hyperkalaemia; treated with IV potassium", "B. TdP (twisting of points): polymorphic VT associated with prolonged QT interval — during the prolonged repolarisation phase, early afterdepolarisations (EADs) trigger abnormal beats that initiate TdP; management: IV magnesium sulphate 2g over 5–10 minutes (first-line), correct underlying cause (hypokalaemia, drugs), consider overdrive pacing", "C. TdP is identical to monomorphic VT — treatment is the same (amiodarone infusion)", "D. TdP is caused by Brugada syndrome and treated with quinidine", "E. TdP is only seen in congenital long QT syndrome and never occurs with drug-induced QT prolongation"],
        "correctAnswer": "B",
        "explanation": "Torsade de pointes (TdP): polymorphic VT with characteristic 'twisting' of the QRS complex around the isoelectric line. Associated with prolonged QT interval (>500ms high risk). Mechanism: prolonged repolarisation → early afterdepolarisations (EADs) from incomplete repolarisation reaching threshold → triggered activity initiates TdP. Causes: (1) Electrolyte abnormalities — hypokalaemia, hypomagnesaemia, hypocalcaemia (all prolong QT); (2) Drugs — antiarrhythmics (quinidine, sotalol — class IA and III), antibiotics (erythromycin, clarithromycin, azithromycin), antipsychotics (haloperidol, droperidol), antiemetics (domperidone, metoclopramide), antifungals (fluconazole); (3) Congenital LQTS; (4) Bradycardia. Management: IV magnesium 2g IV over 5 minutes (stabilises cardiac membranes, suppresses EADs — even if Mg2+ is normal); correct K+ (target >4.0 mmol/L); stop offending drugs; DC cardioversion if haemodynamically compromised; overdrive pacing or isoproterenol to increase HR (reduces QTc — inverse square relationship with HR). Do NOT give amiodarone (prolongs QT further)."
    },
    {
        "id": "t5-m431", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 70-year-old man is admitted with a large anterior STEMI. Primary PCI is performed successfully. Four days later, he develops sudden-onset hypotension, a new harsh pansystolic murmur at the left sternal edge, and biventricular failure. Which ONE of the following is the MOST likely complication?",
        "options": ["A. Stent thrombosis — re-occlusion of the LAD causing a second MI with a new murmur from papillary muscle ischaemia", "B. Ventricular septal defect (VSD) — mechanical complication of MI from ischaemic necrosis and rupture of the interventricular septum; occurs 3–5 days post-MI; harsh pansystolic murmur at left sternal edge with right-to-left shunt and biventricular failure", "C. Acute mitral regurgitation from papillary muscle rupture — causes a pansystolic murmur identical in location to VSD", "D. Free wall rupture with cardiac tamponade — causes pulsus paradoxus and Beck's triad, not a new murmur", "E. Dressler's syndrome — pericarditis 2–4 weeks post-MI causing a friction rub and pericardial effusion"],
        "correctAnswer": "B",
        "explanation": "Post-MI mechanical complications (3–7 days post-MI — tissue necrosis and softening): (1) Ventricular septal defect (VSD): necrosis of the interventricular septum → rupture → left-to-right shunt; harsh pansystolic murmur at the left sternal edge (different from MR murmur which radiates to the axilla); step-up in O2 saturation from RA to PA confirms L→R shunt; rapidly causes biventricular failure. (2) Acute mitral regurgitation: papillary muscle rupture (posteromedial papillary muscle — single blood supply from PDA → inferior MI); soft pansystolic murmur at apex radiating to axilla; acute pulmonary oedema predominates. (3) Free wall rupture: cardiac tamponade → sudden haemodynamic collapse without a murmur; often rapidly fatal. Acute post-MI VSD: urgent cardiac surgery (or percutaneous device closure) — medical management alone has >90% mortality. Temporary stabilisation with intra-aortic balloon pump and vasodilators."
    },
    {
        "id": "t5-m432", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly identifies the dental significance of 'gingival hyperplasia' as a side effect and the cardiovascular drug most commonly responsible?",
        "options": ["A. Warfarin causes gingival hyperplasia by increasing gingival fibroblast proliferation from vitamin K pathway inhibition", "B. Amlodipine (and other dihydropyridine calcium channel blockers such as nifedipine) causes gingival overgrowth (gingival hyperplasia/enlargement) — particularly in plaque-present areas; mechanism involves altered fibroblast collagen metabolism; management includes improving oral hygiene and considering drug substitution", "C. Bisoprolol causes gingival hyperplasia by blocking beta-receptors in gingival fibroblasts", "D. Ramipril causes gingival hyperplasia as an extension of its bradykinin-mediated side effects", "E. Spironolactone causes gingival hyperplasia through its anti-androgenic effects on gingival connective tissue"],
        "correctAnswer": "B",
        "explanation": "Drug-induced gingival overgrowth (DIGO): three main drug classes: (1) Calcium channel blockers (nifedipine — highest incidence ~50%; amlodipine — lower incidence ~3–15%; other dihydropyridines); (2) Phenytoin (anticonvulsant); (3) Ciclosporin (immunosuppressant). Mechanism of CCB-induced DIGO: dihydropyridines inhibit Ca2+ entry into gingival fibroblasts → reduced collagen phagocytosis → collagen accumulates in the gingival connective tissue. Plaque-dependent — exacerbated by poor oral hygiene (bacterial plaque cytokines further stimulate fibroblast proliferation). Distribution: initially in the interdental papillae of the anterior teeth. Management: (1) Improve oral hygiene (can partially reverse early DIGO); (2) Substitute amlodipine with a rate-limiting CCB (diltiazem, verapamil) or alternative antihypertensive; (3) Surgical gingivectomy if hyperplasia is severe and non-responsive. Dental teams should monitor gingival health in all CCB patients."
    },
    {
        "id": "t5-m433", "theme": 5, "topicTag": "hypertension",
        "question": "A 45-year-old man is started on indapamide (a thiazide-like diuretic) for hypertension. Which ONE of the following metabolic side effect requires monitoring after initiation?",
        "options": ["A. Hyperkalaemia — indapamide retains potassium in the collecting duct", "B. Hypokalaemia — thiazide diuretics promote potassium excretion in the distal convoluted tubule; hypokalaemia increases the risk of arrhythmias, particularly in patients on digoxin or at risk for long QT", "C. Hypoglycaemia — thiazide diuretics cause dangerously low blood glucose by stimulating insulin secretion", "D. Hypocalcaemia — thiazides promote urinary calcium excretion causing calcium deficiency", "E. No metabolic monitoring is required for indapamide — it is metabolically neutral"],
        "correctAnswer": "B",
        "explanation": "Thiazide diuretic metabolic effects: (1) Hypokalaemia: thiazides inhibit the Na-Cl co-transporter in the DCT → increased Na+ delivery to the collecting duct → Na+ reabsorbed in exchange for K+ (aldosterone-mediated) and H+ → K+ loss; hypokalaemia worsens with co-prescription of loop diuretics, high salt intake, or hyperaldosteronism; monitor K+ at 2–4 weeks and after dose changes. (2) Hyponatraemia: particularly in elderly (SIADH-like effect + dilutional). (3) Hyperuricaemia: reduces renal uric acid excretion → gout. (4) Hyperglycaemia/new-onset T2DM: reduce insulin sensitivity. (5) Dyslipidaemia: mild increase in LDL/triglycerides (less so with modern thiazide-like agents indapamide, chlorthalidone vs bendroflumethiazide). (6) Hypercalcaemia (NOT hypocalcaemia): thiazides reduce urinary calcium excretion — used therapeutically for calcium stone disease. Indapamide has a better metabolic profile than older thiazides."
    },
    {
        "id": "t5-m434", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "A 65-year-old woman with a 40-pack-year smoking history is found to have a 4.8cm abdominal aortic aneurysm (AAA) on abdominal ultrasound during NHS AAA screening. She is asymptomatic. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Emergency surgical repair — all AAAs found on screening require immediate surgery regardless of size", "B. 3-monthly ultrasound surveillance and optimise cardiovascular risk factors (smoking cessation, statin, antiplatelet, BP control); refer for elective repair when aneurysm reaches 5.5cm or growth >1cm/year", "C. Endovascular repair (EVAR) immediately as this is the screening-detected size threshold for intervention", "D. Discharge — AAAs under 6cm never rupture and require no follow-up", "E. CT angiogram immediately and plan surgical repair before the aneurysm can grow any further"],
        "correctAnswer": "B",
        "explanation": "NHS AAA Screening Programme (NAASP) management thresholds: Small AAA 3.0–4.4cm: annual ultrasound surveillance. Medium AAA 4.5–5.4cm: 3-monthly surveillance and aggressive cardiovascular risk factor modification (smoking cessation — single most important intervention slowing aneurysm growth; statin; antiplatelet; BP control aiming for SBP <140). Large AAA ≥5.5cm or growth >1cm/year OR symptomatic: refer vascular surgery for elective repair — EVAR (endovascular) or open surgery. Rationale: operative mortality of elective repair (~1–2% for EVAR, ~5% for open) must be weighed against annual rupture risk (<1% for 4cm, ~5% for 5cm, ~10–15% for 6cm, >50% for 7cm+). At 4.8cm, the rupture risk does not yet exceed the operative mortality → surveillance is the correct management. Women have higher rupture risk at smaller sizes — some guidelines consider 5.0cm threshold for women."
    },
    {
        "id": "t5-m435", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on apixaban 5mg twice daily for AF is prescribed fluconazole 150mg for oral candidiasis. Which ONE of the following interaction is MOST clinically significant?",
        "options": ["A. Fluconazole has no interaction with apixaban — azole antifungals only interact with warfarin", "B. Fluconazole is a potent CYP3A4 and P-glycoprotein inhibitor — it significantly increases apixaban plasma levels, raising the risk of bleeding; consider dose reduction of apixaban or switch to nystatin for the oral candidiasis to avoid the interaction", "C. Fluconazole reduces apixaban efficacy by inducing CYP3A4, increasing apixaban metabolism", "D. Fluconazole directly antagonises apixaban's anti-Xa activity at the receptor level", "E. Fluconazole and apixaban should always be prescribed together — azoles enhance DOAC efficacy"],
        "correctAnswer": "B",
        "explanation": "Apixaban pharmacokinetics: metabolised by CYP3A4 and P-glycoprotein (P-gp). Fluconazole: potent inhibitor of CYP3A4 and moderate P-gp inhibitor → significantly reduces apixaban clearance → increased plasma apixaban levels → enhanced anticoagulant effect → bleeding risk. SmPC for apixaban: avoid combined use with strong dual inhibitors of CYP3A4 and P-gp (including fluconazole, ketoconazole, itraconazole, ritonavir). Clinical alternatives: (1) Use nystatin for oral/oropharyngeal candidiasis — absorbed minimally, no CYP interaction — SAFE with apixaban; (2) If systemic azole is essential (e.g. oesophageal candidiasis): reduce apixaban dose and monitor closely; (3) Consider switching to warfarin temporarily (INR-monitored) if prolonged azole use required. This interaction mirrors the miconazole gel-warfarin interaction — azole antifungals interact with multiple anticoagulants."
    },
    {
        "id": "t5-m436", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "Which ONE of the following correctly distinguishes the coronary angiographic findings that guide the choice between percutaneous coronary intervention (PCI) and coronary artery bypass graft surgery (CABG) in stable multivessel coronary artery disease?",
        "options": ["A. PCI is always preferred over CABG for all multivessel coronary disease regardless of anatomy", "B. SYNTAX score: low SYNTAX score (≤22) — PCI and CABG have equivalent outcomes; intermediate/high SYNTAX score (>22, especially >33) — CABG is superior, with lower rates of MACE and repeat revascularisation; left main coronary artery disease — CABG preferred for complex anatomy, PCI acceptable for lower SYNTAX score", "C. CABG is always preferred over PCI for all multivessel disease as survival is always better with bypass", "D. SYNTAX score is used only to predict operative mortality from CABG, not to guide choice between PCI and CABG", "E. PCI is preferred for all three-vessel disease; CABG is only for left main stem disease"],
        "correctAnswer": "B",
        "explanation": "SYNTAX score: angiographic scoring system assessing coronary lesion complexity (number, location, type, calcification, bifurcation involvement, total occlusion). SYNTAX trial (three-vessel or LM disease): at 5 years: Low SYNTAX ≤22: PCI and CABG similar outcomes → either acceptable. Intermediate SYNTAX 23–32: CABG advantage emerging. High SYNTAX ≥33: CABG significantly superior (lower MACE, lower repeat revascularisation, lower mortality in DM). Left main coronary artery disease: EXCEL and NOBLE trials — CABG preferred for complex LM disease (SYNTAX >32, distal bifurcation involvement); PCI acceptable for ostial/mid-shaft LM with low-intermediate SYNTAX. Multi-disciplinary heart team (MDT — cardiologist + cardiac surgeon + anaesthetist + patient) makes individualized decision. Additional factors: diabetes mellitus (CABG preferred), EF, age/comorbidities, completeness of revascularisation."
    },
    {
        "id": "t5-m437", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "A 68-year-old man had an ischaemic stroke 3 weeks ago. His BP is now 155/92 mmHg (having been 145/88 mmHg pre-stroke). He was on no antihypertensives before. Which ONE of the following is the MOST appropriate management of his blood pressure?",
        "options": ["A. Continue to avoid antihypertensives for 6 months post-stroke — BP must remain elevated for adequate cerebral perfusion", "B. Start antihypertensive therapy (ACE inhibitor or ARB ± thiazide-like diuretic) — secondary prevention of recurrent stroke requires BP reduction; recommended at 2 weeks post-stroke when the patient is neurologically stable", "C. Start antihypertensives immediately on the day of admission for a stroke — immediate BP lowering reduces stroke extension", "D. Antihypertensives are contraindicated in stroke patients — BP must be managed with dietary sodium restriction alone", "E. Refer to neurology before starting any antihypertensive — only neurologists can prescribe BP medication after stroke"],
        "correctAnswer": "B",
        "explanation": "Post-ischaemic stroke secondary prevention — BP management: Acute phase (first 24–72h): avoid routine BP lowering (see earlier question — risks worsening penumbra). After stabilisation (typically 2 weeks post-stroke when neurologically stable): START antihypertensive therapy for long-term secondary prevention. Target: SBP <130 mmHg (PROGRESS trial showed greater benefit with lower targets in secondary stroke prevention compared to primary). Drug choice: ACE inhibitor + thiazide-like diuretic combination (PROGRESS trial — perindopril + indapamide: 43% reduction in recurrent stroke vs placebo). If ACE inhibitor not tolerated (cough): ARB. In patients with AF: anticoagulation is paramount (dominant mechanism was cardioembolic) — start 1–2 weeks post-stroke if small-moderate infarct (TOE to check for LA thrombus if AF was newly detected). Carotid stenosis >50% → carotid endarterectomy within 2 weeks."
    },
    {
        "id": "t5-m438", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "A patient with severe aortic stenosis (mean gradient 55 mmHg, AVA 0.7 cm²) reports exertional chest pain, dyspnoea on climbing one flight of stairs, and an episode of pre-syncope last week. Which ONE of the following is the MOST appropriate next management step?",
        "options": ["A. Start ACE inhibitor — reduces afterload and improves symptoms while awaiting further investigation", "B. Refer for urgent valve replacement (TAVI or SAVR) — symptomatic severe AS has a median survival of only 2–3 years without valve replacement; the presence of the classic triad (angina, dyspnoea, syncope) is a class I indication for urgent intervention", "C. Start digoxin for rate control — AS causes AF which is responsible for the symptoms", "D. Perform exercise stress testing to confirm the haemodynamic significance of the stenosis before considering referral", "E. Refer for annual echocardiographic surveillance — symptoms in AS are non-specific and do not change management"],
        "correctAnswer": "B",
        "explanation": "Symptomatic severe aortic stenosis: the development of symptoms is the critical turning point in AS management. Natural history of symptomatic severe AS: Angina → median survival 5 years; Heart failure → median survival 1–2 years; Syncope → median survival 3 years. This patient has the classic AS triad (angina, dyspnoea, and pre-syncope) — all three symptoms have developed, indicating severely compromised haemodynamics. ESC/ACC/AHA guidelines: class I indication for aortic valve replacement in symptomatic severe AS (mean gradient ≥40 mmHg OR AVA ≤1.0 cm²). Urgency: refer urgently for TAVI or SAVR — every week of delay risks sudden cardiac death (annual rate ~1% in severe AS, higher when symptomatic). Exercise testing is CONTRAINDICATED in symptomatic severe AS (risk of haemodynamic collapse). ACE inhibitors are RELATIVELY contraindicated in severe AS (reduce afterload but cause reflex tachycardia worsening obstruction)."
    },
    {
        "id": "t5-m439", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient taking bisoprolol for heart failure undergoes a routine lower molar extraction under inferior alveolar nerve block. Immediately after the injection, the patient's heart rate drops to 38 bpm and she feels dizzy and diaphoretic. Which ONE of the following is the MOST appropriate immediate management?",
        "options": ["A. Administer atropine 600 micrograms IV immediately — this is an anaphylactic reaction", "B. This is a vasovagal episode — lay the patient flat with legs elevated; this typically resolves spontaneously; monitor and call 999 if she loses consciousness or does not recover within 2 minutes", "C. Administer adrenaline 500 micrograms IM into the anterolateral thigh immediately", "D. Administer atropine 1mg IV immediately — significant bradycardia in a bisoprolol patient requires IV atropine", "E. Perform defibrillation immediately — bradycardia of 38 bpm always requires defibrillation"],
        "correctAnswer": "B",
        "explanation": "Vasovagal syncope (neurocardiogenic syncope) is the most common cause of acute cardiovascular compromise during dental procedures. Precipitated by: anxiety, pain, sight of blood, prolonged standing. Mechanism: increased vagal tone → bradycardia + vasodilation → hypotension → cerebral hypoperfusion. Features: prodrome (nausea, pallor, diaphoresis, tunnel vision), then loss of consciousness; HR drops (as seen here — 38 bpm). Management: (1) IMMEDIATELY recline to flat/Trendelenburg (legs elevated above heart — increases venous return to the heart); (2) Ensure airway patent; (3) Monitor HR/SpO2; (4) The episode typically resolves within 2 minutes with this alone; (5) Give oral fluids and glucose when conscious. Bisoprolol blunts the normal tachycardic recovery phase, so bradycardia persists longer — but the management is still position change first, not drugs. Atropine is only needed if bradycardia is persistent and haemodynamically compromising after positional correction. Defibrillation is for shockable rhythms only."
    },
    {
        "id": "t5-m440", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly identifies the indication for prescribing aspirin in the PRIMARY prevention of cardiovascular disease?",
        "options": ["A. Aspirin 75mg should be prescribed to all adults over 50 years for primary CVD prevention", "B. Aspirin is NO LONGER recommended for primary prevention of CVD — the ASCEND, ARRIVE, and ASPREE trials showed that aspirin's bleeding risk (major GI and intracranial bleeding) equals or exceeds its modest primary prevention benefit in most populations without established CVD", "C. Aspirin is recommended for primary prevention in all patients with QRISK3 ≥10%", "D. Aspirin 75mg plus statin is the standard primary prevention strategy recommended by NICE", "E. Aspirin should be used for primary prevention in all patients with diabetes mellitus to prevent first MI"],
        "correctAnswer": "B",
        "explanation": "Aspirin in primary prevention: three landmark trials published in 2018 settled this debate. ASCEND (diabetes, no CVD): aspirin reduced serious vascular events by 12% but increased major bleeding by 29% — no net benefit. ARRIVE (intermediate CVD risk, no diabetes/CVD): no significant benefit in vascular events; increased GI bleeding. ASPREE (elderly >70 years, no CVD): aspirin associated with INCREASED all-cause mortality (predominantly from cancer and haemorrhage). Conclusion: for SECONDARY prevention (established CVD — post-MI, stroke, PAD): aspirin is recommended (clear net benefit — prevents recurrent events). For PRIMARY prevention (no established CVD): aspirin is NOT recommended in most patients — the bleeding risk neutralises the modest benefit. Exception: very high cardiovascular risk patients may still warrant aspirin after individual risk-benefit assessment. UK current guidelines (NICE, BCS): do NOT prescribe aspirin for primary prevention."
    },
    {
        "id": "t5-m441", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the mechanism of 'cardiac tamponade' and its haemodynamic effects?",
        "options": ["A. Cardiac tamponade occurs when the myocardium ruptures, allowing blood to enter the pericardial space and compress the great vessels", "B. Cardiac tamponade: accumulation of fluid in the pericardial space (blood, exudate, effusion) raises intrapericardial pressure → compresses cardiac chambers (right heart first — lower pressures) → reduces cardiac filling → reduced stroke volume and cardiac output → compensatory tachycardia; Beck's triad: hypotension, raised JVP, muffled heart sounds", "C. Cardiac tamponade only occurs with rapid accumulation of fluid — slow effusions never cause tamponade", "D. Cardiac tamponade causes a hyperkinetic circulation with increased cardiac output and low JVP", "E. Cardiac tamponade is treated with immediate surgical pericardiectomy as the only effective intervention"],
        "correctAnswer": "B",
        "explanation": "Cardiac tamponade: the pericardium is a relatively inelastic sac — rapid accumulation of even 200mL can cause tamponade if it accumulates quickly (e.g. haemopericardium from aortic dissection, cardiac rupture post-MI, penetrating trauma). Slower accumulation allows pericardial stretching — effusions of 1–2L may not cause tamponade if chronic. Mechanism: increased intrapericardial pressure → right ventricular filling impaired first (lower diastolic pressure) → reduced RV output → reduced LV filling → reduced cardiac output. Haemodynamics: hypotension + tachycardia (compensatory) + elevated JVP (pericardial compression impedes venous return but CVP rises as RV cannot fill). Beck's Triad: (1) Hypotension; (2) Elevated JVP (distended neck veins); (3) Muffled heart sounds (fluid attenuates sounds). Additional sign: pulsus paradoxus (>10 mmHg fall in SBP on inspiration). ECG: electrical alternans (alternating QRS amplitude from pendular heart motion). Treatment: pericardiocentesis (needle aspiration — even 50mL dramatically improves haemodynamics) or surgical drainage."
    },
    {
        "id": "t5-m442", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 65-year-old woman is admitted with palpitations and dizziness. Her ECG shows a regular narrow-complex tachycardia at 150 bpm. There are no clearly visible P-waves. Vagal manoeuvres fail to terminate the tachycardia. Which ONE of the following drugs is MOST appropriate to give next?",
        "options": ["A. IV amiodarone 300mg over 1 hour — the first-line drug for all narrow-complex tachycardias", "B. IV adenosine 6mg rapid bolus with a large-bore cannula and a fast saline flush — adenosine will either terminate AV node-dependent SVT or transiently slow the ventricular rate revealing the underlying atrial rhythm (e.g. flutter waves)", "C. IV metoprolol 5mg slowly — beta-blockers are first-line for narrow-complex tachycardia", "D. Synchronised DC cardioversion immediately — narrow-complex tachycardia at 150 bpm always requires cardioversion", "E. IV digoxin 500 micrograms — first-line for terminating SVT in acute settings"],
        "correctAnswer": "B",
        "explanation": "Narrow-complex tachycardia at 150 bpm: regular, no visible P-waves. The rate of exactly 150 bpm raises the clinical suspicion of atrial flutter with 2:1 block (atrial rate 300 bpm, exactly half = 150 ventricular) — flutter waves may be hidden within the QRS or T-wave. After failed vagal manoeuvres: adenosine 6mg IV rapid bolus (followed by 12mg if no response). Dual diagnostic/therapeutic role: (1) If AVNRT or AVRT: terminates the re-entrant circuit → sinus rhythm; (2) If atrial flutter 2:1: transiently slows ventricular rate (AV block from adenosine) → flutter waves become visible ('sawtooth' pattern at 300 bpm) → confirms diagnosis → patient goes to electrical cardioversion or rate control. Adenosine contraindications: WPW (risk of VF), severe asthma (bronchospasm — relative), heart transplant (exquisitely sensitive — use 1–3mg). Warn the patient: brief intense flushing, chest tightness, feeling of impending doom."
    },
    {
        "id": "t5-m443", "theme": 5, "topicTag": "hypertension",
        "question": "A 78-year-old woman with hypertension, heart failure, and CKD (eGFR 35 mL/min) is on ramipril 5mg, amlodipine 10mg, and bisoprolol 5mg. Her BP is 138/85 mmHg on these three drugs. Her cardiologist suggests adding an MRA (eplerenone 25mg) for heart failure benefit. Which ONE of the following is the MOST important laboratory parameter to monitor after starting eplerenone?",
        "options": ["A. Liver function tests — eplerenone is extensively hepatically metabolised and causes hepatotoxicity in CKD", "B. Serum potassium and eGFR — the combination of ACE inhibitor + MRA in CKD significantly increases hyperkalaemia and AKI risk; check at 1 week and regularly thereafter", "C. Complete blood count — eplerenone causes bone marrow suppression in elderly patients", "D. Serum sodium — eplerenone causes severe dilutional hyponatraemia in CKD patients", "E. Thyroid function — MRAs alter thyroid hormone metabolism in patients with CKD"],
        "correctAnswer": "B",
        "explanation": "ACE inhibitor (ramipril) + MRA (eplerenone) combination in CKD: high hyperkalaemia risk. Mechanism: both drugs reduce aldosterone-mediated K+ excretion in the collecting duct → additive K+ retention. With CKD (eGFR 35 — Stage 3b): reduced baseline renal K+ excretion amplifies this risk. Monitoring: serum K+ and eGFR at baseline, 1 week after starting, 4 weeks, and then every 3–6 months. Action thresholds: K+ 5.0–5.5: review and adjust doses; K+ >5.5: reduce or stop MRA; K+ >6.0: STOP MRA urgently and reassess. The RALES trial excluded patients with K+ >5.0 and creatinine >220 µmol/L at baseline. The real-world complication: after the RALES trial publication, hyperkalaemia hospitalisations and deaths increased substantially in the community — prescribers failed to monitor electrolytes appropriately. Eplerenone is more selective (fewer sex hormone side effects than spironolactone — no gynaecomastia) but equally potent for K+ effects."
    },
    {
        "id": "t5-m444", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following correctly describes the pathophysiology of 'intermittent claudication' and why pain resolves with rest?",
        "options": ["A. Claudication pain is caused by lactic acid accumulation in the calf muscles during exercise; rest restores oxygen delivery allowing aerobic metabolism — lactic acid cleared — pain resolves", "B. Claudication pain is neuropathic — peripheral nerve ischaemia causes paresthesia that mimics muscular pain; it resolves with rest as neural conduction recovers", "C. Claudication pain is caused by muscle cramps from electrolyte disturbance during exercise; rest allows electrolyte re-equilibration", "D. Claudication is caused by venous insufficiency — exercise increases venous pressure causing compartment syndrome", "E. Claudication pain is caused by skeletal muscle infarction; rest prevents further infarction but the dead muscle causes continued pain"],
        "correctAnswer": "A",
        "explanation": "Intermittent claudication pathophysiology: at rest, blood flow through a significantly stenosed artery is sufficient for resting metabolic demand. During exercise: exercising muscle oxygen demand increases dramatically. The fixed stenosis cannot increase flow proportionally → relative ischaemia → anaerobic glycolysis → lactic acid accumulation → tissue acidosis → activation of muscle nociceptors → ischaemic muscle pain. Pain is typically described as a cramping/aching in the calf (SFA occlusion) or thigh/buttock (iliac disease). Rest: exercise stops → oxygen demand falls back to resting level → existing blood flow is sufficient → aerobic metabolism resumes → lactic acid cleared by aerobic oxidation → pain resolves within 2–5 minutes. This 'consistent distance walked before pain, consistent rest time' pattern distinguishes claudication from spinal stenosis (neurogenic claudication — variable distance, may need to sit/bend forward, slower recovery) and musculoskeletal conditions."
    },
    {
        "id": "t5-m445", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 55-year-old man has stable coronary artery disease and develops chronic stable angina despite aspirin 75mg and atorvastatin 80mg. He is already on bisoprolol 10mg but still gets angina on moderate exertion. Which ONE of the following is the MOST appropriate addition to his antianginal regimen?",
        "options": ["A. Add amlodipine (dihydropyridine CCB) — second-line antianginal after beta-blocker; reduces afterload and coronary vasospasm; can be combined safely with bisoprolol", "B. Add verapamil — the preferred second-line antianginal agent after bisoprolol; safe in combination with bisoprolol", "C. Add digoxin — the evidence-based second-line antianginal agent for stable CAD", "D. Add isosorbide mononitrate only — long-acting nitrate is always preferred over CCB as second-line angina therapy", "E. Increase bisoprolol to 20mg — dose escalation is always the preferred strategy before adding a second drug class"],
        "correctAnswer": "A",
        "explanation": "Stable angina management: Step 1: aspirin + statin + sublingual GTN for acute episodes + beta-blocker (or rate-limiting CCB if beta-blocker contraindicated). Step 2: if angina persists despite maximally tolerated beta-blocker, add: dihydropyridine CCB (amlodipine, nifedipine) — safe to combine with beta-blocker (reduces peripheral resistance — afterload reduction; coronary vasodilation). OR long-acting nitrate (isosorbide mononitrate) with nitrate-free interval. Verapamil and diltiazem (rate-limiting CCBs) are CONTRAINDICATED with beta-blockers (combined AV nodal depression → bradycardia, heart block). Bisoprolol is already at 10mg — significant dose; increasing to 20mg is non-standard. If dual therapy fails: consider revascularisation (PCI or CABG), or ivabradine (if sinus rhythm and HR >70 on maximally tolerated beta-blocker), ranolazine, or nicorandil."
    },
    {
        "id": "t5-m446", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on warfarin for AF presents with a large spontaneous gingival haematoma that is oozing continuously. His INR is 3.1 (therapeutic range 2–3). Which ONE of the following is the MOST appropriate immediate management?",
        "options": ["A. Stop warfarin immediately and prescribe vitamin K 10mg orally", "B. Apply direct pressure with a gauze pack soaked in tranexamic acid mouthwash (5%) for 20 minutes; if bleeding stops, prescribe tranexamic acid 5% mouthwash 10mL QDS for 3 days; do not alter warfarin; contact anticoagulant clinic to note the event", "C. Refer immediately to accident and emergency — all bleeding in anticoagulated patients requires hospital management", "D. Give FFP 2 units to correct the INR before attempting haemostasis", "E. Irrigate with chlorhexidine and pack with oxidised cellulose without touching the INR"],
        "correctAnswer": "B",
        "explanation": "Gingival haemorrhage in a warfarin patient with INR 3.1 (only marginally above therapeutic range — and therapeutic for mitral valve patients): Management priorities: (1) Local haemostasis FIRST — direct pressure with gauze pack soaked in tranexamic acid 5% for 20 minutes (tranexamic acid inhibits fibrinolysis at the wound site — antifibrinolytic); (2) If bleeding controlled: prescribe tranexamic acid 5% mouthwash 10mL QDS for 2–3 days (bite on soaked gauze for 10–20 minutes — reduces rebleeding); (3) Do NOT stop warfarin (INR 3.1 is therapeutic — bleeding risk does not outweigh thromboembolism risk); (4) Identify the cause of gingival bleeding (plaque-induced inflammation amplified by anticoagulation) — oral hygiene instruction and review; (5) Contact anticoagulant clinic if multiple bleeds or escalating. Systemic reversal (FFP, PCC) is only for serious haemorrhage — gingival bleeding is minor and responds to local measures."
    },
    {
        "id": "t5-m447", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the physiological basis of 'ankle clonus' in patients with hypertensive encephalopathy or hypertensive urgency?",
        "options": ["A. Ankle clonus in hypertension is caused by peripheral nerve damage from chronic hypertension causing polyneuropathy", "B. In hypertensive encephalopathy, severely elevated BP causes cerebral oedema with failure of cerebral autoregulation (forced dilation of cerebral arterioles and blood-brain barrier breakdown) → generalised neurological dysfunction including upper motor neurone signs (clonus, hyperreflexia) from cortical/brainstem dysfunction", "C. Ankle clonus is a specific side effect of ACE inhibitor therapy in patients with hypertension", "D. Ankle clonus in hypertension indicates peripheral vascular disease causing ischaemia of the peripheral nervous system", "E. Ankle clonus in hypertension is caused by hypocalcaemia from thiazide diuretic therapy causing neuromuscular hyperexcitability"],
        "correctAnswer": "B",
        "explanation": "Hypertensive encephalopathy: a medical emergency caused by failure of cerebral autoregulation. Normal autoregulation: cerebral blood flow maintained constant across BP range 50–150 mmHg by vasoconstriction/dilation. When mean arterial pressure (MAP) exceeds the upper limit of autoregulation (varies by baseline BP — higher in chronic hypertensives): cerebrovascular resistance cannot compensate → forced vasodilation → cerebral hyperperfusion → breakdown of the blood-brain barrier → vasogenic oedema → increased intracranial pressure. Neurological features: severe headache, nausea/vomiting, visual disturbance, confusion, seizures, focal neurological signs (including UMN signs — hyperreflexia, clonus) from cortical/subcortical dysfunction. Fundoscopy: papilloedema (grade IV hypertensive retinopathy), flame haemorrhages, cotton wool spots. Management: IV labetalol or sodium nitroprusside — reduce MAP by 10–15% in the first hour (not more rapidly — risks ischaemic stroke from over-correction)."
    },
    {
        "id": "t5-m448", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "Which ONE of the following correctly identifies the embolic complication MOST specific to left-sided infective endocarditis?",
        "options": ["A. Pulmonary emboli — vegetations from left-sided valves break off and lodge in the pulmonary circulation", "B. Systemic arterial emboli (cerebral, renal, splenic, mesenteric, coronary) — vegetation fragments from left-sided valves enter the systemic circulation and can occlude any major artery", "C. Deep vein thrombosis — IE causes a hypercoagulable state leading to DVT", "D. Mesenteric venous thrombosis — IE specifically causes venous rather than arterial emboli", "E. Portal vein thrombosis — embolism from left-sided valves specifically affects the portal circulation"],
        "correctAnswer": "B",
        "explanation": "Left-sided IE embolic complications: vegetation fragments from the mitral or aortic valve → enter the systemic circulation → can lodge in any arterial territory. Most common and clinically significant: (1) Cerebral emboli (stroke, TIA, cerebral abscess) — in up to 30% of left-sided IE; most feared; may be the presenting feature before cardiac signs appear; (2) Renal emboli → renal infarction + haematuria + loin pain; (3) Splenic emboli → splenic infarction + left upper quadrant pain; (4) Mesenteric emboli → bowel ischaemia; (5) Coronary emboli → STEMI. Right-sided IE (tricuspid valve): vegetations → pulmonary emboli (multiple bilateral cavitating lung lesions on imaging). Immune complex deposition (not emboli): (1) Glomerulonephritis (haematuria, proteinuria); (2) Osler's nodes (painful nodules on finger pulps); (3) Roth's spots (retinal haemorrhages with pale centres); (4) Janeway lesions (non-tender macules on palms/soles — septic emboli, NOT immune complex)."
    },
    {
        "id": "t5-m449", "theme": 5, "topicTag": "heart-failure",
        "question": "A 72-year-old man with decompensated heart failure (NYHA class III, EF 28%, LVEDP elevated) is admitted with worsening peripheral oedema and orthopnoea despite oral furosemide 80mg BD. Which ONE of the following is the MOST appropriate change to his diuretic therapy?",
        "options": ["A. Switch to oral spironolactone — MRAs are more effective than loop diuretics for acute decompensated HF", "B. IV furosemide (equivalent to or higher than current oral dose) to overcome gut oedema impairing oral absorption; consider continuous infusion or twice-daily boluses; target urine output 0.5–1 mL/kg/hr", "C. Add oral bendroflumethiazide to the existing furosemide — the thiazide combination is most effective for acute decompensation", "D. Restrict fluid to 500mL/24 hours as the primary intervention — diuretic therapy is not required if fluid restriction is strict enough", "E. Withhold all diuretics for 48 hours to allow renin system 'reset' before reintroducing at higher dose"],
        "correctAnswer": "B",
        "explanation": "Acute decompensated HF with diuretic resistance: gut oedema (from raised right heart pressures) impairs oral drug absorption — oral furosemide bioavailability falls from ~50% at baseline to 10–20% in decompensated HF. Switching to IV furosemide bypasses GI absorption → predictable, rapid diuresis. DOSE trial: continuous IV infusion vs bolus IV furosemide → no significant difference in outcomes; bolus dosing easier. Starting IV furosemide dose: 2.5× the total daily oral dose (e.g. oral 160mg daily → IV 40mg BD or higher). Target: urine output 100–150 mL/hour initially; daily weight reduction 0.5–1 kg/day. Metolazone can be added for resistant cases (sequential nephron blockade). Monitor: daily electrolytes (hypokalaemia, hyponatraemia), creatinine, and fluid balance chart. Transition back to oral diuretics when stable (when gut oedema resolves, oral bioavailability returns to baseline)."
    },
    {
        "id": "t5-m450", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A 60-year-old patient with ischaemic heart disease (previous MI, EF 40%) is taking aspirin 75mg, ticagrelor 90mg BD, bisoprolol 5mg, ramipril 5mg, and atorvastatin 80mg. He presents with an acute dentoalveolar abscess causing facial swelling, trismus, and fever. He requires urgent incision and drainage (I&D) and dental extraction. Which ONE of the following antibiotic, if prescribed, would have the MOST clinically significant interaction with his current medications?",
        "options": ["A. Amoxicillin 500mg three times daily — minimal cardiovascular drug interactions", "B. Metronidazole 400mg three times daily — inhibits CYP2C9 and CYP3A4; raises warfarin INR dramatically (less relevant here as no warfarin), but has no significant interaction with ticagrelor or aspirin", "C. Clarithromycin 500mg twice daily — potent CYP3A4 inhibitor; significantly raises ticagrelor plasma levels (ticagrelor is a CYP3A4 substrate) → increased antiplatelet effect and bleeding risk; also raises atorvastatin levels → myopathy risk", "D. Cefalexin 500mg four times daily — beta-lactam with significant cardiac drug interactions", "E. Doxycycline 100mg twice daily — tetracycline that inhibits atorvastatin metabolism causing rhabdomyolysis"],
        "correctAnswer": "C",
        "explanation": "Clarithromycin + ticagrelor: clarithromycin is a potent CYP3A4 inhibitor; ticagrelor is predominantly metabolised by CYP3A4 → clarithromycin dramatically increases ticagrelor plasma levels → greatly enhanced P2Y12 receptor blockade → significantly increased bleeding risk. This interaction is listed as a CONTRAINDICATION in the ticagrelor SmPC — avoid concurrent use. Additionally, clarithromycin inhibits atorvastatin CYP3A4 metabolism → elevated statin levels → myopathy/rhabdomyolysis risk. Correct antibiotic choice for this patient: Amoxicillin 500mg TDS (minimal cardiac drug interactions — safe choice); if penicillin-allergic: metronidazole ± doxycycline (metronidazole is safe with ticagrelor — no CYP3A4 interaction; doxycycline is safe with atorvastatin at standard doses). Always check the BNF interaction checker before prescribing antibiotics to patients on ticagrelor, prasugrel, or statins. The patient's acute infection requires urgent treatment — choose the safest effective antibiotic."
    }
]

data['mockBank'].extend(new_mock)

with open('data/theme-5.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"mockBank total: {len(data['mockBank'])}")
