import json

with open('data/theme-5.json', 'r') as f:
    data = json.load(f)

new_mock = [
    {
        "id": "t5-m391", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the physiological basis of 'splitting' of the second heart sound (S2) and its clinical significance?",
        "options": ["A. S2 splitting occurs when the mitral valve closes before the tricuspid valve during diastole", "B. S2 is produced by closure of the aortic (A2) and pulmonary (P2) valves; physiological splitting widens on inspiration (increased RV filling → delayed P2) and narrows on expiration; fixed splitting suggests ASD; paradoxical splitting (widens on expiration) suggests LBBB or severe AS", "C. S2 splitting is always pathological and indicates severe pulmonary hypertension", "D. Wide fixed splitting of S2 is the hallmark of ventricular septal defect (VSD)", "E. S2 splitting only occurs in children and disappears at skeletal maturity"],
        "correctAnswer": "B",
        "explanation": "Second heart sound (S2) = aortic valve closure (A2) + pulmonary valve closure (P2). Normally A2 precedes P2 by <30ms (heard as single sound). Physiological splitting: on inspiration → increased intrathoracic negative pressure → increased RV venous return → RV takes longer to eject → delayed P2; simultaneously reduced LV preload → A2 earlier. Net: A2-P2 interval widens on inspiration (audible splitting), narrows on expiration. Pathological: Fixed splitting (ASD — left-to-right shunt provides constant extra RV volume; P2 consistently delayed regardless of respiration). Wide splitting (RBBB, pulmonary stenosis — delayed P2). Paradoxical/reversed splitting (LBBB, severe AS, HCM — A2 is severely delayed, now A2 follows P2; splitting heard on expiration, disappears on inspiration). Loud P2 = pulmonary hypertension."
    },
    {
        "id": "t5-m392", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 62-year-old woman undergoes coronary angiography which reveals a 45% stenosis of the left anterior descending artery. Her fractional flow reserve (FFR) measurement is 0.76. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Medical therapy only — a 45% stenosis is never haemodynamically significant and PCI is not indicated", "B. Proceed with PCI (stent placement) — FFR ≤0.80 indicates a haemodynamically significant stenosis that will benefit from revascularisation", "C. Surgical bypass (CABG) — all LAD stenoses require surgical rather than percutaneous revascularisation", "D. FFR 0.76 is within the normal range — no further treatment required beyond lifestyle advice", "E. Repeat angiography in 6 months — FFR measurements are unreliable and require confirmation"],
        "correctAnswer": "B",
        "explanation": "Fractional Flow Reserve (FFR): a wire-based pressure measurement during coronary angiography. FFR = mean distal coronary pressure / mean aortic pressure during maximal hyperaemia (adenosine-induced). FFR represents the fraction of normal maximum coronary flow achievable despite the stenosis. FFR ≤0.80: haemodynamically significant stenosis — insufficient flow to meet myocardial demand → ischaemia → PCI improves outcomes (DEFER, FAME, FAME-2 trials). FFR >0.80: stenosis is not flow-limiting — medical therapy is equivalent to PCI (avoiding unnecessary revascularisation). A 45% visual stenosis might appear non-significant, but FFR 0.76 proves it causes ischaemia — PCI is indicated. FFR allows targeting only functionally significant lesions, reducing unnecessary stenting and complications."
    },
    {
        "id": "t5-m393", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient presents to the dental emergency clinic with a grossly swollen face, trismus, and high fever from a lower third molar abscess. He is on dabigatran 150mg twice daily for AF. He had his morning dose at 7am, and it is now 11am. He requires urgent surgical drainage under general anaesthesia. Which ONE of the following is the MOST appropriate management of his anticoagulation?",
        "options": ["A. Proceed immediately with GA without any modification — dabigatran wears off quickly", "B. Delay surgery for 48 hours until dabigatran is fully cleared, then proceed", "C. Contact the anaesthetist and haematology team urgently; consider idarucizumab (Praxbind) for rapid dabigatran reversal if surgery cannot be safely delayed; assess renal function (determines dabigatran clearance)", "D. Give 4-factor PCC (Beriplex) to reverse dabigatran before GA", "E. Switch to warfarin immediately and proceed with surgery once INR normalises"],
        "correctAnswer": "C",
        "explanation": "Urgent surgery in a dabigatran patient: dabigatran (direct thrombin inhibitor) has a half-life of 12–17 hours (longer in renal impairment — up to 30+ hours). At 11am (4 hours post-dose), significant anticoagulant effect remains. For life/limb-threatening emergency where surgery cannot be delayed: idarucizumab (Praxbind) — a humanised monoclonal antibody fragment that binds dabigatran with extremely high affinity (350× greater than thrombin), completely reversing anticoagulation within minutes. RE-VERSE AD trial confirmed efficacy. Dose: 5g IV (two 2.5g doses). For less urgent situations: assess if surgery can wait until dabigatran cleared (consider eGFR — if eGFR >80, dabigatran 90% cleared in ~24h; if eGFR 30–50, takes 48h). 4F-PCC reverses factor Xa inhibitors (apixaban, rivaroxaban), not dabigatran. Andexanet alfa reverses factor Xa inhibitors."
    },
    {
        "id": "t5-m394", "theme": 5, "topicTag": "hypertension",
        "question": "Which ONE of the following correctly describes 'white coat hypertension' and its clinical significance?",
        "options": ["A. White coat hypertension is a serious condition requiring immediate pharmacological treatment as it inevitably progresses to sustained hypertension within 1 year", "B. White coat hypertension: elevated BP in the clinic (≥140/90) with normal ABPM (<135/85 daytime); prevalence ~20%; associated with some increased cardiovascular risk compared to truly normal BP but significantly less than sustained hypertension; monitoring without pharmacological treatment is appropriate in most cases", "C. White coat hypertension is diagnosed when BP is elevated on home monitoring but normal in clinic", "D. White coat hypertension has no cardiovascular risk implications and requires no follow-up once identified", "E. White coat hypertension is treated identically to sustained hypertension as the mechanism of risk is the same"],
        "correctAnswer": "B",
        "explanation": "White coat hypertension (WCH): BP elevated in clinical settings but normal on ABPM/HBPM. Prevalence: ~15–20% of those with clinic-elevated BP. Diagnosis: requires ABPM or HBPM to confirm. ABPM: daytime average <135/85 mmHg. Cardiovascular risk: WCH patients have higher CV risk than normotensives (some studies suggest true WCH may represent subclinical vascular changes) but substantially lower risk than sustained hypertension. Management: lifestyle advice (diet, exercise, weight, smoking cessation, alcohol reduction); repeat ABPM every 1–2 years (up to 15% progress to sustained hypertension over 10 years); no pharmacological treatment for uncomplicated WCH unless other risk factors are present. 'Masked hypertension' (opposite): normal clinic BP, elevated ABPM — may have higher CV risk than WCH and requires treatment."
    },
    {
        "id": "t5-m395", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "A 68-year-old man with severe calcific aortic stenosis (aortic valve area 0.6 cm², mean gradient 55 mmHg) is considered too high risk for conventional surgical aortic valve replacement (SAVR). Which ONE of the following is the MOST appropriate intervention?",
        "options": ["A. Balloon aortic valvuloplasty — the definitive treatment for severe AS in high-risk surgical patients", "B. Transcatheter aortic valve implantation (TAVI/TAVR) — a catheter-delivered bioprosthetic valve deployed within the native stenotic valve; proven to reduce mortality vs medical therapy in inoperable patients and non-inferior to SAVR in high-risk patients", "C. Medical management with ACE inhibitors — reduces the transvalvular gradient without surgery", "D. Dobutamine infusion therapy — long-term inotropic support maintains cardiac output across the stenotic valve", "E. Implantable cardioverter defibrillator (ICD) — prevents sudden cardiac death, which is the most common complication of severe AS"],
        "correctAnswer": "B",
        "explanation": "Transcatheter Aortic Valve Implantation (TAVI/TAVR): a collapsible bioprosthetic valve crimped onto a catheter and delivered via the femoral artery (transfemoral — most common) or alternative access (transapical, transaortic) to the native aortic valve position. The bioprosthetic valve is deployed within the calcified native valve (valve-in-valve). Evidence: PARTNER 1 trial — TAVI superior to medical therapy in inoperable patients; PARTNER 1B — non-inferior to SAVR in high surgical risk. Subsequent trials (PARTNER 2, SURTAVI, PARTNER 3, Evolut Low Risk): TAVI now non-inferior or superior to SAVR in intermediate and low surgical risk patients. Balloon aortic valvuloplasty: temporary palliation only (restenosis within months) — not definitive treatment. TAVI is now the predominant method for AS treatment in most centres."
    },
    {
        "id": "t5-m396", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient with AF and chronic kidney disease (eGFR 18 mL/min/1.73m²) requires anticoagulation. Which ONE of the following is the MOST appropriate anticoagulant?",
        "options": ["A. Apixaban 5mg twice daily — DOACs are preferred in all CKD stages including dialysis", "B. Warfarin — remains appropriate in severe CKD (eGFR <30) where DOACs are contraindicated or not recommended; INR monitoring is essential", "C. Dabigatran 150mg twice daily — best DOAC for severe CKD due to minimal renal excretion", "D. Rivaroxaban 20mg once daily — safe in all CKD stages including eGFR <15", "E. No anticoagulation is possible in severe CKD — the risk always outweighs the benefit"],
        "correctAnswer": "B",
        "explanation": "Anticoagulation in severe CKD (eGFR 15–29) and end-stage renal disease (eGFR <15/dialysis): All DOACs are renally cleared to varying degrees and accumulate in severe CKD → increased bleeding risk. Specific limits: dabigatran: contraindicated <30 mL/min. Rivaroxaban: use 15mg OD if eGFR 15–49; avoid if <15. Apixaban: can use down to eGFR 15 with dose adjustment (2.5mg BD if ≥2 of: age ≥80, weight ≤60kg, creatinine ≥133 µmol/L). For eGFR 18 (severe CKD not yet dialysis), apixaban is technically within its licensed range (just), but many guidelines still recommend warfarin for eGFR <25–30 due to accumulation risk. In dialysis patients: warfarin is the established choice (no renal clearance issue, INR-monitored); evidence for DOACs on dialysis is very limited. This patient at eGFR 18 warrants warfarin or specialist guidance."
    },
    {
        "id": "t5-m397", "theme": 5, "topicTag": "heart-failure",
        "question": "Which ONE of the following SGLT2 inhibitors has demonstrated mortality benefit specifically in patients with HFrEF, and what is its mechanism relevant to heart failure?",
        "options": ["A. Metformin — reduces cardiovascular events in HF by improving insulin sensitivity and reducing glycaemia", "B. Empagliflozin (or dapagliflozin) — SGLT2 inhibitors reduce glucose and sodium reabsorption in the proximal tubule → glycosuria, natriuresis → reduced preload and plasma volume → reduced HF hospitalisations and cardiovascular death (EMPEROR-Reduced, DAPA-HF trials) — effect is independent of diabetic status", "C. Sitagliptin — DPP-4 inhibitor that reduces cardiac fibrosis in HF patients", "D. Liraglutide — GLP-1 agonist shown to significantly reduce HF hospitalisations in all HF patients", "E. Pioglitazone — thiazolidinedione that reduces cardiac remodelling in HFrEF"],
        "correctAnswer": "B",
        "explanation": "SGLT2 inhibitors (sodium-glucose co-transporter 2 inhibitors — empagliflozin, dapagliflozin, canagliflozin) in HF: originally approved for type 2 diabetes, but landmark trials revealed major CV and HF benefits independent of glucose-lowering. DAPA-HF (dapagliflozin in HFrEF, with and without T2DM): 26% relative risk reduction in worsening HF or CV death. EMPEROR-Reduced (empagliflozin in HFrEF): 25% relative risk reduction in CV death + HF hospitalisation. Mechanism in HF (beyond glucose lowering): osmotic diuresis reducing preload; natriuresis; reduced plasma volume; improved cardiac energetics (increased ketone body utilisation as myocardial fuel); reduced inflammation and fibrosis; reduced epicardial fat. Now guideline-recommended (NICE, ESC) for HFrEF regardless of diabetes status. Note: pioglitazone is contraindicated in HF (causes fluid retention)."
    },
    {
        "id": "t5-m398", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 50-year-old man with AF is rate-controlled on bisoprolol 5mg daily. He continues to have frequent symptomatic palpitations and his AF has been present for 8 months. He prefers to try for sinus rhythm. Which ONE of the following is the MOST appropriate next step?",
        "options": ["A. Increase bisoprolol to 10mg — rate control optimisation is the only strategy for persistent AF", "B. Electrical cardioversion after at least 3–4 weeks of therapeutic anticoagulation (or TOE-guided early cardioversion to exclude LA thrombus) followed by antiarrhythmic drug therapy to maintain sinus rhythm", "C. Proceed to catheter ablation immediately — it is the first-line rhythm control strategy for all symptomatic AF", "D. Add digoxin to bisoprolol for better rate control — rhythm control is not possible after 8 months of AF", "E. Anticoagulate with warfarin for life but do not attempt rhythm restoration"],
        "correctAnswer": "B",
        "explanation": "Rhythm control strategy for persistent symptomatic AF: if the patient prefers sinus rhythm, attempt pharmacological or electrical cardioversion. Prerequisites: (1) Anticoagulation for ≥3–4 weeks before cardioversion (to allow any LA thrombus to organise/dissolve — new thrombus forms within 24–48h of AF onset); OR TOE to exclude LA thrombus → immediate cardioversion if no thrombus. (2) Continue anticoagulation for ≥4 weeks post-cardioversion (atrial stunning — mechanical function recovers later than electrical function). After cardioversion: antiarrhythmic drugs (flecainide for structurally normal heart; amiodarone if structural disease) to maintain sinus rhythm. Catheter ablation: more effective than drugs for maintaining SR in paroxysmal/persistent AF; considered if drugs fail or as first-line in selected patients. EAST-AFNET 4 trial: early rhythm control reduces CV events compared to rate control in newly diagnosed AF."
    },
    {
        "id": "t5-m399", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "A 72-year-old man has a popliteal artery aneurysm discovered incidentally on ultrasound. It measures 2.8cm in diameter. Which ONE of the following correctly identifies the MOST important complication of popliteal artery aneurysm (PAA)?",
        "options": ["A. Rupture — the most common complication, causing massive limb haematoma requiring emergency surgery", "B. Thromboembolism — thrombus within the aneurysm sac embolises distally into the tibial arteries, causing acute or chronic limb ischaemia; the most common clinically significant complication of PAA", "C. Venous compression — the aneurysm compresses the popliteal vein causing DVT", "D. Malignant transformation — large aneurysms develop sarcomatous change at the interface with the arterial wall", "E. Infection — spontaneous colonisation of the aneurysm with skin flora causing mycotic aneurysm"],
        "correctAnswer": "B",
        "explanation": "Popliteal artery aneurysm (PAA): the most common peripheral artery aneurysm (after AAA). Bilateral in 50% of cases; associated with AAA in 40% (screen for AAA if PAA found). Most important complication: thromboembolism — thrombus forms within the slow-flow sac → embolises distally into tibial/foot vessels → acute limb ischaemia (most dramatic) or chronic occlusion of tibial vessels ('trash foot' — microemboli causing digital ischaemia and poor revascularisation targets). Rupture is rare (unlike AAA — the popliteal fossa confines expansion). Venous/neurological compression occurs but less common. Popliteal nerve compression → pain/weakness. Indications for elective repair: symptomatic aneurysm; asymptomatic PAA ≥2cm (thromboembolism risk increases with size). Repair: surgical bypass (vein graft from femoral to popliteal, excluding the aneurysm) or endovascular exclusion."
    },
    {
        "id": "t5-m400", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes the mechanism of action of fondaparinux?",
        "options": ["A. Fondaparinux is a synthetic pentasaccharide that selectively binds antithrombin III, enhancing its inhibition of factor Xa only (not factor IIa/thrombin), and does not cross-react with HIT antibodies", "B. Fondaparinux is a direct oral thrombin inhibitor that does not require antithrombin as a cofactor", "C. Fondaparinux inhibits both factor Xa and thrombin equally — similar to unfractionated heparin but without the monitoring requirement", "D. Fondaparinux inhibits vitamin K epoxide reductase — same mechanism as warfarin but with more predictable pharmacokinetics", "E. Fondaparinux is a factor Xa inhibitor that directly binds factor Xa without antithrombin as a cofactor"],
        "correctAnswer": "A",
        "explanation": "Fondaparinux (Arixtra): a synthetic pentasaccharide sequence derived from heparin (the minimal sequence required for antithrombin III binding). Mechanism: binds antithrombin III → conformational change dramatically increases ATIII's affinity for factor Xa (NOT for thrombin/IIa — it is too short to bridge ATIII to thrombin). Selective indirect anti-Xa activity only. Key advantages over LMWH: (1) Does NOT bind platelet factor 4 (PF4) → does NOT cause HIT (does not form the PF4-drug complex that stimulates HIT antibodies — safe for use in HIT); (2) Once daily subcutaneous injection; (3) No routine monitoring required; (4) Renally eliminated (contraindicated if eGFR <30). Used for: VTE treatment and prophylaxis; ACS (OASIS-5 trial — superior to enoxaparin in NSTEMI for net clinical outcomes). Cannot be reversed by protamine."
    },
    {
        "id": "t5-m401", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the clinical features of 'pericarditis' and how it is distinguished from myocardial infarction on ECG?",
        "options": ["A. Pericarditis and MI have identical ECG appearances — the clinical history is the only distinguishing feature", "B. Pericarditis: sharp pleuritic chest pain (worse lying flat, relieved sitting forward); ECG shows saddle-shaped ST elevation in multiple leads (concave upwards) + PR depression; no reciprocal ST depression; friction rub on auscultation; elevated CRP/ESR; troponin may be mildly elevated if myopericarditis", "C. Pericarditis ECG: ST elevation only in V1–V4 with reciprocal depression in inferior leads — identical distribution to anterior STEMI", "D. Pericarditis always causes complete heart block on ECG", "E. Pericarditis is distinguished from MI by the presence of T-wave inversions in pericarditis and ST elevation only in MI"],
        "correctAnswer": "B",
        "explanation": "Acute pericarditis: inflammation of the pericardium. Classical features: (1) Sharp, pleuritic chest pain — worse on inspiration, lying down, movement; relieved by sitting forward (reduces pericardial pressure); (2) Pericardial friction rub — high-pitched scratching sound; (3) Fever. ECG: (1) Diffuse saddle-shaped (concave upward) ST elevation in multiple leads (unlike MI — focal, convex/tombstone ST elevation with reciprocal depression); (2) PR depression in multiple leads (pathognomonic — atrial involvement); (3) No reciprocal ST changes. Troponin elevated if myopericarditis (myocardial involvement). Distinguishing from MI: pericarditis → pan-lead ST change + PR depression + concave shape + pleuritic character. MI → focal territory ST change + convex/tombstone shape + reciprocal depression + cardiac risk factors. Echo: pericardial effusion (not always present). Treatment: NSAIDs + colchicine."
    },
    {
        "id": "t5-m402", "theme": 5, "topicTag": "atherosclerosis",
        "question": "Which ONE of the following medications is the MOST appropriate for primary prevention of cardiovascular events in a 55-year-old man with QRISK3 of 13%, LDL 4.2 mmol/L, and no contraindications?",
        "options": ["A. Atorvastatin 80mg — high-intensity statin for primary prevention in all patients with QRISK3 >10%", "B. Atorvastatin 20mg — NICE recommends lower-intensity statin for primary prevention (vs 80mg for secondary prevention) with target ≥40% non-HDL cholesterol reduction", "C. Rosuvastatin 40mg — maximum dose rosuvastatin is the preferred primary prevention statin", "D. Simvastatin 40mg — simvastatin is preferred for primary prevention over atorvastatin", "E. No statin — QRISK3 must exceed 20% before statin therapy is indicated for primary prevention"],
        "correctAnswer": "B",
        "explanation": "NICE statin guidelines for primary prevention: QRISK3 ≥10% → offer atorvastatin 20mg daily (note: NOT 80mg — that is secondary prevention). Target: ≥40% reduction in non-HDL cholesterol from baseline (check at 3 months). If target not achieved with 20mg: uptitrate or switch statin. Primary vs secondary prevention statin intensity: Primary prevention: atorvastatin 20mg (lower absolute risk means lower-intensity statin is proportionate). Secondary prevention (established CVD, DM with target organ damage, CKD, FH): atorvastatin 80mg (maximally intensive — higher absolute risk justifies more aggressive LDL reduction). Simvastatin 40mg has higher myopathy risk (CYP3A4 interactions) and lower LDL reduction than atorvastatin 20mg — atorvastatin is now preferred. Rosuvastatin 40mg is reserved for secondary prevention or FH when atorvastatin 80mg is insufficient."
    },
    {
        "id": "t5-m403", "theme": 5, "topicTag": "heart-failure",
        "question": "A 65-year-old man with HFrEF (EF 30%) on optimal medical therapy develops hyperkalaemia (K+ 6.1 mmol/L) and his eGFR falls to 28 mL/min. He is on ramipril 10mg, bisoprolol 10mg, and eplerenone 25mg. Which ONE of the following is the MOST appropriate adjustment?",
        "options": ["A. Stop all heart failure medications immediately and reassess in 4 weeks", "B. Stop eplerenone (MRA) first as it contributes most to hyperkalaemia in CKD; consider patiromer (potassium binder) to allow continued RAAS blockade; reduce ramipril dose if K+ remains elevated; do not stop beta-blocker", "C. Stop ramipril only — ACE inhibitors cause hyperkalaemia but MRAs do not", "D. Continue all medications unchanged — K+ 6.1 and eGFR 28 are acceptable in HFrEF patients", "E. Add furosemide at high dose — loop diuretics will rapidly correct the hyperkalaemia and renal impairment"],
        "correctAnswer": "B",
        "explanation": "Hyperkalaemia and renal impairment in HFrEF on triple RAAS blockade (ACE inhibitor + MRA): both ACE inhibitors and MRAs raise K+ (ACE inhibitor → reduced aldosterone-mediated K+ excretion; MRA → directly blocks aldosterone's K+-excreting effect). eGFR 28 further reduces K+ excretion. K+ 6.1 = dangerous — risk of life-threatening arrhythmia. Management priorities: (1) ECG immediately for hyperkalaemia changes; (2) Temporarily stop or halve eplerenone (MRA) — the drug most reducible without losing primary HF prognostic benefit; (3) Reduce ACE inhibitor dose if K+ remains high; (4) Consider potassium binders (patiromer, sodium zirconium cyclosilicate) — newer agents that can lower K+ and allow continued RAAS therapy; (5) Do NOT stop beta-blocker (does not cause hyperkalaemia; stopping may worsen HF acutely); (6) Dietary K+ restriction. Aim to restart MRA at lower dose when K+ normalises."
    },
    {
        "id": "t5-m404", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "Which ONE of the following correctly describes the management of blood pressure in the acute phase of ischaemic stroke?",
        "options": ["A. Aggressively lower BP to <130/80 mmHg immediately — high BP drives further infarction", "B. BP is typically not lowered in the acute phase of ischaemic stroke (first 24–72 hours) unless it is very high (>220/120 mmHg without thrombolysis, or >180/105 with thrombolysis) — the elevated BP maintains perfusion of the ischaemic penumbra via collateral vessels; aggressive BP lowering worsens infarct size", "C. Maintain systolic BP >200 mmHg for 72 hours to maximise collateral perfusion", "D. IV labetalol is mandatory for all acute ischaemic strokes to prevent haemorrhagic transformation", "E. Start standard antihypertensive therapy on the day of admission for all acute ischaemic stroke patients"],
        "correctAnswer": "B",
        "explanation": "Acute ischaemic stroke BP management: In the first 24–72 hours, cerebral autoregulation is impaired in the ischaemic zone — blood flow becomes pressure-dependent. The penumbra (ischaemic but salvageable tissue) depends on collateral flow maintained by the elevated systemic BP ('pressure breakthrough' at the ischaemic zone). Lowering BP acutely → reduced collateral perfusion → penumbra infarcted → larger final infarct. SCAST and COSSACS trials confirmed no benefit from routine acute BP lowering. NICE NG128 (2019): do not routinely lower BP unless: >220/120 without thrombolysis; >180/105 before/after thrombolysis; hypertensive encephalopathy; aortic dissection; acute heart failure. At 24–72 hours post-stroke: start long-term antihypertensive therapy for secondary prevention. Haemorrhagic stroke: lower BP to <140 mmHg systolic (reduces haematoma expansion)."
    },
    {
        "id": "t5-m405", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient on ramipril develops a dry persistent cough. The GP wants to continue RAAS blockade for hypertension and diabetic nephroprotection. Which ONE of the following is the MOST appropriate substitution?",
        "options": ["A. Switch to enalapril — a different ACE inhibitor is less likely to cause cough", "B. Switch to losartan (ARB — angiotensin receptor blocker) — ARBs block the angiotensin receptor without inhibiting ACE or bradykinin metabolism, so they do not cause cough", "C. Stop all RAAS blockade and switch to amlodipine — cough is a sign of ACE inhibitor toxicity requiring cessation of all renin-angiotensin drugs", "D. Add a cough suppressant (codeine) and continue ramipril — the cough is clinically insignificant", "E. Switch to a direct renin inhibitor (aliskiren) — similar efficacy to ACE inhibitors without bradykinin-mediated cough"],
        "correctAnswer": "B",
        "explanation": "ACE inhibitor cough: occurs in 10–20% of patients (higher incidence in East Asian populations — up to 30–40%). Mechanism: ACE inhibitors block kininase II → accumulation of bradykinin in the airways → prostaglandin and substance P release → dry irritating cough. ALL ACE inhibitors cause cough (class effect — switching between ACE inhibitors will not resolve it). Angiotensin receptor blockers (ARBs — losartan, valsartan, irbesartan, candesartan) block the AT1 receptor directly — do NOT affect ACE enzyme or bradykinin — no cough. The renal (anti-proteinuric) and cardiovascular protective effects of ARBs are equivalent to ACE inhibitors. ARBs are therefore the appropriate substitution for ACE inhibitor-induced cough. Note: ARBs are slightly more expensive and do not accumulate bradykinin — some argue bradykinin may contribute to ACE inhibitor benefits beyond angiotensin II blockade."
    },
    {
        "id": "t5-m406", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient reports taking 'a blood pressure tablet that also helps with anxiety.' He cannot recall the name. Which ONE of the following drug class MOST likely describes this combination of effects?",
        "options": ["A. ACE inhibitor — ramipril reduces anxiety through RAAS modulation in the central nervous system", "B. Beta-blocker (e.g. propranolol) — reduces peripheral manifestations of anxiety (tremor, palpitations, tachycardia) and is used for performance anxiety and situational anxiety as well as hypertension", "C. Thiazide diuretic — reduces anxiety by decreasing cortisol production", "D. Calcium channel blocker (amlodipine) — amlodipine has central anxiolytic properties", "E. ARB (losartan) — reduces anxiety by blocking AT1 receptors in the amygdala"],
        "correctAnswer": "B",
        "explanation": "Beta-blockers (non-selective: propranolol, nadolol; cardioselective: atenolol) are used for both hypertension and situational/performance anxiety. For anxiety: beta-blockers block peripheral beta-adrenergic manifestations of the fight-or-flight response — reduced tremor, palpitations, tachycardia, and sweating — without the sedation of benzodiazepines. Propranolol 10–40mg is commonly used for performance anxiety (examinations, public speaking, musical performances). It does NOT reduce the subjective/cognitive component of anxiety but eliminates the somatic symptoms that worsen the anxiety cycle. For dental anxiety: dental phobia patients may be on propranolol. Dental relevance: beta-blockers blunt the tachycardia response to adrenaline in LA, and the non-selective ones interact with adrenaline (risk of hypertensive episode if IV adrenaline administered — stick to dental doses with vasoconstrictor)."
    },
    {
        "id": "t5-m407", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes the mechanism of action of ticagrelor and how it differs from clopidogrel?",
        "options": ["A. Both ticagrelor and clopidogrel are prodrugs requiring hepatic activation; ticagrelor is more effective because it has a higher affinity for the P2Y12 receptor after activation", "B. Clopidogrel is a prodrug requiring CYP2C19 activation to active metabolite; ticagrelor is an active drug (not a prodrug) that reversibly inhibits P2Y12 — faster onset, more predictable platelet inhibition, not affected by CYP2C19 polymorphisms", "C. Ticagrelor inhibits COX-1, while clopidogrel blocks P2Y12 — they work on different platelet pathways", "D. Ticagrelor is a prodrug like clopidogrel but requires different CYP enzymes for activation", "E. Clopidogrel has more predictable pharmacokinetics than ticagrelor because clopidogrel does not require hepatic metabolism"],
        "correctAnswer": "B",
        "explanation": "Clopidogrel: thienopyridine prodrug → requires hepatic CYP2C19 activation → active metabolite irreversibly binds P2Y12 receptor. Problem: CYP2C19 polymorphisms (loss-of-function alleles — poor metabolisers, ~30% of Europeans, ~60% of Asians) → inadequate platelet inhibition → increased MACE risk. Ticagrelor: cyclopentyl-triazolo-pyrimidine — active drug (NOT a prodrug) → directly and REVERSIBLY binds P2Y12 receptor (different binding site from clopidogrel). Faster onset (2h vs 6h for clopidogrel); more consistent platelet inhibition (not affected by CYP2C19 genotype); reversible binding allows faster recovery of platelet function. PLATO trial: ticagrelor superior to clopidogrel post-ACS (16% relative reduction in CV death/MI/stroke). Side effect unique to ticagrelor: dyspnoea (adenosine-mediated — ticagrelor blocks adenosine reuptake); bradycardia. Caution: ticagrelor must not be given with aspirin >100mg (reduces efficacy)."
    },
    {
        "id": "t5-m408", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly identifies the ECG criteria for diagnosing long QT syndrome (LQTS) and the MOST common genetic cause?",
        "options": ["A. QTc >440ms in men or >460ms in women (Bazett's formula corrected for heart rate); LQTS1 (KCNQ1 mutation — loss of function of IKs potassium channel) is the most common genetic cause", "B. QT interval >500ms (uncorrected); LQT2 caused by SCN5A mutation is most common", "C. QTc >350ms; any QTc below this threshold indicates congenital LQTS", "D. QT interval >200ms measured from Q to end of T-wave; LQT3 caused by HERG mutation is most common", "E. QTc >550ms is required to diagnose LQTS; below this threshold, LQTS cannot be diagnosed regardless of symptoms"],
        "correctAnswer": "A",
        "explanation": "Long QT Syndrome (LQTS): prolonged cardiac repolarisation → risk of torsade de pointes (polymorphic VT) → syncope/sudden cardiac death. Diagnosis: QTc (corrected QT using Bazett's formula: QTc = QT/√RR) >440ms in men, >460ms in women (some sources use >450ms for both; >500ms is considered high risk). Genetic causes: LQT1 (35–45%): KCNQ1 mutation — reduced IKs (slow delayed rectifier K+ current); triggered by exercise/swimming. LQT2 (25–30%): KCNH2 (HERG) mutation — reduced IKr; triggered by sudden noises/emotional startle. LQT3 (5–10%): SCN5A mutation — increased INa (late sodium current — same gene as Brugada); triggered at rest/sleep. Clinical: syncope, seizures, cardiac arrest (often first presentation). Drug-induced LQTS (acquired — must exclude): antiarrhythmics, antipsychotics, antimicrobials, antiemetics."
    },
    {
        "id": "t5-m409", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "Which ONE of the following organisms is MOST commonly associated with IE in intravenous drug users, and which heart valve is most commonly affected?",
        "options": ["A. Streptococcus viridans affecting the mitral valve — same as community-acquired IE", "B. Staphylococcus aureus affecting the tricuspid valve — right-sided IE from contaminated injection materials is classic in IVDU; the tricuspid valve is most commonly involved as bacteria are injected directly into the venous circulation", "C. Enterococcus faecalis affecting the aortic valve — gut organisms seeding the aortic valve during faecal bacteraemia", "D. Candida albicans affecting all four valves simultaneously — fungal IE is the defining type in IVDU", "E. Pseudomonas aeruginosa affecting the pulmonary valve — Gram-negative organisms preferentially affect the right heart in IVDU"],
        "correctAnswer": "B",
        "explanation": "IV drug user (IVDU) IE: Staphylococcus aureus is the causative organism in >50–80% of cases in IVDU (from skin flora entering via needle injection). Tricuspid valve involvement: bacteria injected into peripheral veins → venous circulation → right heart → tricuspid valve directly exposed. Features of right-sided S. aureus IE: tricuspid valve vegetations; pulmonary emboli (septic emboli to lungs from right-sided vegetations — multiple bilateral cavitating consolidations on CXR/CT); less severe haemodynamic compromise than left-sided IE (tricuspid regurgitation is better tolerated than MR/AR). Also seen in IVDU: Candida, Pseudomonas, polymicrobial. Left-sided IE does occur in IVDU (aortic/mitral) and carries worse prognosis. Right-sided IE in IVDU generally has better prognosis and can often be managed medically without surgery."
    },
    {
        "id": "t5-m410", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following correctly describes the clinical significance of the 'ankle oedema' sign in a patient with chronic venous insufficiency versus cardiac or hepatic oedema?",
        "options": ["A. Venous, cardiac, and hepatic oedema are clinically identical and cannot be distinguished without laboratory tests", "B. Venous insufficiency oedema: predominantly unilateral, worse with prolonged standing/walking, improves with leg elevation overnight, associated with varicose veins, skin changes (haemosiderin staining, lipodermatosclerosis, venous ulcers at the medial malleolus); cardiac oedema: bilateral, symmetrical, pitting, associated with raised JVP, dyspnoea, orthopnoea; hepatic oedema: bilateral ankle oedema + ascites + jaundice + other signs of chronic liver disease", "C. Venous oedema is always non-pitting; cardiac oedema is always pitting — this is the sole distinguishing feature", "D. All forms of ankle oedema are caused by hypoalbuminaemia and are indistinguishable clinically", "E. Venous insufficiency oedema improves with diuretics; cardiac oedema resolves with leg elevation — opposite to common teaching"],
        "correctAnswer": "B",
        "explanation": "Distinguishing ankle oedema causes is a core clinical skill: Chronic venous insufficiency: mechanism = venous hypertension (failed valves/DVT history) → capillary hydrostatic pressure rise → fluid in interstitium. Features: often unilateral or asymmetric; worse throughout the day with standing; improves overnight with elevation; associated with dilated veins, skin changes (lipodermatosclerosis — woody induration and pigmentation from haemosiderin), medial malleolar venous ulcers; JVP normal; no dyspnoea. Treatment: compression hosiery. Heart failure: bilateral, pitting, associated with ↑JVP, bibasal crackles, orthopnoea/PND; responds to diuretics. Hepatic: bilateral + ascites + hypoalbuminaemia (oncotic pressure falls) + coagulopathy; no raised JVP unless concurrent cardiac disease. Hypoalbuminaemia alone: bilateral, non-inflammatory, no venous skin changes."
    },
    {
        "id": "t5-m411", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 58-year-old patient on amiodarone 200mg daily develops new-onset hypothyroidism (TSH 45 mIU/L, free T4 low). Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Stop amiodarone immediately — amiodarone-induced hypothyroidism always requires cessation of the drug", "B. Continue amiodarone; start levothyroxine replacement therapy — amiodarone-induced hypothyroidism (AIH) is easily managed with thyroid hormone replacement without stopping amiodarone, especially if amiodarone is controlling a dangerous arrhythmia", "C. Reduce amiodarone dose by 50% — hypothyroidism is dose-dependent and always resolves with dose reduction", "D. Start carbimazole — amiodarone-induced hypothyroidism has the same mechanism as Graves' disease and responds to antithyroid drugs", "E. Refer for thyroidectomy — surgical removal of the thyroid is first-line for all amiodarone-induced thyroid disease"],
        "correctAnswer": "B",
        "explanation": "Amiodarone-induced thyroid disease: amiodarone contains 37% iodine by weight and is structurally similar to thyroid hormones. Hypothyroidism (AIH): from iodine-excess inhibiting thyroid hormone synthesis (Wolff-Chaikoff effect — normal thyroid escapes, but diseased thyroid cannot). Management: continue amiodarone if the arrhythmia indication is strong (VT, AF — stopping amiodarone risks life-threatening arrhythmia return and amiodarone has a 40–55 day half-life anyway); start levothyroxine replacement — straightforward and effective. Hyperthyroidism type 1 (AIT-1): iodine excess driving autonomous thyroid tissue — treat with carbimazole/propylthiouracil. Hyperthyroidism type 2 (AIT-2): destructive thyroiditis from direct amiodarone toxicity — treat with prednisolone. Distinguishing type 1 vs 2 requires thyroid ultrasound and colour Doppler. Amiodarone and thyroid function should be monitored every 6 months in all patients."
    },
    {
        "id": "t5-m412", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly describes the murmur of hypertrophic obstructive cardiomyopathy (HOCM) and the manoeuvres that change its intensity?",
        "options": ["A. HOCM murmur is a pansystolic murmur at the apex radiating to the axilla; it increases with Valsalva and decreases on squatting — identical to mitral regurgitation", "B. HOCM murmur is a harsh ejection systolic murmur at the left sternal edge; it INCREASES with Valsalva (reduces preload → less LVOT filling → worse obstruction) and with standing; it DECREASES with squatting (increases preload and afterload → reduces LVOT obstruction)", "C. HOCM murmur is a diastolic murmur heard at the aortic area radiating to the carotids", "D. HOCM murmur is fixed and does not change with any manoeuvre — this differentiates it from valvular AS", "E. HOCM murmur decreases with Valsalva and increases with squatting — opposite to most other systolic murmurs"],
        "correctAnswer": "B",
        "explanation": "HOCM systolic murmur: harsh ejection systolic murmur at the left sternal edge (not radiating to carotids — unlike valvular AS). Dynamic obstruction means the murmur intensity changes with preload, afterload, and contractility: INCREASES (worsens) with: Valsalva manoeuvre (increased intrathoracic pressure → reduced venous return → reduced LV volume → worse LVOTO); standing (pooling of blood in legs → reduced preload); dehydration; tachycardia; amyl nitrite (vasodilation → reduced afterload + preload). DECREASES (improves) with: squatting (increased preload and afterload → larger LV → less LVOTO); leg raising (increased preload); phenylephrine (increased afterload → larger LV cavity); beta-blockers (reduced contractility and HR → less obstruction). This dynamic nature (increasing with Valsalva) is the defining feature distinguishing HOCM from valvular AS (which decreases or does not change with Valsalva)."
    },
    {
        "id": "t5-m413", "theme": 5, "topicTag": "cvd-overview",
        "question": "During a routine dental examination, a 50-year-old man is found to have a regular pulse of 44 bpm. He is asymptomatic, normotensive, and has no history of cardiac disease. He is a marathon runner. Which ONE of the following is the MOST likely explanation and appropriate management?",
        "options": ["A. Third degree heart block — urgent pacemaker referral is required", "B. Physiological sinus bradycardia from high vagal tone in an endurance athlete — no treatment required; confirm with 12-lead ECG and check for symptoms", "C. Hypothyroidism — prescribe levothyroxine without further investigation", "D. Sick sinus syndrome — refer urgently to cardiology for permanent pacemaker consideration", "E. Medication side effect — assume beta-blocker overdose and send to emergency department"],
        "correctAnswer": "B",
        "explanation": "Endurance athletes commonly develop marked resting bradycardia (HR 30–60 bpm) from increased vagal (parasympathetic) tone — a physiological adaptation. Sympathetic withdrawal and increased vagal drive dominate at rest → slower SA node firing. This is benign and does not require treatment. Confirm with a 12-lead ECG: in physiological sinus bradycardia — P-waves normal (upright in II, negative in aVR), normal PR interval, narrow QRS. If the patient is asymptomatic (no syncope, pre-syncope, exercise intolerance) → reassure. Red flags requiring further investigation: symptomatic bradycardia, structural heart disease, abnormal P-waves, variable PR interval, prolonged QRS (raising concern for infranodal block). Comparison to his resting ECGs (if available) shows chronic unchanged pattern. Complete heart block (option A) shows AV dissociation — P-waves and QRS unrelated — not physiological."
    },
    {
        "id": "t5-m414", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "Which ONE of the following correctly describes the concept of 'ischaemic preconditioning' and its therapeutic implications?",
        "options": ["A. Ischaemic preconditioning means that patients who have had a prior MI are immune to further MI — the damaged myocardium cannot be further injured", "B. Ischaemic preconditioning: brief episodes of sublethal ischaemia render the myocardium more resistant to a subsequent prolonged ischaemic insult; mediated by adenosine, opioids, and PKC activation; has inspired remote ischaemic preconditioning (brief limb ischaemia) as a cardioprotective strategy", "C. Ischaemic preconditioning is a pathological process that accelerates plaque rupture after a period of stable angina", "D. Ischaemic preconditioning describes the process by which collateral vessels develop over years of chronic stable angina", "E. Ischaemic preconditioning only occurs in neonates — adult myocardium does not respond to brief ischaemia"],
        "correctAnswer": "B",
        "explanation": "Ischaemic preconditioning (IPC): discovered in 1986 (Murry). Brief repetitive episodes of ischaemia (e.g., 5 minutes of occlusion × 4 cycles) before a prolonged ischaemic insult dramatically reduce myocardial infarct size (by 75% in animal models). Two phases: Early preconditioning (within minutes, lasts 1–2 hours): mediated by adenosine A1 receptors, opioid receptors, PKC activation → opening of mitochondrial KATP channels → reduced Ca2+ overload during subsequent ischaemia. Late preconditioning ('second window' — 12–24h later, lasting days): mediated by NOS, COX-2, heat shock proteins — protein synthesis-dependent. Clinical application: Remote ischaemic preconditioning (RIPC) — brief cycles of limb ischaemia (blood pressure cuff inflation to 200mmHg on upper arm for 5 min × 4 cycles) before planned cardiac surgery or primary PCI. Early trials promising; later large trials (ERICCA, RIPHeart) disappointing — perhaps because anaesthetics (especially propofol) blocked cardioprotective signalling."
    },
    {
        "id": "t5-m415", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient on warfarin for AF is admitted with an acute upper GI bleed. His INR is 6.2 and he is haemodynamically compromised (BP 85/60 mmHg, HR 118 bpm). Which ONE of the following is the MOST appropriate immediate management of the anticoagulation?",
        "options": ["A. Give oral vitamin K 5mg and transfuse blood — this is sufficient for all warfarin-related GI bleeds", "B. Stop warfarin; give IV vitamin K 10mg immediately; give 4-factor prothrombin complex concentrate (4F-PCC) — this combination rapidly reverses warfarin (PCC within minutes, Vitamin K sustains the reversal); fluid resuscitation and urgent GI endoscopy", "C. Give FFP 4 units — sufficient to reverse warfarin in major haemorrhage without needing PCC", "D. Continue warfarin — stopping anticoagulation in AF risks stroke and the GI bleed must be managed endoscopically without anticoagulation reversal", "E. Give platelet transfusion — the coagulopathy of warfarin is primarily a platelet disorder"],
        "correctAnswer": "B",
        "explanation": "Life-threatening warfarin-related haemorrhage (haemodynamic compromise, INR 6.2): requires IMMEDIATE reversal. (1) IV vitamin K 10mg — corrects INR over 6–12 hours by restoring vitamin K-dependent factor synthesis (II, VII, IX, X, proteins C and S); prevents rebound re-anticoagulation as PCC effect wanes after ~12–24h; (2) 4-factor prothrombin complex concentrate (4F-PCC — Beriplex, Octaplex) — IMMEDIATE reversal (within 10 minutes) by directly replacing all vitamin K-dependent clotting factors. Preferred over FFP (which requires large volumes to achieve equivalent factor levels, slower administration, greater transfusion reaction risk, no thrombosis risk from PCC). Target post-reversal INR <1.5. Simultaneously: IV access, blood/fluids, urgent GI endoscopy for definitive haemostasis. Restart anticoagulation when haemostasis secured — typically 7–14 days, depending on GI bleed cause and thromboembolic risk."
    },
    {
        "id": "t5-m416", "theme": 5, "topicTag": "hypertension",
        "question": "A 35-year-old woman is found to have consistently elevated BP of 175/105 mmHg. Blood tests reveal hypokalaemia (K+ 2.9 mmol/L), high plasma aldosterone, and suppressed renin. Which ONE of the following is the MOST likely diagnosis?",
        "options": ["A. Cushing's syndrome — elevated cortisol stimulates aldosterone receptors causing hypertension and hypokalaemia", "B. Primary hyperaldosteronism (Conn's syndrome) — autonomous aldosterone secretion from an adrenal adenoma or bilateral adrenal hyperplasia; aldosterone-to-renin ratio >30 is characteristic; hypokalaemia from aldosterone-driven urinary K+ wasting", "C. Phaeochromocytoma — catecholamine excess causing paroxysmal hypertension and hypokalaemia", "D. Renovascular hypertension (renal artery stenosis) — reduced renal perfusion causes elevated renin and secondary hyperaldosteronism", "E. Essential hypertension with thiazide-induced hypokalaemia — the most common explanation for this combination"],
        "correctAnswer": "B",
        "explanation": "Primary hyperaldosteronism (PA/Conn's syndrome): autonomous aldosterone production from adrenal cortex (unrelated to renin-angiotensin system). Causes: unilateral adrenal adenoma (35%) — classical 'Conn's adenoma'; bilateral adrenal hyperplasia (65%). Biochemistry: HIGH aldosterone + SUPPRESSED renin → high aldosterone-to-renin ratio (ARR >30–40 in standard units). Aldosterone stimulates Na+ retention + K+ excretion in the collecting duct → hypertension + hypokalaemia (though up to 50% of PA patients have normal K+). Diagnosis: aldosterone-to-renin ratio screening → confirmatory test (fludrocortisone suppression test); adrenal CT; adrenal vein sampling (to distinguish unilateral vs bilateral). Treatment: unilateral adenoma → laparoscopic adrenalectomy (curative); bilateral hyperplasia → mineralocorticoid receptor antagonist (spironolactone or eplerenone)."
    },
    {
        "id": "t5-m417", "theme": 5, "topicTag": "atherosclerosis",
        "question": "Which ONE of the following correctly describes the role of high-density lipoprotein (HDL) in atheroprotection?",
        "options": ["A. HDL causes atherosclerosis by transporting cholesterol from the liver to peripheral tissues", "B. HDL promotes reverse cholesterol transport — accepts cholesterol from peripheral tissues and macrophage foam cells in the arterial wall (via ABCA1, ABCG1 transporters), transporting it to the liver for excretion; it also has anti-inflammatory and antioxidant properties — explaining the inverse relationship between HDL and cardiovascular risk", "C. HDL is entirely neutral — its main function is to act as a carrier for triglycerides in the fasting state", "D. HDL reduces cardiovascular risk by directly inhibiting LDL oxidation in the circulation — all HDL benefit comes from this antioxidant function", "E. Low HDL is beneficial in patients with high LDL as it prevents excess cholesterol efflux from macrophages"],
        "correctAnswer": "B",
        "explanation": "High-density lipoprotein (HDL) and reverse cholesterol transport (RCT): HDL is synthesised in the liver and intestine as nascent pre-beta-HDL. In peripheral tissues: ABCA1 transporter on macrophage foam cells and other cells → transfers phospholipid and cholesterol to nascent HDL → forms mature spherical HDL. Cholesterol esterified by LCAT (lecithin-cholesterol acyltransferase). Mature HDL returns to liver → SR-BI receptor → hepatic uptake of cholesterol → bile excretion. Net effect: removes cholesterol from macrophage foam cells in atheromatous plaques → reduces plaque burden. Additional HDL functions: anti-inflammatory (suppresses VCAM-1/ICAM-1 expression on endothelium), antioxidant (reduces oxLDL), anti-thrombotic (promotes endothelial prostacyclin). HDL <1.0 mmol/L in men, <1.2 mmol/L in women is a cardiovascular risk factor. However, HDL-raising drug trials have largely failed — the quality/functionality of HDL particles matters beyond quantity."
    },
    {
        "id": "t5-m418", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient on aspirin 75mg daily for secondary prevention following an MI asks if he should stop taking it before his upper molar extraction next week. Which ONE of the following is the MOST appropriate advice?",
        "options": ["A. Stop aspirin 7 days before the extraction to allow platelet recovery and prevent post-extraction haemorrhage", "B. Continue aspirin — the increased bleeding risk from a single extraction is small and manageable with local haemostasis; stopping aspirin risks coronary thrombosis and MI recurrence, which is far more dangerous", "C. Halve the aspirin dose to 37.5mg for 2 weeks around the extraction as a compromise", "D. Switch to paracetamol for the 2 weeks surrounding the extraction and restart aspirin afterwards", "E. The patient must be admitted to hospital for the extraction under general anaesthetic as aspirin cannot be stopped for extractions"],
        "correctAnswer": "B",
        "explanation": "Aspirin in secondary cardiovascular prevention (post-MI): aspirin must NEVER be stopped without compelling reason. Post-MI aspirin reduces reinfarction and cardiovascular death risk by ~25%. Stopping aspirin → platelet function recovery over 7–10 days → increased thrombosis risk in partially re-endothelialised coronary vessels. The post-extraction bleeding risk from continuing aspirin is a manageable inconvenience (local haemostasis — sutures, oxidised cellulose packing, tranexamic acid mouthwash). The coronary thrombosis risk from stopping aspirin is potentially fatal. Evidence: multiple RCTs and systematic reviews confirm aspirin continuity is safe for dental extractions and other minor surgical procedures. This principle extends to patients on DAPT (also continue both antiplatelet drugs for most dental procedures as per BDA/SDCEP guidance)."
    },
    {
        "id": "t5-m419", "theme": 5, "topicTag": "heart-failure",
        "question": "Which ONE of the following correctly describes the pathophysiology of 'cardiac cachexia' in advanced heart failure?",
        "options": ["A. Cardiac cachexia is caused by the diuretic therapy prescribed for heart failure, which removes protein along with excess fluid", "B. Cardiac cachexia: involuntary weight loss >6% of body weight in advanced HF, caused by multiple mechanisms: elevated TNF-alpha, IL-6, and other pro-inflammatory cytokines causing muscle protein catabolism; malabsorption from gut oedema; increased resting metabolic rate; anorexia from hepatic congestion causing nausea and early satiety; neurohormonal activation (cortisol, aldosterone)", "C. Cardiac cachexia is caused exclusively by reduced caloric intake due to dyspnoea-related eating difficulty", "D. Cardiac cachexia only affects skeletal muscle — cardiac muscle is protected by compensatory hypertrophy in HF", "E. Cardiac cachexia is a side effect of beta-blocker therapy and resolves when beta-blockers are stopped"],
        "correctAnswer": "B",
        "explanation": "Cardiac cachexia: a severe complication of advanced HF affecting ~10–16% of patients. Associated with significantly worse prognosis (2-year mortality ~50%). Multifactorial pathophysiology: (1) Neurohormonal activation — RAAS, SNS, elevated cortisol → protein catabolism and reduced anabolic hormone (testosterone, IGF-1); (2) Pro-inflammatory cytokines (TNF-alpha — 'cachexin', IL-6, IL-1) from gut ischaemia and cardiac dysfunction → skeletal muscle wasting and apoptosis; (3) Gut oedema from right HF → malabsorption of nutrients; reduced intestinal mucosal integrity → bacterial translocation → more inflammation; (4) Elevated resting metabolic rate from increased work of breathing; (5) Anorexia — hepatomegaly causing early satiety, nausea; (6) Drug side effects. Treatment targets the underlying HF and inflammatory state; nutritional support is important. Cardiac cachexia is distinct from malnutrition — it is largely catabolic/inflammatory rather than simply reduced intake."
    },
    {
        "id": "t5-m420", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient taking carvedilol (non-selective beta-blocker + alpha-1 blocker) for heart failure attends for dental extraction requiring local anaesthetic. Which ONE of the following consideration regarding adrenaline in the local anaesthetic is MOST important?",
        "options": ["A. Adrenaline is absolutely contraindicated in all patients on any beta-blocker", "B. With non-selective beta-blockade (carvedilol, propranolol), IV adrenaline causes unopposed alpha-1 vasoconstriction → severe hypertension + reflex bradycardia; however, dental doses of adrenaline (2 cartridges of 1:100,000) administered with aspiration and slow injection carry very low risk in stable patients — use minimum effective dose and avoid intravascular injection", "C. Adrenaline is safer with non-selective beta-blockers than selective ones as the alpha-blockade component offsets the vasoconstriction", "D. Adrenaline at any dose causes fatal bradycardia in patients on carvedilol due to complete cardiac beta-1 blockade", "E. No special precautions are needed — carvedilol has no interaction with dental doses of adrenaline in local anaesthetics"],
        "correctAnswer": "B",
        "explanation": "Adrenaline-beta-blocker interaction: adrenaline acts on alpha-1 (vasoconstriction) and beta-1 (increased HR/contractility) and beta-2 (vasodilation) receptors. Normally: beta-2 vasodilation in peripheral vessels partially offsets alpha-1 vasoconstriction. With non-selective beta-blockade (propranolol, carvedilol — blocks both beta-1 and beta-2): beta-2 vasodilation in peripheral vessels is blocked → unopposed alpha-1 vasoconstriction → significant systemic BP rise → baroreceptor-mediated reflex bradycardia. This 'hypertensive-bradycardic' response is greatest with IV adrenaline. Dental relevance: standard dental LA adrenaline (2 cartridges × 36 micrograms = 72 micrograms; up to 4 cartridges in healthy adults = 144 micrograms) — at these doses, with correct technique (aspiration, slow injection), systemic absorption is minimal and the interaction is usually clinically insignificant. Intravascular injection = high risk. Carvedilol's alpha-1 blockade component partially offsets the concern, making it arguably slightly safer than propranolol alone."
    }
]

data['mockBank'].extend(new_mock)

with open('data/theme-5.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"mockBank total: {len(data['mockBank'])}")
