import json

with open('data/theme-5.json', 'r') as f:
    data = json.load(f)

new_mock = [
    {
        "id": "t5-m341", "theme": 5, "topicTag": "atherosclerosis",
        "question": "Which ONE of the following correctly describes the role of foam cells in atherogenesis?",
        "options": ["A. Foam cells are smooth muscle cells that migrate into the adventitia and produce collagen for plaque stabilisation", "B. Foam cells are lipid-laden macrophages formed when monocyte-derived macrophages in the intima engulf oxidised LDL via scavenger receptors — they are the hallmark of the fatty streak and early atherosclerotic plaque", "C. Foam cells are endothelial cells swollen with intracellular lipid that detach from the vessel wall and trigger thrombus formation", "D. Foam cells are platelets that adhere to exposed subendothelial collagen and become engorged with fibrin", "E. Foam cells are specialised T-lymphocytes that accumulate lipid and release cytokines causing plaque rupture"],
        "correctAnswer": "B",
        "explanation": "Foam cell formation is central to atherogenesis. Sequence: (1) Endothelial dysfunction from risk factors (hypertension, smoking, diabetes, dyslipidaemia) → increased permeability and VCAM-1/ICAM-1 expression; (2) Monocytes adhere and migrate into the intima → differentiate into macrophages; (3) Macrophages engulf oxidised LDL (oxLDL) via scavenger receptors (SR-A, CD36) — not downregulated by intracellular lipid (unlike LDL receptor) → unlimited lipid accumulation; (4) Lipid-laden macrophages = foam cells — visible macroscopically as 'fatty streaks.' Foam cells release pro-inflammatory cytokines (IL-1, TNF, MCP-1) perpetuating the inflammatory cycle. They eventually undergo apoptosis/necrosis, releasing lipid into the necrotic core of advanced plaques."
    },
    {
        "id": "t5-m342", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 58-year-old man presents with central chest pain at rest lasting 20 minutes that resolved spontaneously. His ECG shows transient ST depression in leads V4–V6. Troponin at 3 hours is mildly elevated (3× upper limit of normal). Which ONE of the following is the MOST appropriate diagnosis?",
        "options": ["A. Stable angina — troponin is elevated because the patient exercised before attending", "B. STEMI — ST depression indicates posterior MI requiring immediate primary PCI", "C. Non-ST elevation myocardial infarction (NSTEMI) — chest pain at rest, transient ST depression, and elevated troponin without ST elevation on ECG", "D. Unstable angina — troponin elevation confirms myocardial injury in classical unstable angina", "E. Musculoskeletal chest pain — elevated troponin is a laboratory error in young patients"],
        "correctAnswer": "C",
        "explanation": "NSTEMI (Non-ST Elevation MI) diagnosis requires: (1) Symptoms consistent with ACS (chest pain at rest); (2) ECG changes (ST depression, T-wave inversion, or no change — but no persistent ST elevation); (3) Troponin elevation above the 99th percentile upper reference limit (here 3× ULN = significant myocardial injury). NSTEMI differs from unstable angina (UA) by the presence of troponin elevation — UA has the same presentation but troponin is negative. NSTEMI indicates actual cardiomyocyte necrosis. STEMI requires persistent ST elevation. Posterior MI (option B) would cause ST elevation in V7–V9 mirror image — not the same as anterior ST depression alone. Management: DAPT (aspirin + ticagrelor), anticoagulation, risk stratification, and coronary angiography within 72 hours."
    },
    {
        "id": "t5-m343", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "A 35-year-old man with a ventricular septal defect (VSD) develops IE caused by Streptococcus viridans. Which ONE of the following correctly describes why VSD confers a high risk of IE?",
        "options": ["A. The VSD patch material is thrombogenic and acts as a nidus for bacterial adhesion", "B. High-velocity jet of blood through the VSD causes turbulent flow and endothelial damage at the site of impact — this creates a platelet-fibrin thrombus (non-bacterial thrombotic endocarditis — NBTE) that acts as a nidus for bacterial adhesion during bacteraemia", "C. VSD causes pulmonary hypertension which damages the right-sided valves, making them susceptible to IE", "D. VSD causes left-to-right shunt which reduces LV preload, causing compensatory LV hypertrophy that is at risk of IE", "E. VSDs specifically attract viridans streptococci through a surface receptor not present on normal endocardium"],
        "correctAnswer": "B",
        "explanation": "The Rocha Lima hypothesis of IE pathogenesis: congenital or valvular defects create high-velocity, turbulent jets → endothelial trauma at the site of impact (low-pressure side of the defect) → platelet-fibrin deposits form (NBTE — Non-Bacterial Thrombotic Endocarditis) → during transient bacteraemia, bacteria (particularly viridans streptococci — which express surface adhesins binding fibronectin and fibrin) adhere to the NBTE → bacterial multiplication protected from host defences within the vegetation. High-risk lesions: VSD, patent ductus arteriosus, bicuspid aortic valve, previous rheumatic valve disease, prosthetic valves, previous IE. Low-velocity lesions (large ASD, repaired VSD without residual jet): lower risk because turbulent jet is absent."
    },
    {
        "id": "t5-m344", "theme": 5, "topicTag": "heart-failure",
        "question": "Which ONE of the following correctly describes the pathophysiological role of the renin-angiotensin-aldosterone system (RAAS) in heart failure and why ACE inhibitors improve outcomes?",
        "options": ["A. In HF, RAAS is suppressed because increased cardiac output reduces renal perfusion pressure", "B. In HF, reduced cardiac output → reduced renal perfusion → renin release → angiotensin II → aldosterone → Na+/water retention (increased preload) and vasoconstriction (increased afterload) — initially compensatory but chronically deleterious; ACE inhibitors block angiotensin II formation reducing these harmful effects", "C. ACE inhibitors improve HF outcomes by blocking beta-1 receptors and reducing heart rate", "D. RAAS activation in HF causes hyponatraemia by stimulating excessive free water excretion", "E. ACE inhibitors improve HF by inhibiting aldosterone synthesis in the adrenal cortex directly"],
        "correctAnswer": "B",
        "explanation": "In heart failure, reduced cardiac output → reduced renal perfusion pressure → juxtaglomerular cells release renin → renin converts angiotensinogen to angiotensin I → ACE converts Ang I to Ang II → (1) Vasoconstriction (Ang II is a potent vasoconstrictor) → increased afterload → further reduces CO; (2) Aldosterone secretion → Na+ and water retention → increased preload → pulmonary congestion; (3) Sympathetic activation; (4) Cardiac and vascular remodelling (Ang II drives myocyte hypertrophy, fibrosis, and cardiomyocyte apoptosis). ACE inhibitors block Ang II production → vasodilation (reduces afterload), reduced aldosterone (reduces preload and fibrosis), and anti-remodelling effects → improved survival (CONSENSUS, SOLVD trials — 20–25% mortality reduction). Also accumulate bradykinin → ACE inhibitor cough."
    },
    {
        "id": "t5-m345", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly explains why adenosine is used to diagnose and treat supraventricular tachycardia (SVT) but is ineffective (and potentially dangerous) in ventricular tachycardia (VT)?",
        "options": ["A. Adenosine is effective for both SVT and VT — there is no contraindication to its use in VT", "B. Adenosine blocks A1 receptors in the AV node, transiently slowing or blocking conduction — terminates AV nodal re-entrant tachycardias (AVNRT) and AVRT that require AV nodal conduction; ineffective in VT (re-entrant circuit is in the ventricle — below the AV node) and can cause paradoxical acceleration of AF/flutter through accessory pathways", "C. Adenosine terminates VT by increasing ventricular refractory period but causes AV block in SVT", "D. Adenosine is used for VT with LBBB morphology but not RBBB morphology", "E. Adenosine is contraindicated in all tachycardias — it is only used as a diagnostic tool in ECG laboratories"],
        "correctAnswer": "B",
        "explanation": "Adenosine binds A1 receptors in the AV node → activates GIRK channels → hyperpolarisation → temporary AV node block (typically 10–15 seconds). SVT mechanism: (1) AVNRT — re-entrant circuit within the AV node — AV block terminates the circuit; (2) AVRT — re-entrant circuit using AV node and accessory pathway — AV block breaks the circuit. Both terminate with adenosine. VT: the re-entrant circuit is entirely within the ventricular myocardium — AV block has no effect on the ventricular circuit → adenosine does NOT terminate VT. If the rhythm is actually pre-excited AF with WPW (mimicking VT) and adenosine blocks the AV node → all impulses go through the accessory pathway → extremely rapid ventricular rate → VF. Therefore, adenosine must ONLY be used when the rhythm is confirmed or strongly suspected to be SVT."
    },
    {
        "id": "t5-m346", "theme": 5, "topicTag": "hypertension",
        "question": "A 52-year-old Afro-Caribbean man has BP 158/96 mmHg confirmed on ABPM. He has no diabetes and eGFR 75 mL/min. According to NICE, which ONE of the following is the MOST appropriate first-line antihypertensive?",
        "options": ["A. ACE inhibitor (ramipril) — first-line for all adults under 55 years regardless of ethnicity", "B. Calcium channel blocker (amlodipine) — first-line for all adults over 55 years or of Afro-Caribbean origin", "C. Thiazide-like diuretic (indapamide) — first-line specifically for Afro-Caribbean patients", "D. Beta-blocker (bisoprolol) — first-line for patients with high cardiovascular risk", "E. ARB (losartan) — preferred in Afro-Caribbean patients over ACE inhibitors to avoid ACE inhibitor cough"],
        "correctAnswer": "B",
        "explanation": "NICE step 1 antihypertensive selection: Under 55 years AND NOT Afro-Caribbean → ACE inhibitor or ARB (first-line). Over 55 years OR Afro-Caribbean of any age → CCB (amlodipine). Rationale: Afro-Caribbean patients have lower renin activity on average (RAAS-independent hypertension mechanism) → ACE inhibitors/ARBs are less effective as monotherapy. CCBs and thiazide-like diuretics work independently of renin levels. An Afro-Caribbean 52-year-old (any age) → CCB first-line. Note: if CCB is not tolerated or is contraindicated → thiazide-like diuretic (indapamide, chlorthalidone) as alternative first-line. ARBs are an alternative to ACE inhibitors (particularly if ACE inhibitor cough) but both are second-line in Afro-Caribbean patients."
    },
    {
        "id": "t5-m347", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following correctly identifies the MOST common site for atherosclerotic occlusive disease causing intermittent claudication?",
        "options": ["A. Aortoiliac segment (Leriche syndrome) — bilateral buttock/thigh claudication with impotence in men", "B. Superficial femoral artery (SFA) in the adductor canal — causing calf claudication; the most common site for PAD", "C. Popliteal artery — causing foot claudication", "D. Tibial arteries — causing digital ischaemia and calf claudication", "E. Common femoral artery — causing thigh claudication"],
        "correctAnswer": "B",
        "explanation": "The superficial femoral artery (SFA) as it passes through the adductor canal (Hunter's canal) is the MOST common site for atherosclerotic occlusion in peripheral arterial disease. It is a long, relatively fixed vessel passing through a fibromuscular tunnel where it is exposed to repetitive mechanical stress. Occlusion at this site → calf claudication (gastrocnemius muscle is supplied by the popliteal artery which becomes ischaemic with SFA occlusion). Leriche syndrome (aortoiliac occlusion): buttock/thigh claudication, absent femoral pulses, erectile dysfunction in men — a distinct but less common pattern. Tibial artery disease: most common in diabetics and causes rest pain/tissue loss rather than typical claudication."
    },
    {
        "id": "t5-m348", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly describes the mechanism by which spironolactone benefits patients with heart failure with reduced ejection fraction (HFrEF)?",
        "options": ["A. Spironolactone acts as a mineralocorticoid receptor antagonist (MRA) — blocks aldosterone's effects on the collecting duct (reduces Na+ retention, K+ loss) AND blocks aldosterone-mediated cardiac fibrosis and myocardial remodelling; reduces mortality by ~30% in HFrEF (RALES trial)", "B. Spironolactone is a loop diuretic that inhibits Na-K-2Cl co-transporter in the ascending limb of Henle", "C. Spironolactone blocks beta-1 adrenergic receptors, reducing sympathetic stimulation of the failing heart", "D. Spironolactone directly inhibits angiotensin-converting enzyme, reducing angiotensin II and aldosterone levels", "E. Spironolactone reduces preload by blocking vasopressin V2 receptors in the collecting duct"],
        "correctAnswer": "A",
        "explanation": "Spironolactone and eplerenone are mineralocorticoid receptor antagonists (MRAs). In HFrEF, RAAS activation → chronically elevated aldosterone → (1) Renal: sodium retention, potassium/magnesium wasting (hypokalaemia worsens arrhythmia risk); (2) Cardiac: aldosterone drives myocardial fibrosis and remodelling independent of Ang II. MRAs block both effects: renal effect reduces volume overload; cardiac effect reduces fibrosis and remodelling. RALES trial (spironolactone in NYHA III–IV HFrEF): 30% reduction in all-cause mortality. EPHESUS (eplerenone post-MI with HF): significant mortality reduction. Key side effects: hyperkalaemia (risk increased with ACE inhibitor co-prescription — monitor eGFR and K+), gynaecomastia (spironolactone — less with eplerenone — more selective MRA)."
    },
    {
        "id": "t5-m349", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the concept of 'cardiac output' and its determinants?",
        "options": ["A. Cardiac output = heart rate × stroke volume; stroke volume is determined by preload, afterload, and contractility", "B. Cardiac output = systolic BP × diastolic BP / heart rate", "C. Cardiac output = end-diastolic volume only; it is not affected by heart rate", "D. Cardiac output is fixed at 5 L/min and cannot be altered by physiological stimuli", "E. Cardiac output = stroke volume only; heart rate does not contribute to cardiac output"],
        "correctAnswer": "A",
        "explanation": "Cardiac output (CO) = Heart Rate (HR) × Stroke Volume (SV). Normal resting CO ≈ 5 L/min (HR 70 × SV 70mL). Stroke volume determinants: (1) Preload — end-diastolic ventricular volume/wall stress (Frank-Starling law: increased preload → increased stretch → increased contractile force up to a limit); (2) Afterload — resistance against which the ventricle ejects (systemic vascular resistance for LV; pulmonary vascular resistance for RV — increased afterload reduces SV); (3) Contractility — intrinsic myocardial force generation (positive inotropes increase contractility — catecholamines, digoxin; negative — beta-blockers, verapamil). Cardiac index = CO/BSA (normalises for body size; normal 2.5–4 L/min/m²). In heart failure: CO falls → compensatory HR increase and RAAS activation."
    },
    {
        "id": "t5-m350", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on warfarin has an INR of 8.5 but has no signs of bleeding. Which ONE of the following is the MOST appropriate management according to BCSH guidelines?",
        "options": ["A. Give IV vitamin K 10mg immediately and admit for observation", "B. Stop warfarin; give oral vitamin K 1–5mg; recheck INR in 24 hours; restart warfarin at a lower dose when INR is in range", "C. Continue warfarin at the same dose and recheck INR in 48 hours — labile INR is common", "D. Give fresh frozen plasma to immediately correct the INR before any vitamin K is administered", "E. Admit to hospital and give IV protamine sulphate to reverse warfarin rapidly"],
        "correctAnswer": "B",
        "explanation": "BCSH/BSH guidelines for elevated INR without bleeding: INR 5–8 with no bleeding: stop 1–2 doses of warfarin, restart at lower dose when INR <5. INR >8 with no bleeding: stop warfarin; give oral vitamin K 1–5mg (phytomenadione); recheck INR within 24 hours; restart warfarin when INR <5. IV vitamin K 10mg is reserved for serious/life-threatening haemorrhage (causes over-correction to INR <2 for several days, making re-anticoagulation difficult). Oral vitamin K 1–5mg reduces INR over 24–48 hours without over-correcting. FFP is only for active serious haemorrhage (volume and factor replacement). Protamine reverses heparin, not warfarin. The goal is to bring the INR safely back into range while minimising thromboembolism risk from over-reversal."
    },
    {
        "id": "t5-m351", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient with a drug-eluting coronary stent placed 4 months ago requires extraction of a non-restorable tooth. He is on aspirin 75mg + ticagrelor 90mg BD (dual antiplatelet therapy — DAPT). Which ONE of the following is the MOST appropriate approach to his antiplatelet therapy?",
        "options": ["A. Stop both aspirin and ticagrelor 5 days before extraction to minimise bleeding risk", "B. Stop ticagrelor only (the more potent antiplatelet) 5 days before; continue aspirin", "C. Continue BOTH aspirin and ticagrelor; do not discontinue either drug; perform extraction with local haemostatic measures", "D. Contact the prescribing cardiologist and suggest postponing the extraction until DAPT is complete (typically 12 months post-stent)", "E. Switch from ticagrelor to clopidogrel before the extraction as clopidogrel carries a lower bleeding risk"],
        "correctAnswer": "C",
        "explanation": "Drug-eluting stents (DES) require DAPT (typically 12 months) to prevent in-stent thrombosis — a catastrophic complication causing STEMI with mortality >25%. At 4 months, the stent endothelialisation is incomplete. Stopping EITHER antiplatelet drug significantly increases in-stent thrombosis risk. For dental extractions: continue BOTH antiplatelet drugs. The increased bleeding from DAPT is manageable with local haemostasis (sutures, packing, tranexamic acid mouthwash) — this is a far preferable risk to in-stent thrombosis. Option D is reasonable to consider (postponing elective extraction) but this is a non-restorable tooth that may cause infection/abscess if left — and the extraction risk with DAPT is manageable. Never stop or modify DAPT without cardiology agreement."
    },
    {
        "id": "t5-m352", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly identifies the ECG features of right bundle branch block (RBBB)?",
        "options": ["A. Broad QRS >120ms with broad, notched 'M-shaped' R-wave in V1 and deep wide S-wave in V6 (RSR' pattern in V1)", "B. Broad QRS >120ms with broad, notched 'W-shaped' R-wave in V6 and broad QS complex in V1", "C. Narrow QRS with ST elevation in V1–V3 and right axis deviation", "D. Broad QRS with absent R-wave in V1–V4 (poor R wave progression) and deep S-waves in V5–V6", "E. Broad QRS with delta wave at the start of the QRS and short PR interval"],
        "correctAnswer": "A",
        "explanation": "RBBB ECG pattern — 'WiLLiaM MoRRoW': Right Bundle Branch Block shows: (1) QRS >120ms (complete RBBB); (2) RSR' pattern ('M-shape' or 'bunny ears') in V1 — the second R' is from the delayed right ventricular depolarisation; (3) Broad slurred S-wave in leads I, aVL, V5–V6 — slow terminal depolarisation of the RV after LV has finished. Mnemonic: V1 looks like 'M' in RBBB. LBBB shows: broad QRS, broad 'M-shaped' R in V6 (and broad QS in V1) — the classic 'WiLLiaM' pattern. Delta wave + short PR = WPW (pre-excitation, not bundle branch block). RBBB new onset in context of STEMI may indicate anterior extension or right ventricular infarction."
    },
    {
        "id": "t5-m353", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly describes the haemodynamic consequences of severe aortic regurgitation (AR)?",
        "options": ["A. Severe AR causes elevated LVEDP and LV pressure overload similar to severe aortic stenosis", "B. Severe AR causes LV volume overload (regurgitant volume fills LV during diastole) → eccentric LV hypertrophy (dilation and hypertrophy) → increased LV stroke volume with low diastolic BP — wide pulse pressure", "C. Severe AR primarily affects the right ventricle, causing right heart failure and peripheral oedema", "D. Severe AR causes decreased LV end-diastolic volume because the regurgitant jet obstructs inflow through the mitral valve", "E. In severe AR, the pulse pressure is narrow because the regurgitant jet reduces LV systolic ejection"],
        "correctAnswer": "B",
        "explanation": "Aortic regurgitation: during diastole, blood flows back from the aorta into the LV through the incompetent aortic valve → LV receives both normal mitral inflow AND regurgitant volume → LV volume overload → eccentric hypertrophy (LV enlarges to accommodate the increased volume while maintaining wall stress — Laplace's law). LV ejects a large stroke volume → high systolic BP. During diastole, blood regurgitates back into the LV → aortic diastolic pressure falls → low diastolic BP. Net effect: WIDE PULSE PRESSURE (high systolic, low diastolic). Signs of wide pulse pressure in AR: Corrigan's pulse (water-hammer pulse), de Musset's sign (head bobbing), Traube's sign (pistol shots over femoral artery), Müller's sign (uvula pulsating). LV eventually dilates and fails → symptoms develop late."
    },
    {
        "id": "t5-m354", "theme": 5, "topicTag": "atherosclerosis",
        "question": "A 45-year-old man has a total cholesterol 8.1 mmol/L, LDL 6.2 mmol/L, HDL 1.3 mmol/L, and triglycerides 1.8 mmol/L. He has tendon xanthomata on both Achilles tendons. His father died of MI at age 42. Which ONE of the following is the MOST likely diagnosis?",
        "options": ["A. Secondary hypercholesterolaemia from hypothyroidism — always check TFTs before diagnosing genetic disorders", "B. Familial hypercholesterolaemia (FH) — autosomal dominant LDL receptor mutation causing severely elevated LDL from birth; tendon xanthomata and family history of premature CVD are pathognomonic features", "C. Polygenic hypercholesterolaemia — mild elevation from multiple common variants without tendon xanthomata", "D. Familial combined hyperlipidaemia — elevated cholesterol AND triglycerides with no tendon xanthomata", "E. Diet-induced hypercholesterolaemia — resolved by dietary modification alone without pharmacological treatment"],
        "correctAnswer": "B",
        "explanation": "Familial Hypercholesterolaemia (FH) diagnosis (Simon Broome criteria — definite FH): total cholesterol >7.5 mmol/L (or LDL >4.9 mmol/L in adults) PLUS tendon xanthomata (pathognomonic — cholesterol deposits in tendons) OR first/second degree relative with documented coronary artery disease under 60 years or elevated cholesterol. FH is caused by mutations in: LDL receptor (most common — 85%), ApoB (prevents LDL binding to LDLR), PCSK9 (gain-of-function — promotes LDLR degradation). LDL is elevated from birth → atherosclerosis starts in childhood → premature CVD without treatment. Treatment: high-intensity statins; ezetimibe added if target not reached; PCSK9 inhibitors for refractory/homozygous FH. Cascade screening of first-degree relatives is essential."
    },
    {
        "id": "t5-m355", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient on amiodarone long-term develops a dry cough and progressive breathlessness on exertion. Chest X-ray shows bilateral infiltrates. Which ONE of the following is the MOST likely complication?",
        "options": ["A. ACE inhibitor-induced cough — amiodarone is metabolised to an ACE inhibitor-like compound", "B. Amiodarone pulmonary toxicity — interstitial pneumonitis/pulmonary fibrosis from amiodarone accumulation in the lungs; incidence 2–17%; potentially fatal if not recognised", "C. Cardiac tamponade — amiodarone causes pericardial effusion presenting with breathlessness and bilateral infiltrates", "D. Amiodarone-induced atrial fibrillation — increased sympathetic tone causes dyspnoea and bilateral infiltrates", "E. Pulmonary embolism — amiodarone increases blood viscosity and causes thromboembolism"],
        "correctAnswer": "B",
        "explanation": "Amiodarone pulmonary toxicity: amiodarone and its metabolite desethylamiodarone accumulate in the lung parenchyma (high lipophilicity) → direct toxic damage to type II pneumocytes AND indirect immune-mediated inflammation. Presentations: subacute interstitial pneumonitis (most common), organising pneumonia, acute respiratory distress. CXR/CT: bilateral alveolar/interstitial infiltrates, often asymmetric. Incidence: 2–17% of long-term users. Risk factors: high dose, long duration, pre-existing lung disease. Diagnosis: clinical picture + imaging + exclusion of infection and HF. Management: STOP amiodarone; high-dose oral prednisolone (0.5mg/kg) for months to years. Recovery can occur but may take months; some progress to fibrosis. Other amiodarone toxicities: thyroid (hypo/hyperthyroidism), hepatic, corneal microdeposits, photosensitivity, peripheral neuropathy."
    },
    {
        "id": "t5-m356", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "Which ONE of the following correctly describes the ABCD2 score used after TIA and identifies the score threshold requiring urgent same-day specialist assessment?",
        "options": ["A. ABCD2 score assesses: Age, BP, Clinical features, Duration of symptoms, Diabetes — score ≥4 should be seen by a TIA specialist within 24 hours; score ≥6 within 1 hour", "B. ABCD2 score assesses: Age (≥60 = 1 point), Blood pressure at presentation (≥140/90 = 1 point), Clinical features (unilateral weakness = 2, speech without weakness = 1, other = 0), Duration (≥60 min = 2, 10–59 min = 1), Diabetes (1 point). NICE recommends specialist TIA review within 24 hours for all cases; urgent MRI/imaging", "C. ABCD2 score is used only to determine the need for anticoagulation in TIA, not for urgency of assessment", "D. ABCD2 score is no longer recommended — all TIAs are treated as equal urgency", "E. ABCD2 score maximum is 5 points; any score >2 requires hospital admission for 7 days of monitoring"],
        "correctAnswer": "B",
        "explanation": "ABCD2 score (max 7 points): Age ≥60y = 1; Blood pressure ≥140/90 = 1; Clinical features: unilateral weakness = 2, speech disturbance without weakness = 1; Duration: ≥60min = 2, 10–59min = 1; Diabetes = 1. Originally used to risk-stratify TIA (score ≥4 = high risk, 5–7 = very high 2-day stroke risk ~8%). However, current NICE NG128 (2019) guidance recommends: offer specialist assessment (TIA clinic or stroke unit) within 24 hours of symptom onset for ALL TIAs, regardless of ABCD2 score (because even low scores have meaningful stroke risk). The ABCD2 score is still useful for communicating risk but no longer gates access to urgent review. MRI DWI, carotid imaging, ECG, and blood tests should accompany urgent specialist assessment."
    },
    {
        "id": "t5-m357", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes 'heparin-induced thrombocytopenia type II' (HIT) and the MOST important management step?",
        "options": ["A. HIT type II is a mild allergy to heparin causing transient platelet reduction; managed by reducing the heparin dose", "B. HIT type II is an immune-mediated prothrombotic disorder: antibodies against heparin-PF4 complexes activate platelets → paradoxical THROMBOSIS despite low platelet count; management = STOP all heparin immediately and anticoagulate with a non-heparin agent (argatroban or fondaparinux)", "C. HIT type II is treated by platelet transfusion to restore platelet count before heparin discontinuation", "D. HIT type II resolves spontaneously without treatment as long as heparin is continued at a reduced dose", "E. HIT type II only occurs with unfractionated heparin; LMWH is completely safe and can be substituted"],
        "correctAnswer": "B",
        "explanation": "Heparin-Induced Thrombocytopenia type II (HIT): immune-mediated reaction — IgG antibodies form against heparin/platelet factor 4 (PF4) complexes → antibody-PF4-heparin complex binds FcγRIIA receptors on platelets → massive platelet activation → thrombosis (venous and arterial), paradoxically despite thrombocytopenia. Features: platelet count falls 30–50% from baseline, 5–10 days after heparin start (or sooner in previously sensitised patients); new thrombosis despite anticoagulation. 4Ts score (Thrombocytopenia, Timing, Thrombosis, other causes oT) quantifies probability. Management: STOP ALL HEPARIN (UFH AND LMWH — cross-reactive antibodies); START non-heparin anticoagulant (argatroban — IV direct thrombin inhibitor; or fondaparinux — anti-Xa; danaparoid); NEVER give platelets (feeds the thrombotic storm). Do NOT use warfarin acutely (causes venous limb gangrene by depleting protein C first)."
    },
    {
        "id": "t5-m358", "theme": 5, "topicTag": "cvd-overview",
        "question": "A 60-year-old man undergoes a coronary angiogram which shows a 'coronary artery fistula' between the left anterior descending (LAD) artery and the right ventricle. Which ONE of the following BEST describes the haemodynamic consequence of this finding?",
        "options": ["A. The fistula creates a left-to-right shunt — blood passes from high-pressure LAD (aortic pressure) directly into the low-pressure right ventricle, creating a volume load on the right heart and reducing coronary perfusion distal to the fistula", "B. The fistula creates a right-to-left shunt causing central cyanosis", "C. The fistula increases coronary perfusion to the myocardium supplied by the LAD", "D. The fistula has no haemodynamic consequences and is always an incidental finding requiring no treatment", "E. The fistula creates an afterload reduction on the left ventricle, improving overall cardiac function"],
        "correctAnswer": "A",
        "explanation": "Coronary artery fistula: an abnormal connection between a coronary artery (high-pressure arterial system) and a cardiac chamber or great vessel (typically low-pressure structure — right heart, pulmonary artery). The LAD-RV fistula creates: (1) Left-to-right shunt (high pressure → low pressure) → volume load on RV and pulmonary circulation → right heart dilation → eventual right heart failure if large; (2) Coronary steal — blood is preferentially diverted from the LAD into the fistula rather than perfusing the myocardium → myocardial ischaemia distal to the fistula; (3) Continuous murmur (similar to PDA). Small fistulae: often incidental, observe. Large fistulae (significant shunt, symptoms, ventricular dilation): percutaneous coil embolisation or surgical closure."
    },
    {
        "id": "t5-m359", "theme": 5, "topicTag": "heart-failure",
        "question": "A 68-year-old woman with HFrEF (EF 32%) on optimal medical therapy (ACE inhibitor, beta-blocker, MRA) develops worsening breathlessness. Her ECG shows sinus rhythm with LBBB and QRS duration 156ms. Which ONE of the following additional therapy should be considered?",
        "options": ["A. Add digoxin — the first-line treatment for worsening HF in patients already on triple therapy", "B. Cardiac resynchronisation therapy (CRT) — improves cardiac synchrony in patients with LBBB and QRS >130ms; improves symptoms, EF, and survival (CARE-HF, COMPANION trials)", "C. Add loop diuretic — furosemide as the next step for worsening breathlessness in HFrEF", "D. Arrange urgent heart transplant listing — there are no other medical or device options for worsening HFrEF", "E. Add ivabradine — rate reduction is the priority in LBBB HF regardless of heart rate"],
        "correctAnswer": "B",
        "explanation": "Cardiac resynchronisation therapy (CRT) indications: HFrEF (EF ≤35%) + NYHA class II–IV despite optimal medical therapy + QRS ≥130ms (especially LBBB morphology — most benefit with LBBB ≥150ms). LBBB causes dyssynchronous ventricular contraction (RV activates before LV) → wasted contraction, reduced efficiency, worsened EF. CRT biventricular pacemaker delivers simultaneous RV and LV pacing → resynchronises ventricular contraction → improved stroke volume, reduced mitral regurgitation, reverse remodelling of LV. CARE-HF trial: CRT reduced all-cause mortality by 36% in eligible HFrEF patients. If ICD indication also present (EF ≤35%): CRT-D device provides both functions. Adding loop diuretics treats congestion symptoms but does not improve survival. Digoxin has modest symptom benefit only."
    },
    {
        "id": "t5-m360", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A dentist prescribes ibuprofen 400mg three times daily for post-extraction pain to a patient on lisinopril and furosemide for hypertension and heart failure. Which ONE of the following is the MOST clinically important interaction to be aware of?",
        "options": ["A. Ibuprofen reduces the absorption of lisinopril from the gastrointestinal tract", "B. The combination of NSAID + ACE inhibitor + loop diuretic ('triple whammy') significantly increases the risk of acute kidney injury by reducing renal prostaglandin synthesis and glomerular filtration — avoid this combination", "C. Ibuprofen raises serum potassium when combined with lisinopril, causing fatal hyperkalaemia within one dose", "D. Furosemide inhibits ibuprofen metabolism, causing toxic ibuprofen levels after a single dose", "E. Ibuprofen is always safe to prescribe alongside antihypertensives as its systemic dose from dental use is too small to cause interactions"],
        "correctAnswer": "B",
        "explanation": "'Triple whammy' nephrotoxicity: ACE inhibitor (or ARB) + loop diuretic + NSAID = high risk of acute kidney injury. Mechanism: renal prostaglandins maintain afferent arteriolar vasodilation (counteracting Ang II-mediated efferent constriction) to preserve GFR — especially when effective circulating volume is reduced (as in heart failure or diuretic-induced volume depletion). NSAIDs inhibit COX → reduced prostaglandins → afferent vasoconstriction → dramatically reduced GFR → AKI. This triple combination is implicated in a significant proportion of drug-induced AKI hospitalised patients. In dental practice: avoid NSAIDs in patients on ACE inhibitors + diuretics; use paracetamol ± codeine for analgesia instead. Additionally: NSAIDs reduce the antihypertensive effect of ACE inhibitors and cause sodium/fluid retention (worsening heart failure)."
    },
    {
        "id": "t5-m361", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 25-year-old competitive cyclist presents for a sports medical examination. His resting ECG shows: sinus bradycardia (HR 42 bpm), PR interval 220ms, QRS 110ms (incomplete RBBB), and early repolarisation pattern in V1–V4. He is entirely asymptomatic. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Refer urgently to electrophysiology — these ECG findings represent high risk of sudden cardiac death in athletes", "B. These are normal physiological ECG adaptations to endurance training ('athlete's heart') — no further investigation required; return to sport with normal advice", "C. Arrange a 24-hour Holter monitor and stop all competitive sport pending results", "D. These findings are diagnostic of hypertrophic cardiomyopathy — stop all competitive sport immediately", "E. These findings indicate complete heart block — arrange urgent permanent pacemaker implantation"],
        "correctAnswer": "B",
        "explanation": "Athlete's ECG changes: endurance athletes develop: (1) Sinus bradycardia (increased vagal tone, reduced resting HR); (2) First-degree AV block (PR 200–220ms — from increased vagal tone slowing AV node conduction); (3) Incomplete RBBB (QRS 100–120ms — mild RV conduction delay from training-related RV adaptation); (4) Early repolarisation (ST elevation in precordial leads — normal variant particularly in athletes). All of these are NORMAL physiological training adaptations — they are benign and not associated with increased risk. They MUST be distinguished from pathological ECG changes requiring investigation: deep T-wave inversions in >2 leads (excluding RBBB), ST depression, pathological Q-waves, LBBB, long QT, short QT, Brugada pattern, WPW. The 2017 International Consensus on Athlete ECG Interpretation (Drezner criteria) provides detailed guidance."
    },
    {
        "id": "t5-m362", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly explains why prosthetic mechanical heart valves require higher INR targets than other anticoagulation indications?",
        "options": ["A. Mechanical valves are made of thrombogenic materials that require complete anticoagulation to prevent valve dysfunction from clot formation within the valve mechanism; mitral valves require INR 3–4, aortic valves INR 2.5–3.5 due to higher thrombosis risk", "B. The higher INR target reflects the legal requirement for anticoagulation in all prosthetic device patients", "C. All mechanical valves require the same INR of 3.0 regardless of position", "D. Mechanical valves require anticoagulation only in the first 3 months after implantation; thereafter they are fully endothelialised and anticoagulation is no longer needed", "E. Higher INR targets are used to prevent paravalvular leak rather than thromboembolism"],
        "correctAnswer": "A",
        "explanation": "Prosthetic mechanical heart valves are made of non-biological materials (pyrolytic carbon) that are intrinsically thrombogenic — fibrin and platelet deposition on valve surfaces can cause: (1) Valve thrombosis — clot on the valve occluder impairs leaflet movement → acute haemodynamic compromise; (2) Systemic embolism — clot fragments embolise causing stroke or peripheral embolism. INR targets vary by valve position and type: Aortic position mechanical valve (lower thrombosis risk than mitral — faster flow): target INR 2.5–3.5 (or 2.0–3.0 for low-risk modern bileaflet valves). Mitral position mechanical valve (higher risk — slower flow, larger valve area, more turbulence): target INR 3–4. Older valves (ball-and-cage — Starr-Edwards): higher targets. Bioprosthetic valves: anticoagulation only for 3 months post-implant, then switch to aspirin (fully endothelialised and less thrombogenic)."
    },
    {
        "id": "t5-m363", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "A 55-year-old man presents with sudden-onset severe left leg pain, pallor, pulselessness, paraesthesia, and paralysis. His femoral pulse is present but popliteal and foot pulses are absent. Which ONE of the following is the MOST likely diagnosis and appropriate management pathway?",
        "options": ["A. Deep vein thrombosis — treat with LMWH and arrange duplex ultrasound", "B. Acute limb ischaemia from embolic or thrombotic arterial occlusion — a surgical emergency; immediate vascular surgery referral, IV heparin anticoagulation, urgent revascularisation (embolectomy/thrombolysis/bypass) within 6 hours to salvage the limb", "C. Compartment syndrome — perform immediate fasciotomy in the emergency department", "D. Critical limb ischaemia — arrange elective angiogram and plan revascularisation over the next 2 weeks", "E. Leriche syndrome — bilateral symptoms are expected; unilateral presentation suggests DVT"],
        "correctAnswer": "B",
        "explanation": "Acute Limb Ischaemia (ALI): the '6 P's' — Pain, Pallor, Pulselessness, Paraesthesia, Paralysis, Perishing cold. This is a limb-threatening emergency. Causes: (1) Embolism (most common in AF — thrombus from LA embolises to peripheral artery — typically sudden and complete); (2) Acute thrombosis (on background of PAD — the limb already has some collateral flow, so presentation may be less dramatic). Management: immediate IV heparin (prevent propagation); urgent vascular surgery review; revascularisation within 6 hours (Rutherford classification: immediately threatened limb — marginally viable limb with sensory/motor loss requires immediate surgery): embolectomy under LA (Fogarty catheter), thrombolysis (catheter-directed), or bypass. Beyond 6 hours: irreversible muscle necrosis → amputation may be inevitable. Paralysis/paraesthesia indicate near-irreversible ischaemia — extreme urgency."
    },
    {
        "id": "t5-m364", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient on amlodipine 5mg for hypertension is prescribed clarithromycin for a chest infection by their GP. Which ONE of the following interaction is MOST clinically significant?",
        "options": ["A. Clarithromycin inhibits P-glycoprotein, reducing amlodipine absorption and lowering blood pressure control", "B. Clarithromycin is a potent CYP3A4 inhibitor — inhibits amlodipine metabolism → significantly increased plasma amlodipine levels → risk of severe hypotension and peripheral oedema; consider dose reduction or temporary amlodipine dose adjustment", "C. Clarithromycin directly blocks calcium channels, causing additive hypotension with amlodipine", "D. Amlodipine inhibits clarithromycin absorption, reducing antibiotic efficacy", "E. There is no clinically relevant interaction between clarithromycin and amlodipine"],
        "correctAnswer": "B",
        "explanation": "Amlodipine is primarily metabolised by CYP3A4. Clarithromycin is a potent CYP3A4 inhibitor (ERYTHROMYCIN is moderate; AZITHROMYCIN has minimal CYP3A4 inhibition). Inhibiting CYP3A4 → reduced amlodipine metabolism → significantly higher plasma amlodipine levels → enhanced vasodilation → hypotension (can be severe) + worsening peripheral oedema. The interaction is particularly significant in elderly or volume-depleted patients. Clinical management: if clarithromycin is essential, consider temporarily reducing amlodipine dose or monitoring BP closely. Azithromycin is a safer macrolide alternative if appropriate for the infection. Note: clarithromycin also inhibits CYP3A4 metabolism of many other CVD drugs (statins — risk of myopathy; digoxin — via P-gp inhibition; warfarin — raises INR via CYP2C9)."
    },
    {
        "id": "t5-m365", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 65-year-old man with stable angina complains that his angina is now occurring at rest. His ECG shows new T-wave inversions in leads V1–V4. His troponin is negative at 0 hours and 3 hours. Which ONE of the following is the MOST appropriate diagnosis?",
        "options": ["A. NSTEMI — troponin will eventually become positive after 24 hours; treat as NSTEMI", "B. Unstable angina (UA) — ACS with symptoms at rest and ECG changes but negative troponin; represents severe coronary instability requiring urgent assessment and medical treatment", "C. Stable angina — rest symptoms with ECG changes are within the normal variation of stable angina", "D. Musculoskeletal pain — negative troponin rules out any cardiac pathology", "E. Pericarditis — T-wave inversions are the hallmark of pericarditis in leads V1–V4"],
        "correctAnswer": "B",
        "explanation": "Unstable angina (UA): part of the ACS spectrum, distinguished from NSTEMI by NEGATIVE serial troponins. Features: angina at rest (or minimal exertion or increasing frequency/severity) with ECG changes (ST depression, T-wave inversion) but no myocardial necrosis markers. Negative troponin at 0h and 3h (using high-sensitivity troponin) effectively rules out NSTEMI. However, UA is NOT benign — the underlying mechanism (plaque rupture/erosion with dynamic thrombus) poses ongoing MI and cardiac death risk. Management: aspirin + P2Y12 inhibitor (ticagrelor), anticoagulation (fondaparinux preferred), beta-blocker, statin, and coronary angiography within 72 hours (earlier if high-risk features). The distinction between UA and NSTEMI guides prognosis but management is largely the same."
    },
    {
        "id": "t5-m366", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly identifies the dental management threshold for INR in patients requiring simple dental extractions?",
        "options": ["A. INR must be below 2.0 for any dental extraction to be performed safely", "B. INR up to 4.0 is acceptable for simple dental extractions with appropriate local haemostasis; the evidence shows that continuing warfarin at therapeutic levels is safer than stopping (which risks thromboembolism)", "C. INR must be below 1.5 — equivalent to normal coagulation — for any invasive dental procedure", "D. INR above 2.5 requires hospital admission for all dental extractions", "E. Any INR within the therapeutic range (2–3 or 2.5–3.5) automatically requires LMWH bridging before dental extractions"],
        "correctAnswer": "B",
        "explanation": "The British Dental Association/SDCEP/Haemostasis & Thrombosis Task Force guidelines on warfarin in dentistry: for SIMPLE dental extractions, warfarin should be CONTINUED. The INR threshold for proceeding is ≤4.0 — at this level the risk of uncontrolled haemorrhage is low when effective local haemostasis is used (socket suturing, haemostatic packing, tranexamic acid mouthwash 10mL QDS for 2 days). If INR >4.0: postpone procedure and contact anticoagulant clinic. If INR is within therapeutic range (2–3 or 2.5–3.5): proceed with local haemostasis measures. The evidence from multiple RCTs shows that stopping warfarin increases thromboembolism risk (stroke, MI) without meaningfully reducing post-extraction bleeding when appropriate local measures are used. Check INR within 24–72 hours before the procedure."
    },
    {
        "id": "t5-m367", "theme": 5, "topicTag": "hypertension",
        "question": "A 58-year-old woman has confirmed hypertension (ABPM daytime average 148/94 mmHg) and is already taking amlodipine 10mg. Her BP is still above target. Which ONE of the following is the MOST appropriate next step according to NICE step 2?",
        "options": ["A. Double the amlodipine dose to 20mg as the maximum dose has not been reached", "B. Add an ACE inhibitor (e.g. ramipril) or ARB — step 2 NICE hypertension: CCB + ACE inhibitor/ARB combination", "C. Switch amlodipine to a beta-blocker — beta-blockers are step 2 drugs when CCBs fail", "D. Add spironolactone — the next step for all patients inadequately controlled on one drug", "E. Refer to cardiology for consideration of renal denervation as all pharmacological options have been tried"],
        "correctAnswer": "B",
        "explanation": "NICE hypertension management ladder: Step 1 (under 55, non-Afro-Caribbean): ACE inhibitor or ARB. Step 1 (over 55 or Afro-Caribbean): CCB. Step 2: CCB + ACE inhibitor/ARB (combination of the two step-1 drug classes). Step 3: CCB + ACE inhibitor/ARB + thiazide-like diuretic (triple combination). Step 4 (resistant hypertension — BP above target on 3 drugs): if K+ ≤4.5: add spironolactone 25mg; if K+ >4.5: add alpha-blocker (doxazosin) or beta-blocker. This patient is at step 1 (CCB 10mg maximum dose) and needs step 2 — add ACE inhibitor (ramipril) or ARB (losartan). Amlodipine maximum dose is 10mg — cannot increase further. Beta-blockers are step 4 alternatives, not step 2 progression."
    },
    {
        "id": "t5-m368", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "Blood cultures from a patient with suspected IE grow Staphylococcus aureus. Which ONE of the following correctly describes the clinical significance of this finding compared to viridans streptococcal IE?",
        "options": ["A. Staphylococcal IE is less destructive than streptococcal IE and can usually be managed without surgery", "B. Staphylococcus aureus IE is more virulent than viridans streptococcal IE — causes rapid valve destruction, higher rate of emboli, perivalvular abscess formation, and significantly higher mortality (20–40%); often requires earlier surgical intervention", "C. Staphylococcal IE predominantly affects the left side of the heart in IV drug users", "D. Viridans streptococcal IE has higher mortality than staphylococcal IE because streptococci form larger vegetations", "E. Staphylococcal IE is exclusively a community-acquired infection and never occurs in hospital patients"],
        "correctAnswer": "B",
        "explanation": "Staphylococcus aureus IE vs Viridans streptococcal IE: S. aureus (aggressive virulence): produces multiple exotoxins and enzymes that destroy valve tissue; causes rapid valve perforation, chordal rupture, and perivalvular abscess (requiring surgery); high vegetation burden → frequent emboli (>50% neurological events); acute presentation over days; mortality 20–40%. Viridans streptococci (subacute): slow growing, less destructive; typically affects previously abnormal valves; lower virulence → slower valve destruction; responds better to antibiotics alone; mortality 5–10%. S. aureus from IV drug use: classically right-sided (tricuspid valve) — less destructive than left-sided; better prognosis. Hospital-acquired S. aureus IE: from IV lines, procedures — left-sided; high mortality. Any S. aureus bacteraemia should be treated as presumptive IE until excluded."
    },
    {
        "id": "t5-m369", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the Frank-Starling mechanism and its clinical relevance in heart failure?",
        "options": ["A. The Frank-Starling mechanism states that as afterload increases, stroke volume increases proportionally — this explains why hypertension improves cardiac output", "B. The Frank-Starling mechanism: within physiological limits, increased end-diastolic volume (preload) → increased sarcomere stretch → more optimal actin-myosin overlap → greater force of contraction → increased stroke volume; in HF, the curve is flattened and shifted right — higher filling pressures needed for the same cardiac output", "C. Frank-Starling mechanism applies only to the right ventricle — the left ventricle has independent contractile regulation", "D. The Frank-Starling mechanism describes how the heart rate increases automatically when venous return increases", "E. The Frank-Starling mechanism is absent in heart failure patients — their hearts cannot respond to changes in preload"],
        "correctAnswer": "B",
        "explanation": "Frank-Starling Law of the Heart: increased preload (venous return → end-diastolic volume) → increased sarcomere stretch (up to optimal length ~2.2 µm) → greater cross-bridge formation between actin and myosin → increased contractile force → increased stroke volume. This mechanism allows the heart to match output to venous return (right and left ventricles stay balanced). Clinical relevance in HF: in the failing heart, the Frank-Starling curve is depressed (same preload produces less stroke volume) and flattened. To maintain cardiac output, the heart operates at higher filling pressures (LVEDP rises) → pulmonary venous congestion → pulmonary oedema. Diuretics and vasodilators (preload reduction) move the patient to a more comfortable portion of the depressed curve. Inotropes shift the curve up."
    },
    {
        "id": "t5-m370", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 70-year-old woman with known AF is brought to the emergency department with a HR of 165 bpm and BP 72/50 mmHg. She is sweating and confused. Which ONE of the following is the MOST appropriate immediate management?",
        "options": ["A. Administer IV amiodarone 300mg over 1 hour as rate control is the priority", "B. Administer IV diltiazem — most rapid rate control agent for haemodynamically unstable AF", "C. Immediate synchronised DC cardioversion under sedation — haemodynamic compromise from AF requires immediate rhythm restoration", "D. Start IV digoxin — loading dose for rapid ventricular rate control in AF with hypotension", "E. Oral beta-blocker stat — bisoprolol 5mg immediately for rapid rate control"],
        "correctAnswer": "C",
        "explanation": "Haemodynamically unstable AF (HR 165, BP 72/50, confusion = end-organ hypoperfusion): this is the absolute indication for IMMEDIATE synchronised DC cardioversion. The rapid ventricular response is causing haemodynamic compromise — the heart cannot fill and eject effectively at 165 bpm. Drug rate control would be dangerously slow and many rate-control drugs (diltiazem, verapamil, amiodarone) cause further hypotension. Synchronised cardioversion: apply to QRS complex (not T-wave) — initial energy 100–200J (biphasic); requires sedation/anaesthesia if patient conscious; succeeds in restoring sinus rhythm in majority. Note: anticoagulation status must be considered (if AF >48h without anticoagulation — TOE to exclude LA thrombus, or anticoagulate and cardiovert anyway in emergency). Never delay DC cardioversion in haemodynamically unstable arrhythmias for anticoagulation concerns."
    },
    {
        "id": "t5-m371", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "Which ONE of the following correctly describes a 'lacunar infarct' and the cerebral artery territory typically affected?",
        "options": ["A. A lacunar infarct is a large cortical infarct from middle cerebral artery occlusion causing dense hemiplegia and aphasia", "B. A lacunar infarct is a small deep infarct (<15mm) caused by occlusion of a perforating small vessel supplying the internal capsule, basal ganglia, thalamus, or pons — from lipohyalinosis (typically hypertension-related) or microatheroma; presents with pure motor or pure sensory stroke syndromes", "C. A lacunar infarct affects the cerebellum and causes isolated ataxia from vertebral artery thrombosis", "D. A lacunar infarct is caused exclusively by cardioembolism from AF", "E. A lacunar infarct is distinguished from TIA solely by the duration of symptoms (>24 hours)"],
        "correctAnswer": "B",
        "explanation": "Lacunar infarcts: small deep brain infarcts (<15mm on MRI) from occlusion of penetrating arteries (lenticulostriate arteries, thalamoperforating arteries, pontine perforators) supplying deep structures. Mechanism: lipohyalinosis (chronic hypertension causing fibrinoid degeneration of small vessel walls — not atherosclerosis). Presentations (classic lacunar syndromes): (1) Pure motor hemiparesis — posterior limb of internal capsule; (2) Pure sensory stroke — thalamus; (3) Ataxic hemiparesis — posterior limb IC or pons; (4) Dysarthria-clumsy hand syndrome — genu IC or pons. Distinguished from cortical strokes: no cortical features (no aphasia, no visual field defect, no cortical sensory loss, no neglect). CT often negative acutely; MRI DWI detects lacunar infarcts. The main risk factor is hypertension — aggressive BP control reduces risk."
    },
    {
        "id": "t5-m372", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 75-year-old man is on atorvastatin 80mg for secondary prevention of CVD. He is newly prescribed clarithromycin by his GP. Which ONE of the following serious adverse effect is MOST important to monitor for during the antibiotic course?",
        "options": ["A. Rhabdomyolysis — clarithromycin inhibits CYP3A4, dramatically increasing plasma atorvastatin levels — risk of severe myopathy/rhabdomyolysis", "B. Hepatitis — clarithromycin and atorvastatin are both hepatotoxic and the combination always causes liver failure", "C. Peripheral neuropathy — the combination causes cumulative neurotoxic damage", "D. Atorvastatin is not metabolised by CYP3A4 — clarithromycin has no interaction", "E. QT prolongation — atorvastatin prolongs the QT interval when plasma levels are increased by clarithromycin"],
        "correctAnswer": "A",
        "explanation": "Statin-antibiotic interaction: atorvastatin (like simvastatin and lovastatin) is metabolised by CYP3A4. Clarithromycin (and erythromycin) are potent CYP3A4 inhibitors → reduced atorvastatin metabolism → 3–10 fold increase in plasma statin levels → dramatically increased risk of myopathy and rhabdomyolysis (potentially fatal — myoglobinuria → AKI). At high doses (80mg atorvastatin), the baseline risk is already elevated. Management: if clarithromycin is essential, consider temporarily STOPPING the statin for the duration of the antibiotic course (typically 7–14 days); alternatively, use azithromycin (minimal CYP3A4 interaction) if clinically appropriate. Pravastatin and rosuvastatin are NOT metabolised by CYP3A4 — safer alternatives in patients requiring macrolides."
    },
    {
        "id": "t5-m373", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following correctly describes the 'ankle-brachial pressure index' (ABPI) and the threshold for diagnosing significant PAD?",
        "options": ["A. ABPI = brachial systolic BP / ankle systolic BP; ABPI <0.9 indicates significant PAD", "B. ABPI = ankle systolic BP / brachial systolic BP; normal ≥0.9; ABPI 0.5–0.9 indicates claudication severity PAD; ABPI <0.5 indicates critical limb ischaemia", "C. ABPI = ankle diastolic BP / brachial diastolic BP; ABPI <0.5 indicates claudication", "D. ABPI is measured only after treadmill exercise and is not valid at rest", "E. ABPI >1.3 always indicates arterial disease from calcification — treat identically to low ABPI"],
        "correctAnswer": "B",
        "explanation": "Ankle-Brachial Pressure Index (ABPI): measured using Doppler probe to detect ankle systolic BP (posterior tibial or dorsalis pedis — highest of the two) and brachial systolic BP. ABPI = ankle systolic BP / brachial systolic BP. Interpretation: >1.0 (some say ≥0.9): normal; 0.7–0.9: mild PAD (often asymptomatic); 0.5–0.7: moderate PAD (claudication); <0.5: severe PAD (critical limb ischaemia — rest pain or tissue loss); >1.3: incompressible calcified arteries (diabetics, chronic renal disease — falsely elevated — ABPI unreliable in this range; use toe-brachial index instead). Clinical use: diagnosis of PAD, severity assessment, pre-revascularisation planning, monitoring. Post-exercise ABPI drops significantly in claudicants but remains normal in non-vascular causes of leg pain (spinal stenosis, compartment syndrome)."
    },
    {
        "id": "t5-m374", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A 69-year-old man with moderate heart failure (NYHA class II) attends for routine dental treatment. He reports no current symptoms. Which ONE of the following is the MOST important consideration when planning his care?",
        "options": ["A. Refer to hospital for all dental treatment as patients with heart failure should never be treated in primary care", "B. Avoid local anaesthesia entirely as adrenaline is absolutely contraindicated in all heart failure patients", "C. Assess current symptom status, recent hospital admissions, medications, and BP; treat electively in a stable, well-controlled patient; use semi-reclined position (not fully supine); limit adrenaline to 2 cartridges of 1:100,000; avoid NSAIDs; minimise stress", "D. Carry out all dental treatment rapidly in a single extended appointment to minimise repeated attendance stress", "E. Prescribe prophylactic antibiotics before all dental procedures to prevent infective endocarditis"],
        "correctAnswer": "C",
        "explanation": "Heart failure patients in dental practice: (1) Assess fitness — NYHA class, recent decompensation, current medications, BP, SpO2; NYHA I–II stable: can be treated in primary care. NYHA III–IV or recent hospitalisation: defer non-urgent treatment, consider hospital dental department; (2) Position: semi-reclined (30–45°) — fully supine worsens pulmonary congestion (orthopnoea) and may precipitate acute LVF; (3) Adrenaline: 2 cartridges of 1:100,000 adrenaline (180 micrograms) is acceptable — avoid excessive doses; intravascular injection is a significant risk — always aspirate; (4) Avoid NSAIDs — worsen sodium/water retention and renal function; (5) Minimise stress/anxiety — can precipitate acute decompensation; consider anxiolytics (short-acting benzodiazepine); (6) No routine IE prophylaxis unless specified high-risk cardiac condition (NICE guideline)."
    },
    {
        "id": "t5-m375", "theme": 5, "topicTag": "cvd-overview",
        "question": "A 67-year-old man with a long history of atrial fibrillation has a CHA2DS2-VASc score of 5. His HAS-BLED score is 2. Which ONE of the following correctly guides his anticoagulation decision?",
        "options": ["A. HAS-BLED score 2 is high — anticoagulation should be withheld to avoid bleeding", "B. CHA2DS2-VASc 5 confers very high stroke risk (approximately 9% annual stroke risk); HAS-BLED 2 is low-moderate bleeding risk; net clinical benefit of anticoagulation far outweighs bleeding risk — anticoagulate with DOAC or warfarin", "C. CHA2DS2-VASc and HAS-BLED scores balance each other — a score of 5 and 2 respectively means no treatment is required", "D. Anticoagulation is only indicated if CHA2DS2-VASc ≥6 — a score of 5 is below the treatment threshold", "E. Aspirin 75mg is preferred over anticoagulation when HAS-BLED >1 to reduce bleeding risk"],
        "correctAnswer": "B",
        "explanation": "CHA2DS2-VASc scoring: Congestive HF (1), Hypertension (1), Age ≥75 (2), Diabetes (1), Stroke/TIA history (2), Vascular disease (1), Age 65–74 (1), Sex category female (1). Score 5 ≈ 9.7% annual stroke risk without anticoagulation. HAS-BLED score ≤2 = low-moderate bleeding risk. The net clinical benefit of anticoagulation is clearly positive at CHA2DS2-VASc ≥2 in men, ≥3 in women. HAS-BLED is used to identify MODIFIABLE bleeding risk factors to address (uncontrolled BP, alcohol excess, concurrent NSAID/antiplatelet), NOT to withhold anticoagulation — the bleeding risk from anticoagulation at HAS-BLED 2 is still exceeded by the stroke prevention benefit. Aspirin has no proven role in AF stroke prevention and causes equivalent GI bleeding to anticoagulants."
    },
    {
        "id": "t5-m376", "theme": 5, "topicTag": "atherosclerosis",
        "question": "Which ONE of the following correctly explains why the fibrous cap thickness of an atherosclerotic plaque determines the risk of acute MI rather than the degree of luminal stenosis?",
        "options": ["A. A thin fibrous cap plaque with a large necrotic lipid core is a 'vulnerable' plaque — thin cap ruptures under haemodynamic shear stress, exposing the pro-thrombotic lipid core to flowing blood, triggering platelet aggregation and thrombus formation — the culprit lesion in STEMI", "B. Thick fibrous cap plaques are unstable because they cannot accommodate the expansion of the necrotic core during exercise", "C. Luminal stenosis determines MI risk — plaques causing >90% stenosis always cause MI while plaques causing <70% stenosis are always stable", "D. Fibrous cap thickness is irrelevant — it is the calcium content of the plaque that determines rupture risk", "E. Plaque rupture can only occur at total occlusions — partial stenosis plaques are always stable"],
        "correctAnswer": "A",
        "explanation": "The 'vulnerable plaque' concept: most MIs (~70%) occur from rupture of plaques causing <70% stenosis — these plaques are often not haemodynamically significant on stress testing. Vulnerable plaque features (TCFA — thin-cap fibroatheroma): large lipid-rich necrotic core (>40% of plaque volume), thin fibrous cap (<65 µm — macrophage-mediated proteolysis dissolves collagen, destabilising the cap), high macrophage/inflammatory cell infiltration. Haemodynamic shear stress → cap rupture → subendothelial matrix and necrotic core exposed → tissue factor activates extrinsic clotting cascade → platelet aggregation + fibrin clot → occlusive thrombus → STEMI. Paradox: tight stenoses (>70%) develop abundant collaterals and cause stable angina rather than MI; mild-moderate stenoses rupture suddenly without warning. This explains why bypass surgery/PCI prevents angina but only partially prevents MI."
    },
    {
        "id": "t5-m377", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient is prescribed sacubitril/valsartan (Entresto) for HFrEF. Which ONE of the following represents the MOST important safety consideration when transitioning from an ACE inhibitor?",
        "options": ["A. Sacubitril/valsartan must be started the same day as stopping the ACE inhibitor to prevent haemodynamic deterioration", "B. A mandatory 36-hour washout period is required between stopping the ACE inhibitor and starting sacubitril/valsartan — combining them risks severe angioedema because both inhibit bradykinin breakdown (sacubitril inhibits neprilysin which also degrades bradykinin)", "C. Sacubitril/valsartan cannot be used in any patient previously on an ACE inhibitor due to receptor downregulation", "D. Sacubitril/valsartan must be combined with an ACE inhibitor — the combination is the mechanism of action", "E. The washout period between ACE inhibitor and sacubitril/valsartan is 7 days to prevent drug interactions"],
        "correctAnswer": "B",
        "explanation": "Sacubitril/valsartan (Entresto): sacubitril is a neprilysin inhibitor; neprilysin degrades natriuretic peptides (BNP, ANP — beneficial in HF) AND bradykinin. Sacubitril inhibits neprilysin → increased bradykinin. ACE inhibitors also increase bradykinin (block kinin degradation). Combining → extremely high bradykinin levels → severe potentially life-threatening angioedema (oropharyngeal swelling). Therefore: mandatory 36-hour washout after stopping ACE inhibitor BEFORE starting sacubitril/valsartan. Patients on ARBs (no bradykinin effect) can switch directly without washout. PARADIGM-HF trial: sacubitril/valsartan vs enalapril in HFrEF — 20% relative reduction in CV death + HF hospitalisation. Indicated in HFrEF (EF ≤35%) symptomatic on ACE inhibitor + beta-blocker, eGFR ≥30, SBP ≥100."
    },
    {
        "id": "t5-m378", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly describes the mechanism of 're-entry' as a cause of cardiac arrhythmia?",
        "options": ["A. Re-entry requires two pathways with different conduction velocities and refractory periods — a premature impulse blocks in the faster pathway (still refractory), conducts slowly down the other pathway, then re-enters the first pathway retrogradely when it has recovered, establishing a circular circuit", "B. Re-entry occurs when the SA node fires at an increased rate, causing rapid repetitive depolarisation of the entire heart simultaneously", "C. Re-entry is caused by focal automaticity — a single ectopic focus firing spontaneously and rapidly, overriding the SA node", "D. Re-entry requires a structural defect (hole in the septum) for electrical impulses to travel in the wrong direction", "E. Re-entry only occurs during myocardial ischaemia and resolves spontaneously when perfusion is restored"],
        "correctAnswer": "A",
        "explanation": "Re-entry is the most common mechanism for sustained arrhythmias (AF, AFL, SVT, VT). Requirements: (1) Two pathways with different properties; (2) Unidirectional block in one pathway (due to different refractory periods); (3) Slow conduction in the alternative pathway allowing time for the blocked pathway to recover. Circuit: premature impulse → blocked in fast pathway (still refractory) → conducts slowly down slow pathway → arrives at the junction retrogradely → fast pathway has recovered → conducts retrogradely up fast pathway → re-enters slow pathway → circuit established → tachycardia. Examples: AVNRT (fast and slow AV nodal pathways), AVRT (AV node + accessory pathway), AFL (macro-re-entry around the tricuspid annulus), VT (around scar). Treatment: AV nodal blockers terminate AV node-dependent re-entry; ablation eliminates anatomical circuits."
    },
    {
        "id": "t5-m379", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly identifies the Duke criteria major criterion relating to echocardiography in the diagnosis of infective endocarditis?",
        "options": ["A. Echocardiographic evidence of endocardial involvement — oscillating intracardiac mass (vegetation) on valve/supporting structures/implanted material, OR new partial dehiscence of prosthetic valve, OR new valvular regurgitation", "B. Two separate blood cultures positive for typical IE organisms at any titre", "C. Fever >38°C on echocardiography is a major criterion", "D. Echocardiographic evidence of dilation of the left ventricle", "E. New right bundle branch block on ECG alongside echocardiographic changes"],
        "correctAnswer": "A",
        "explanation": "Modified Duke Criteria for IE diagnosis: Major criteria: (1) Positive blood culture — typical microorganism in 2 separate cultures (viridans streptococci, S. bovis, HACEK group, S. aureus, enterococcus) OR persistently positive cultures OR single positive for Coxiella burnettii/phase I IgG titre >1:800; (2) Evidence of endocardial involvement (echocardiographic major criterion) — oscillating intracardiac mass (vegetation), abscess, pseudoaneurysm, intracardiac fistula, perforation/aneurysm of valvular leaflet, new partial dehiscence of prosthetic valve, OR new valvular regurgitation. Minor criteria: predisposing cardiac condition or IVDU; fever ≥38°C; vascular phenomena; immunological phenomena; positive blood culture (not meeting major criteria). Definite IE: 2 major, OR 1 major + 3 minor, OR 5 minor. TOE (transoesophageal echo) is more sensitive than TTE for vegetations and abscesses."
    },
    {
        "id": "t5-m380", "theme": 5, "topicTag": "hypertension",
        "question": "A 65-year-old man has BP 155/92 mmHg confirmed on ABPM despite taking amlodipine 10mg + ramipril 10mg + indapamide 2.5mg. His serum potassium is 3.9 mmol/L (eGFR 65 mL/min). This represents stage 4 (resistant) hypertension. Which ONE of the following is the MOST appropriate step 4 addition?",
        "options": ["A. Add furosemide — high-dose loop diuretic is the step 4 drug of choice for resistant hypertension", "B. Add spironolactone 25mg — the preferred step 4 addition when K+ ≤4.5 mmol/L in NICE guidelines", "C. Add bisoprolol as a step 4 drug regardless of potassium level", "D. Add doxazosin — preferred if K+ >4.5 as an alpha-blocker; equally preferred if K+ <4.5", "E. Refer immediately to endocrinology as resistant hypertension on 3 drugs always indicates phaeochromocytoma"],
        "correctAnswer": "B",
        "explanation": "NICE step 4 (resistant hypertension on triple therapy — CCB + ACE inhibitor/ARB + thiazide-like diuretic): (1) Check K+ level: if K+ ≤4.5 mmol/L → add low-dose spironolactone 25mg (mineralocorticoid receptor antagonist — significant evidence for BP reduction in resistant hypertension; PATHWAY-2 trial: most effective step 4 drug; acts on aldosterone-dependent sodium retention); (2) If K+ >4.5 mmol/L or significant CKD (GFR <45 and hyperkalaemia risk) → consider alpha-blocker (doxazosin) or beta-blocker. Spironolactone is effective in resistant hypertension even without primary hyperaldosteronism — likely because aldosterone plays a role in resistant hypertension beyond primary aldosteronism. Monitor renal function and potassium 4–8 weeks after adding spironolactone (hyperkalaemia risk with ACE inhibitor/ARB combination)."
    },
    {
        "id": "t5-m381", "theme": 5, "topicTag": "anticoagulants",
        "question": "A 45-year-old woman develops a provoked proximal DVT (deep vein thrombosis) after a 12-hour flight. She has no previous thromboembolism and no thrombophilia. Which ONE of the following is the MOST appropriate duration of anticoagulation?",
        "options": ["A. 6 weeks of anticoagulation — provoked DVT requires only short-term treatment", "B. 3 months of anticoagulation — then stop, as the risk factor (flight) is transient and the DVT is provoked; re-evaluate clinically", "C. Lifelong anticoagulation — all DVTs require permanent anticoagulation", "D. 6 months of anticoagulation — provoked DVT requires longer treatment than PE", "E. 2 weeks of anticoagulation — once the clot has stabilised, longer treatment is unnecessary"],
        "correctAnswer": "B",
        "explanation": "Duration of anticoagulation for DVT (NICE guideline): Provoked DVT/PE (reversible risk factor — surgery, trauma, immobilisation, long-haul flight, hospitalisation, pregnancy): 3 months anticoagulation then stop. The temporary risk factor has resolved; risk of recurrence is low (~5% at 5 years). Unprovoked DVT (no identifiable risk factor): 3–6 months minimum; then consider extended anticoagulation based on recurrence risk, bleeding risk, and patient preference (unprovoked = ~30% recurrence rate at 5 years without ongoing anticoagulation). Recurrent unprovoked VTE, cancer-associated thrombosis, or certain thrombophilias (antiphospholipid syndrome, homozygous Factor V Leiden): indefinite anticoagulation. First provoked DVT (as here — flight): 3 months then reassess — no indication for lifelong anticoagulation."
    },
    {
        "id": "t5-m382", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "Which ONE of the following correctly identifies the MOST common ECG location of ST elevation in an inferior STEMI and the coronary artery typically responsible?",
        "options": ["A. ST elevation in V1–V4 — left anterior descending (LAD) occlusion", "B. ST elevation in II, III, aVF (inferior leads) — right coronary artery (RCA) occlusion in 80% of cases", "C. ST elevation in I, aVL, V5–V6 (lateral leads) — left circumflex occlusion", "D. ST elevation in V1–V3 with posterior changes — obtuse marginal branch occlusion", "E. ST elevation in all leads simultaneously — left main coronary artery occlusion"],
        "correctAnswer": "B",
        "explanation": "Coronary anatomy and MI territories: Right coronary artery (RCA) → supplies the inferior wall of the LV (posterior descending artery — PDA, most commonly from RCA = right dominant circulation in 80%): ST elevation in II, III, aVF → inferior STEMI. Also assess V3R/V4R (right-sided leads) for RV infarction (ST elevation in RV leads — complicates inferior STEMI in 30–40% of RCA occlusions; causes profound hypotension with fluid-sensitive state — must NOT give nitrates or diuretics). Left anterior descending (LAD) → anterior wall: ST elevation V1–V4. Left circumflex (LCx) → lateral and posterior wall: ST elevation I, aVL, V5–V6 (or isolated posterior changes — tall R-waves + ST depression V1–V3 = posterior STEMI requiring posterior leads V7–V9)."
    },
    {
        "id": "t5-m383", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly describes the mechanism of action of PCSK9 inhibitors (e.g. evolocumab, alirocumab) in reducing cardiovascular risk?",
        "options": ["A. PCSK9 inhibitors block HMG-CoA reductase, the rate-limiting enzyme of cholesterol synthesis — the same mechanism as statins but more potent", "B. PCSK9 inhibitors are monoclonal antibodies that bind and inhibit PCSK9 — a protease that normally degrades LDL receptors; inhibiting PCSK9 → more LDL receptors recycled back to hepatocyte surface → increased LDL clearance from plasma → dramatic LDL reduction (50–65% additional reduction on top of statin)", "C. PCSK9 inhibitors reduce LDL by inhibiting intestinal cholesterol absorption, similar to ezetimibe", "D. PCSK9 inhibitors are antisense oligonucleotides that silence the ApoB gene, reducing LDL particle number", "E. PCSK9 inhibitors activate the LXR nuclear receptor, upregulating reverse cholesterol transport"],
        "correctAnswer": "B",
        "explanation": "PCSK9 (Proprotein Convertase Subtilisin/Kexin type 9): a protease secreted by hepatocytes that binds to LDL receptors on the hepatocyte surface after LDL uptake → directs LDLR to lysosomal degradation instead of recycling. High PCSK9 activity → fewer LDL receptors → less LDL clearance → elevated plasma LDL. PCSK9 inhibitors (evolocumab — Repatha; alirocumab — Praluent): humanised monoclonal antibodies that bind circulating PCSK9, preventing it from binding LDLR → LDLRs are recycled to the hepatocyte surface → increased LDL uptake → plasma LDL drops 50–65% (additional to statin). FOURIER (evolocumab) and ODYSSEY (alirocumab) trials: significant MACE reduction on top of maximally tolerated statin in high-risk patients. Indicated in: FH, statin intolerance (with maximum tolerated statin + ezetimibe), very high CVD risk with LDL above target."
    },
    {
        "id": "t5-m384", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient taking warfarin for a mechanical mitral valve (INR target 3–4) requires extraction of a carious lower molar. His INR today is 3.6. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Stop warfarin and reschedule for when the INR falls to 2.0 — all extractions require INR <2.0", "B. Postpone and refer to the anticoagulant clinic to reduce the INR to 2.5 before dental treatment", "C. Proceed with extraction: INR 3.6 is within the therapeutic range for this patient (target 3–4) and is below the dental threshold of 4.0; use local haemostasis; do not stop warfarin", "D. Stop warfarin 5 days before extraction and bridge with LMWH injections", "E. Refer to hospital oral surgery department immediately as mechanical valve patients can never have extractions in primary care"],
        "correctAnswer": "C",
        "explanation": "This is a nuanced question: the patient has a mechanical mitral valve with an INR target of 3–4 (higher than standard 2–3 due to prosthetic valve position). INR 3.6 is therapeutic for THIS patient. The dental threshold for proceeding with simple extraction is INR ≤4.0. INR 3.6 is below 4.0 → proceed with extraction with local haemostasis (sutures, tranexamic acid mouthwash). Stopping warfarin in a patient with a mechanical mitral valve is extremely dangerous — mechanical mitral valve carries the highest thromboembolism risk of any anticoagulation indication; even a brief sub-therapeutic period risks valve thrombosis causing acute haemodynamic collapse. LMWH bridging is expensive, inconvenient, and evidence suggests no outcome benefit over continuing warfarin in most situations."
    },
    {
        "id": "t5-m385", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes the 'Windkessel effect' of the aorta and its loss in ageing?",
        "options": ["A. The Windkessel effect refers to the ability of the aorta to autoregulate blood flow to the coronary arteries independently of cardiac output", "B. The Windkessel effect: the elastic aorta stores energy during systole (distends as blood is ejected) and releases it during diastole (recoils, pushing blood forward) — converting pulsatile LV output into smoother continuous peripheral flow; loss of aortic compliance in ageing → isolated systolic hypertension (high SBP from increased pulse wave velocity) and low diastolic BP", "C. The Windkessel effect describes the tidal flow pattern in the coronary arteries during the cardiac cycle", "D. The Windkessel effect is the mechanism by which the carotid baroreceptors buffer acute BP changes during exercise", "E. The Windkessel effect is a pathological process causing pseudoaneurysm formation in the ascending aorta"],
        "correctAnswer": "B",
        "explanation": "Windkessel effect (named after the German word for 'air chamber' — a device in old fire engines): the elastic aorta acts as a buffer. During systole: LV ejects blood at high pressure → elastic aortic wall distends (stores kinetic energy as potential energy). During diastole: aortic wall recoils → stored energy releases → drives blood forward continuously through the peripheral circulation despite the absence of ventricular ejection → maintains diastolic pressure. This dampens the pulse wave and ensures continuous forward flow. In ageing/atherosclerosis: aortic wall stiffens (collagen replaces elastin) → aorta cannot buffer effectively → (1) Higher systolic peak (all the ejected volume creates higher pressure); (2) Earlier return of reflected pulse wave adding to systole; (3) Lower diastolic pressure → isolated systolic hypertension of ageing (widened pulse pressure). This pattern increases LV workload and reduces coronary perfusion pressure."
    },
    {
        "id": "t5-m386", "theme": 5, "topicTag": "heart-failure",
        "question": "A 75-year-old man with HFrEF (EF 28%) has worsening oedema and dyspnoea despite furosemide 80mg twice daily. Which ONE of the following is the MOST appropriate management for his diuretic resistance?",
        "options": ["A. Increase furosemide to 160mg twice daily as the only option for diuretic resistance", "B. Add metolazone (a thiazide-like diuretic) — acts on the distal convoluted tubule where loop diuretics have no effect; the combination produces a 'sequential nephron blockade' and dramatically enhances diuresis; use cautiously (monitor electrolytes and renal function closely)", "C. Stop furosemide and switch to spironolactone as the sole diuretic agent", "D. Prescribe IV furosemide 40mg once — always effective as absorption is the cause of oral furosemide resistance", "E. Restrict fluid to 500mL daily — fluid restriction alone resolves diuretic resistance"],
        "correctAnswer": "B",
        "explanation": "Diuretic resistance in heart failure: reduced response to loop diuretics (furosemide, bumetanide) from: (1) Reduced GI absorption (gut oedema impairs oral bioavailability); (2) Increased sodium reabsorption at the distal tubule (hypertrophied DT compensates for blocked loop) — 'post-diuretic sodium retention'; (3) Neurohormonal activation (RAAS, SNS) promoting sodium retention; (4) Reduced renal perfusion. Strategies: IV diuretic (bypasses GI absorption problem); switch to bumetanide (better oral bioavailability); metolazone (thiazide-like diuretic acting on DCT — 'sequential nephron blockade') added to loop diuretic → synergistic diuresis. Warning: metolazone + furosemide combination can cause profound diuresis → hypovolaemia, hypokalaemia, and AKI — requires close monitoring of electrolytes, fluid status, and renal function."
    },
    {
        "id": "t5-m387", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly describes the ECG finding of 'Wellens' syndrome' and its clinical significance?",
        "options": ["A. Wellens' syndrome describes ST elevation in V1–V3 with right bundle branch block — indicating acute RV infarction", "B. Wellens' syndrome: deep symmetrical T-wave inversions (type A) or biphasic T-waves (type B) in V2–V3 during pain-free period in patients with recent chest pain — indicates critical proximal LAD stenosis causing imminent anterior STEMI if not revascularised urgently", "C. Wellens' syndrome is a hereditary long QT syndrome causing syncope and sudden cardiac death in young athletes", "D. Wellens' syndrome describes the pattern of diffuse ST elevation and PR depression seen in acute pericarditis", "E. Wellens' syndrome is a benign normal variant seen in fit young adults with no clinical significance"],
        "correctAnswer": "B",
        "explanation": "Wellens' syndrome (also called 'LAD coronary T-wave syndrome'): a critical ECG pattern in patients with recent chest pain who are currently pain-free. Two patterns: Type A (30%) — deeply symmetric T-wave inversions in V2–V3 (classic); Type B (70%) — biphasic T-waves in V2–V3 (positive then negative deflection). These patterns indicate critical stenosis of the proximal LAD (left anterior descending artery) with impending occlusion and anterior STEMI. The current pain-free period and near-normal ECG (no ST elevation, preserved R-waves — not infarcted yet) are deceptive. CRITICAL: DO NOT perform exercise stress testing (can provoke total occlusion); do NOT discharge as stable angina; arrange urgent coronary angiography for revascularisation. Recognition of Wellens' pattern prevents the imminent anterior STEMI that would occur without intervention."
    },
    {
        "id": "t5-m388", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "A 70-year-old man is admitted with sudden severe headache ('thunderclap headache') — worst headache of his life. CT head is performed within 6 hours and is reported as normal. Which ONE of the following is the MOST appropriate next investigation?",
        "options": ["A. Reassure the patient — a normal CT head rules out subarachnoid haemorrhage (SAH)", "B. MRI brain with FLAIR sequences — better than CT for detecting SAH", "C. Lumbar puncture (LP) at least 12 hours after headache onset — to detect xanthochromia (bilirubin from haemoglobin breakdown) even when CT is normal; CT sensitivity for SAH decreases rapidly over time", "D. Cerebral angiogram immediately — LP is not needed as a normal CT confirms no aneurysm", "E. Discharge with follow-up in outpatient neurology clinic in 6 weeks"],
        "correctAnswer": "C",
        "explanation": "Subarachnoid haemorrhage (SAH) investigation: CT head within 6 hours of headache onset has sensitivity ~98% for SAH. However, even within 6 hours, approximately 2% of SAHs are missed by CT. After 6 hours, CT sensitivity falls rapidly (haemoglobin is broken down — blood becomes less hyperdense). If CT is normal but SAH still suspected clinically (thunderclap headache = worst headache of life, explosive onset): perform lumbar puncture at minimum 12 hours after symptom onset (to allow time for haemoglobin breakdown to xanthochromia — yellow discolouration of CSF due to bilirubin). CSF spectrophotometry detects bilirubin (xanthochromia) — confirms SAH even with CT-negative result. A negative CT at 6 hours WITH negative CSF effectively excludes SAH. If SAH confirmed → urgent CT angiogram to locate the aneurysm."
    },
    {
        "id": "t5-m389", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient is initiated on hydralazine and isosorbide dinitrate for HFrEF because they are intolerant of ACE inhibitors and ARBs. Which ONE of the following correctly identifies the population in whom this combination has shown the greatest mortality benefit?",
        "options": ["A. All HFrEF patients — hydralazine/nitrate is equivalent to ACE inhibitor therapy regardless of ethnicity", "B. Self-identified Black patients with HFrEF — the A-HeFT trial demonstrated a 43% relative risk reduction in all-cause mortality in this population when added to standard background therapy", "C. Patients over 75 years with HFrEF — the elderly population benefits most from vasodilator therapy", "D. Patients with HFpEF — hydralazine/nitrate is the only proven therapy for preserved EF heart failure", "E. Patients with renal failure — hydralazine and nitrates are preferred when ACE inhibitors cannot be used due to AKI"],
        "correctAnswer": "B",
        "explanation": "Hydralazine + isosorbide dinitrate (H-ISDN): mechanism — hydralazine (arteriolar vasodilator — reduces afterload) + nitrate (venodilator — reduces preload + vasodilator). The African-American Heart Failure Trial (A-HeFT): demonstrated that adding H-ISDN to standard HF therapy (ACE inhibitor/ARB + beta-blocker + diuretic) in self-identified Black patients with NYHA III–IV HFrEF reduced all-cause mortality by 43% and hospitalisations by 39% — trial stopped early due to significant benefit. This led to the regulatory approval of a fixed-dose combination (BiDil) specifically in Black patients with HFrEF. The mechanism for greater benefit in this population may relate to differences in NO bioavailability and RAAS activity. H-ISDN is also used as ACE inhibitor/ARB substitute in intolerant patients (V-HeFT trials showed mortality benefit vs placebo)."
    },
    {
        "id": "t5-m390", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "A 60-year-old diabetic man has bilateral lower limb ischaemic rest pain and non-healing ulcers on both feet. His ABPI is 0.3 bilaterally. His arteries are heavily calcified on X-ray. Which ONE of the following is the MOST appropriate management pathway?",
        "options": ["A. Conservative management with dressings and antibiotics — revascularisation is not possible in diabetic patients", "B. Below-knee amputation immediately — calcified arteries cannot be revascularised", "C. Urgent vascular surgery review for revascularisation assessment (CTA or MR angiogram) — endovascular (angioplasty/stenting) or surgical bypass may be possible and limb salvage should be attempted before considering amputation", "D. Prescribe nifedipine for vasospasm — calcium channel blockers relax the calcified arteries", "E. Increase analgesia only — rest pain in diabetic PAD is non-surgical and managed medically"],
        "correctAnswer": "C",
        "explanation": "Critical Limb Ischaemia (CLI) / Chronic Limb-Threatening Ischaemia (CLTI): ABPI <0.5 with rest pain or tissue loss. Limb-threatening — requires urgent vascular assessment. Amputation is a last resort — limb salvage should ALWAYS be attempted first if anatomically feasible. Management: (1) Urgent vascular surgery review within 24–48 hours; (2) Imaging — CT angiogram or MR angiogram to map the arterial anatomy and identify revascularisation targets (inflow and outflow); (3) Revascularisation: endovascular (angioplasty, stenting — less invasive, suitable for shorter segment disease) or open bypass (femoropopliteal/tibial bypass using vein graft — preferred for long segment occlusions); (4) Wound care, infection control; (5) Risk factor management (glucose, BP, smoking, antiplatelet, statin). Even heavily calcified diabetic vessels can often be revascularised with modern techniques."
    }
]

data['mockBank'].extend(new_mock)

with open('data/theme-5.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"mockBank total: {len(data['mockBank'])}")
