import json

with open('data/theme-5.json', 'r') as f:
    data = json.load(f)

new_mock = [
    {
        "id": "t5-m221", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "Which ONE of the following correctly describes the coronary artery territory supplied by the left anterior descending (LAD) artery?",
        "options": ["A. Inferior wall of the LV, posterior septum, SA node, and AV node", "B. Anterior wall of LV, anterior interventricular septum, apex, and right bundle branch", "C. Lateral wall of LV, left atrium, and posterior descending artery in left-dominant systems", "D. Right ventricle, posterior wall of LV, and the crux of the heart", "E. Posterior descending artery territory exclusively — only the inferior septum"],
        "correctAnswer": "B",
        "explanation": "The LAD (left anterior descending) artery is the largest and most critical coronary artery. It supplies: the anterior wall of the LV, the anterior 2/3 of the interventricular septum (via septal perforators), the LV apex, the right bundle branch, and the left anterior fascicle. Occlusion of the proximal LAD ('widow maker') causes massive anterior STEMI with the worst prognosis among coronary occlusions — loss of >40% of LV mass, cardiogenic shock, and mortality if not rapidly reperfused. Left circumflex (LCx) supplies the lateral LV wall; RCA supplies the inferior wall, right ventricle, and nodal tissue."
    },
    {
        "id": "t5-m222", "theme": 5, "topicTag": "hypertension",
        "question": "A 72-year-old man on amlodipine, ramipril, and indapamide still has poorly controlled BP (average 155/98 mmHg on ABPM). Which ONE of the following is the MOST appropriate next step according to NICE step 4 hypertension management?",
        "options": ["A. Add a fourth antihypertensive: consider low-dose spironolactone (25mg) if K+ <4.5 mmol/L, or alpha-blocker (doxazosin) or beta-blocker", "B. Switch the entire regimen to a fixed-dose combination pill to improve adherence", "C. Add high-dose furosemide 80mg as the fourth drug in resistant hypertension", "D. Stop indapamide and replace with bendroflumethiazide for superior BP reduction", "E. Add verapamil — combining a rate-limiting CCB with amlodipine provides additional vasodilation"],
        "correctAnswer": "A",
        "explanation": "NICE step 4 resistant hypertension (inadequate control on three drugs — A+C+D regimen): first consider adherence review and cause of resistance. If confirmed resistant: add a fourth agent. If serum K+ <4.5 mmol/L, add low-dose spironolactone 25mg (has strong evidence for reducing resistant hypertension — often driven by undiagnosed hyperaldosteronism). If K+ ≥4.5 mmol/L or spironolactone is not tolerated: add alpha-blocker (doxazosin) or beta-blocker (bisoprolol). NEVER combine verapamil/diltiazem with amlodipine or with beta-blockers. Furosemide is not recommended as a routine antihypertensive step 4 agent."
    },
    {
        "id": "t5-m223", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly describes the Jones criteria used to diagnose acute rheumatic fever?",
        "options": ["A. Two minor OR one major criterion with evidence of preceding Group A streptococcal infection", "B. Two major OR one major and two minor criteria with evidence of preceding Group A streptococcal infection (elevated ASO titres or positive throat culture)", "C. Five minor criteria OR one major criterion; no evidence of streptococcal infection is needed", "D. Three major criteria required; minor criteria are only used to support a diagnosis made on clinical grounds", "E. Major and minor criteria must both be present simultaneously — isolated major criteria are insufficient"],
        "correctAnswer": "B",
        "explanation": "The Jones criteria (revised 2015) require: (A) evidence of recent Group A streptococcal infection (elevated/rising ASO titres, positive throat swab, or positive rapid strep test) PLUS (B) two major criteria OR one major + two minor criteria. Major criteria: carditis (clinical or subclinical on echo), polyarthritis, chorea (Sydenham's), erythema marginatum, subcutaneous nodules. Minor criteria: fever, elevated ESR/CRP, prolonged PR interval, arthralgia (if arthritis is not already a major criterion). The revised criteria allow echocardiographic carditis (subclinical carditis) as a major criterion, even without auscultatory findings."
    },
    {
        "id": "t5-m224", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 65-year-old man has a permanent pacemaker (VVI mode) for sick sinus syndrome. During a dental procedure under LA, the dentist uses an ultrasonic scaler. The patient's nurse reports the patient's pulse briefly slows. Which ONE of the following BEST explains this observation?",
        "options": ["A. The local anaesthetic has caused direct cardiac depression, reducing the intrinsic pacemaker rate", "B. Electromagnetic interference from the ultrasonic scaler has temporarily inhibited the pacemaker output", "C. The patient has temporarily converted to a normal sinus rhythm from the parasympathetic effects of the LA", "D. The scaler vibration caused vagal stimulation through the dental pulp nerve, slowing the heart rate", "E. This is normal cardiac variation during the VVI pacemaker's refractory period and requires no intervention"],
        "correctAnswer": "B",
        "explanation": "VVI pacemakers sense intrinsic ventricular activity and inhibit pacing when sensing is detected. They are also susceptible to electromagnetic interference (EMI) — EMI can be misinterpreted as intrinsic cardiac activity, causing the pacemaker to inappropriately inhibit pacing (rate drops to the underlying escape rhythm, which may be very slow in sick sinus syndrome). Ultrasonic scalers are the most common source of clinically relevant EMI in dentistry. Prevention: keep the scaler tip >15cm from the pacemaker generator; use manual scalers or sonic scalers (less EMI). In PM-dependent patients, briefer use and careful monitoring are essential."
    },
    {
        "id": "t5-m225", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly describes the difference in mechanism between ticagrelor and clopidogrel as P2Y12 antagonists?",
        "options": ["A. Both are direct-acting, reversible P2Y12 inhibitors; ticagrelor is simply a newer formulation of clopidogrel", "B. Clopidogrel is a prodrug requiring CYP2C19 activation to its active metabolite; irreversibly blocks P2Y12. Ticagrelor is a direct-acting, reversible P2Y12 blocker; does not require hepatic activation", "C. Ticagrelor blocks the thrombin receptor (PAR-1) rather than P2Y12; clopidogrel blocks P2Y12", "D. Clopidogrel is given IV only; ticagrelor is taken orally and has a longer duration of action", "E. Both are irreversible P2Y12 inhibitors; ticagrelor has a shorter half-life requiring twice-daily dosing compared to clopidogrel's once-daily dosing"],
        "correctAnswer": "B",
        "explanation": "Key mechanistic differences: Clopidogrel — thienopyridine prodrug; requires hepatic activation via CYP2C19 (variable — CYP2C19 poor metabolisers have reduced antiplatelet effect — 'clopidogrel resistance'); irreversibly binds P2Y12 → platelet inhibition lasts for platelet lifespan (7–10 days). Ticagrelor — cyclopentyltriazolopyrimidine; direct-acting (no prodrug activation); reversibly binds P2Y12; faster onset; more consistent antiplatelet effect regardless of CYP genotype; requires twice-daily dosing (shorter duration of action); side effect: dyspnoea (adenosine-mediated — ticagrelor inhibits adenosine reuptake). Ticagrelor is preferred post-ACS (PLATO trial superiority over clopidogrel for MI/death)."
    },
    {
        "id": "t5-m226", "theme": 5, "topicTag": "heart-failure",
        "question": "A 66-year-old woman with heart failure has progressive worsening despite ACE inhibitor, beta-blocker, and spironolactone at maximum doses. Her echocardiogram shows EF 25% with LBBB (QRS 160ms). Which ONE of the following device therapy is MOST appropriate?",
        "options": ["A. Percutaneous coronary intervention — coronary revascularisation will restore cardiac function in all HFrEF patients", "B. Cardiac resynchronisation therapy (CRT or CRT-D) — indicated in EF ≤35% with LBBB QRS ≥150ms on maximum medical therapy", "C. Intra-aortic balloon pump as long-term left ventricular support", "D. Implantable cardiac monitor only — no device therapy is indicated in medical-therapy-refractory HFrEF", "E. Atrial pacemaker — rate control in LBBB will restore normal ventricular synchrony"],
        "correctAnswer": "B",
        "explanation": "CRT (biventricular pacing) is strongly indicated here: EF ≤35% (HFrEF), LBBB morphology with QRS ≥150ms, NYHA class II–IV symptoms despite optimal medical therapy. CRT corrects electromechanical dyssynchrony caused by LBBB — restoring coordinated ventricular contraction, improving stroke volume, and reducing mitral regurgitation from annular distortion. Benefits: improved symptoms (NYHA class), 6-minute walk distance, quality of life, left ventricular reverse remodelling (EF improves), reduced hospitalisation, and reduced mortality (CARE-HF trial). A combined CRT-D device (adds ICD function) is used when sudden cardiac death risk is also high."
    },
    {
        "id": "t5-m227", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A dentist prescribes erythromycin for a patient on bisoprolol and atorvastatin for cardiovascular disease. Which ONE of the following drug interaction is MOST clinically significant?",
        "options": ["A. Erythromycin + bisoprolol: erythromycin induces CYP2D6, reducing bisoprolol plasma levels and heart rate control", "B. Erythromycin + atorvastatin: erythromycin inhibits CYP3A4, raising atorvastatin plasma levels and increasing the risk of myopathy/rhabdomyolysis", "C. Erythromycin + aspirin: erythromycin inhibits platelet COX-1, dangerously potentiating aspirin's antiplatelet effect", "D. Erythromycin + amlodipine: erythromycin competes with amlodipine for absorption in the gut, reducing antihypertensive efficacy", "E. Bisoprolol + atorvastatin: this combination is inherently dangerous and should not be prescribed together"],
        "correctAnswer": "B",
        "explanation": "Erythromycin (and clarithromycin) are potent CYP3A4 inhibitors. Atorvastatin is metabolised by CYP3A4. Inhibiting CYP3A4 → elevated atorvastatin plasma levels → increased risk of myopathy and rhabdomyolysis. The risk is greater for simvastatin (higher CYP3A4 dependence) but clinically significant for atorvastatin too. Clinical management: prefer azithromycin (less CYP3A4 inhibition), amoxicillin (no interaction), or metronidazole (no significant statin interaction) for dental infections in patients on statins. If erythromycin/clarithromycin is necessary, warn the patient to report muscle pain and weakness immediately."
    },
    {
        "id": "t5-m228", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly describes cardiac tamponade and its haemodynamic effect?",
        "options": ["A. Excess blood in the left ventricle impairs ejection, causing pulmonary oedema and reduced cardiac output", "B. Fluid accumulation in the pericardial space compresses the cardiac chambers (especially the right heart), prevents cardiac filling, and severely reduces cardiac output — a haemodynamic emergency", "C. Thrombus within the right atrium reduces tricuspid flow and causes progressive right-sided heart failure", "D. Excessive myocardial hypertrophy from hypertension reduces diastolic compliance, mimicking tamponade", "E. Air embolism in the coronary arteries prevents ventricular filling during diastole, causing tamponade-like physiology"],
        "correctAnswer": "B",
        "explanation": "Pericardial tamponade: fluid accumulates in the pericardial space (haemorrhage, malignant effusion, post-MI — Dressler's syndrome, uraemia) faster than the pericardium can stretch → intrapericardial pressure rises → external cardiac compression → impaired diastolic filling of ALL chambers (RV most vulnerable — thin wall) → reduced stroke volume and cardiac output. Classic 'Beck's triad': hypotension, raised JVP (impaired RV filling), muffled heart sounds. ECG: electrical alternans (alternating QRS amplitude). Pulsus paradoxus (>10mmHg fall in SBP on inspiration). Emergency treatment: pericardiocentesis."
    },
    {
        "id": "t5-m229", "theme": 5, "topicTag": "anticoagulants",
        "question": "A 70-year-old man develops heparin-induced thrombocytopenia (HIT) while on UFH for a DVT. His platelet count falls from 220 to 85 × 10⁹/L on day 8 of heparin. Which ONE of the following is the MOST appropriate immediate action?",
        "options": ["A. Stop heparin; administer a platelet transfusion to prevent bleeding complications; switch to warfarin", "B. Stop ALL heparin (including flushes and LMWH); start a non-heparin anticoagulant (argatroban, danaparoid, or fondaparinux); do NOT give platelets; do NOT start warfarin until platelets >150", "C. Reduce heparin dose by 50% and monitor platelet count daily until it recovers", "D. Switch from UFH to LMWH (enoxaparin) — LMWH does not cause HIT", "E. Stop heparin; give fresh frozen plasma and vitamin K to correct the coagulopathy"],
        "correctAnswer": "B",
        "explanation": "HIT type II management requires: (1) STOP all heparin immediately (including LMWH — cross-reacts with HIT antibodies in some cases, and flushes); (2) START a non-heparin anticoagulant (argatroban — direct thrombin inhibitor, preferred in renal failure is hepatic metabolised; danaparoid — anti-Xa; fondaparinux — anti-Xa; or a DOAC); (3) NO platelet transfusion — paradoxically fuels thrombosis; (4) Do NOT start warfarin until platelets recover to >150 × 10⁹/L — warfarin causes protein C depletion before anticoagulation is achieved, risking venous limb gangrene in HIT. The paradox of HIT: thrombocytopenia but prothrombotic state."
    },
    {
        "id": "t5-m230", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "Which ONE of the following correctly identifies the type of stroke MOST associated with hypertension as its primary risk factor?",
        "options": ["A. Large vessel atherosclerotic ischaemic stroke — hypertension accelerates carotid and intracranial atherosclerosis", "B. Cardioembolic ischaemic stroke from AF — hypertension causes AF which then causes cardioembolic stroke", "C. Haemorrhagic stroke (intracerebral haemorrhage) — hypertension-induced lipohyalinosis and microaneurysm rupture of deep perforating arteries", "D. Venous sinus thrombosis — hypertension increases venous pressure and thrombosis risk", "E. All stroke subtypes are equally associated with hypertension as a risk factor"],
        "correctAnswer": "C",
        "explanation": "While hypertension is a risk factor for ALL stroke types, it is most specifically and directly the primary pathological driver of haemorrhagic stroke (intracerebral haemorrhage — ICH). Chronic hypertension causes: hyaline degeneration of small perforating arteries (lipohyalinosis); Charcot-Bouchard microaneurysm formation on lenticulostriate arteries (basal ganglia, thalamus, pons, cerebellum); microaneurysm rupture causes hypertensive ICH. Controlling BP is the single most effective way to prevent hypertensive ICH. Hypertension is also a major risk factor for lacunar ischaemic strokes (small vessel disease from the same lipohyalinosis process without rupture)."
    },
    {
        "id": "t5-m231", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A patient presents with jaw pain, left arm numbness, and mild indigestion that started at rest 45 minutes ago. He describes no chest pain. Which ONE of the following should the dentist consider?",
        "options": ["A. Temporomandibular joint disorder and cervical radiculopathy — treat conservatively", "B. Orofacial pain of cardiac origin — jaw pain can be the sole presentation of myocardial ischaemia/MI; treat as suspected MI and call 999", "C. Trigeminal neuralgia causing jaw pain with atypical referred sensation to the arm", "D. Dental abscess with cellulitis causing referred pain to the arm and jaw due to inflammation", "E. Angioedema from ACE inhibitor causing jaw swelling that the patient misinterprets as pain"],
        "correctAnswer": "B",
        "explanation": "Orofacial pain of cardiac origin is a critical diagnosis for dental practitioners. Ischaemic cardiac pain can present as jaw pain, toothache, or facial pain without any chest pain — particularly in women, elderly patients, and diabetics. The associated arm numbness and rest onset are highly suggestive of an acute coronary syndrome. The dentist must recognise this as a potential cardiac emergency: call 999, administer aspirin 300mg chewed, give oxygen if SpO2 <94%, and prepare AED. Patients presenting to a dental surgery with atypical pain deserve a careful history including cardiac symptom screening, particularly if the pain is at rest or occurs on exertion."
    },
    {
        "id": "t5-m232", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly describes the mechanism of action of ranolazine in stable angina?",
        "options": ["A. Ranolazine is a beta-blocker that reduces heart rate and myocardial oxygen demand", "B. Ranolazine inhibits the late inward sodium current (INa) during myocardial ischaemia, preventing calcium overload and improving diastolic relaxation without significantly changing heart rate or blood pressure", "C. Ranolazine is a calcium channel blocker that causes coronary vasodilation", "D. Ranolazine activates KATP channels in vascular smooth muscle, causing coronary vasodilation similar to nicorandil", "E. Ranolazine inhibits HMG-CoA reductase in atherosclerotic plaques, reducing the lipid core and stabilising plaque"],
        "correctAnswer": "B",
        "explanation": "Ranolazine uniquely inhibits the late inward sodium current (late INa). During ischaemia, this current is abnormally amplified → excess intracellular Na+ → Na/Ca exchanger runs in reverse → intracellular Ca2+ overload → impaired diastolic relaxation (diastolic stiffness), increased wall tension and O2 demand. Ranolazine blocks late INa → reduces intracellular Ca2+ overload → improves diastolic relaxation → reduces O2 demand without significant HR or BP effects. This makes it useful as an add-on anti-anginal in patients where HR/BP-lowering agents are limited by side effects. It prolongs the QT interval slightly — use with caution if QTc prolonged."
    },
    {
        "id": "t5-m233", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following is MOST associated with the development of a femoral artery false aneurysm (pseudoaneurysm) post-PCI?",
        "options": ["A. Excessive warfarin anticoagulation causing spontaneous haemorrhage into the femoral sheath", "B. Inadequate post-procedural haemostasis at the femoral artery puncture site — blood tracks from the vessel lumen into a contained haematoma that communicates with the vessel", "C. Infection of the femoral artery catheter site causing mycotic aneurysm formation", "D. Atherosclerotic degeneration of the femoral artery weakening the vessel wall at the access site", "E. Post-procedure vasoconstriction at the access site causing arterial thrombosis and recanalization"],
        "correctAnswer": "B",
        "explanation": "Femoral artery pseudoaneurysm is a recognised complication of arterial catheterisation (coronary angiography, PCI). When the arterial puncture site fails to seal adequately (insufficient compression post-procedure, anticoagulation continuing), blood leaks from the arterial lumen into a perivascular space, contained by surrounding tissues → creates a pulsatile haematoma communicating with the arterial lumen via a 'neck.' Features: pulsatile groin mass with systolic bruit, local tenderness, may compress femoral nerve or vein. Treatment: ultrasound-guided thrombin injection (gold standard), compression, or surgical repair for large or infected pseudoaneurysms."
    },
    {
        "id": "t5-m234", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A 55-year-old man is prescribed clopidogrel after stroke. He attends for replacement of a loose denture. He reports that his gums bleed when he removes the denture. Which ONE of the following is the MOST appropriate advice and management?",
        "options": ["A. Advise him to stop clopidogrel for 2 weeks to resolve the gingival bleeding", "B. Reassure him that gingival bleeding is a normal side effect of clopidogrel that cannot be managed", "C. Improve the denture fit to reduce localised trauma; reinforce excellent oral hygiene; provide professional cleaning; do NOT stop clopidogrel", "D. Prescribe tranexamic acid mouthwash for daily use while he continues clopidogrel", "E. Refer to haematology for formal platelet function testing before managing his dental complaint"],
        "correctAnswer": "C",
        "explanation": "Clopidogrel impairs platelet aggregation and can worsen gingival bleeding, but the primary cause in this case is likely localised trauma from an ill-fitting denture compounded by pre-existing gingivitis/periodontitis. The correct approach: improve the denture fit (or take new impressions for a new denture) to eliminate mucosal trauma; optimise oral hygiene (remove plaque — the primary cause of gingival inflammation and bleeding); provide professional debridement. Clopidogrel must NOT be stopped — it is preventing stroke recurrence, and stopping it risks a devastating recurrent stroke. The gingival bleeding is manageable locally."
    },
    {
        "id": "t5-m235", "theme": 5, "topicTag": "anticoagulants",
        "question": "Alteplase is used in the treatment of acute ischaemic stroke. Which ONE of the following BEST describes its mechanism of action and the critical contraindication relevant to its use?",
        "options": ["A. Alteplase is a thrombin inhibitor that prevents new clot formation; contraindicated in renal failure", "B. Alteplase (recombinant tPA) converts plasminogen to plasmin, dissolving the thrombus; contraindicated in haemorrhagic stroke and recent major surgery or intracranial pathology", "C. Alteplase activates vitamin K-dependent factors to reverse the coagulation cascade; contraindicated in patients on warfarin", "D. Alteplase inhibits platelet GPIIb/IIIa receptors, dissolving platelet-rich thrombi; contraindicated in patients on aspirin", "E. Alteplase is a PCSK9 inhibitor that stabilises atherosclerotic plaques; contraindicated in hepatic failure"],
        "correctAnswer": "B",
        "explanation": "Alteplase (rt-PA — recombinant tissue plasminogen activator) is a serine protease that converts plasminogen (bound to fibrin within the thrombus) to plasmin, which then cleaves fibrin → thrombolysis. Used within 4.5 hours of ischaemic stroke onset (confirmed by CT to exclude haemorrhage). Key contraindications: haemorrhagic stroke (would worsen haemorrhage); recent major surgery or significant trauma (<14 days); active internal bleeding; prior intracranial haemorrhage; blood glucose <2.7 or >22.2 mmol/L; BP >185/110 mmHg despite treatment; INR >1.7 (if on warfarin). The decision requires CT to exclude haemorrhage BEFORE administering thrombolysis."
    },
    {
        "id": "t5-m236", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following CORRECTLY describes the difference between systolic and diastolic blood pressure and what physiological state each represents?",
        "options": ["A. Systolic BP is measured during ventricular relaxation; diastolic BP is measured during ventricular contraction", "B. Systolic BP represents the peak arterial pressure during ventricular contraction (systole); diastolic BP represents the minimum arterial pressure during ventricular relaxation (diastole)", "C. Systolic BP is measured at the brachial artery; diastolic BP must be measured at the central aorta", "D. Systolic BP is always lower than diastolic BP in healthy young adults", "E. The difference between systolic and diastolic BP (pulse pressure) has no clinical significance in cardiovascular assessment"],
        "correctAnswer": "B",
        "explanation": "Systolic blood pressure (SBP): the maximum pressure generated in the aorta during left ventricular systole (contraction and ejection). Diastolic blood pressure (DBP): the minimum pressure in the aorta during ventricular diastole (relaxation) — maintained by the elastic recoil of the aortic wall and closed aortic valve. Pulse pressure = SBP - DBP (normally 30–50 mmHg). Widened pulse pressure (>60 mmHg) occurs in aortic regurgitation (large SV) and atherosclerosis (stiff aorta). Narrow pulse pressure (<25 mmHg) occurs in cardiac tamponade, severe AS, cardiogenic shock (reduced SV). Pulse pressure is an important clinical marker of cardiovascular disease."
    },
    {
        "id": "t5-m237", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "A patient has been told she has 'mitral stenosis with an opening snap'. Which ONE of the following BEST describes the significance and mechanism of the opening snap?",
        "options": ["A. The opening snap replaces the second heart sound (S2) in severe mitral stenosis", "B. The opening snap is produced by the abrupt halting of the restricted mitral valve leaflets as they open maximally during diastole; a shorter A2-OS interval indicates more severe stenosis (higher LA pressure)", "C. The opening snap occurs during systole when the mitral valve closes against the high LV pressure", "D. The opening snap is heard at the left sternal edge in expiration and indicates aortic valve pathology", "E. An opening snap that is absent indicates mild mitral stenosis with minimal leaflet restriction"],
        "correctAnswer": "B",
        "explanation": "The opening snap (OS) in mitral stenosis is a high-pitched, early diastolic sound heard best at the apex and left sternal edge. It is produced when the fused mitral leaflets reach their maximum excursion during rapid early diastolic filling — the leaflets snap open abruptly, creating the sound. The A2-OS interval (time between aortic valve closure and the opening snap) is inversely proportional to the severity of MS: more severe stenosis → higher left atrial pressure → the mitral valve opens earlier → shorter A2-OS interval (<70ms = severe; >110ms = mild). The OS disappears when the valve is heavily calcified (reduced leaflet mobility)."
    },
    {
        "id": "t5-m238", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Long QT syndrome type 1 (LQT1) is characterised by which ONE of the following trigger for cardiac events?",
        "options": ["A. Events during sleep or rest — most events occur at night without provocation", "B. Events triggered by sudden auditory stimuli (loud noise, alarm clocks) — characteristic of LQT2", "C. Events triggered by exercise or emotional stress, particularly swimming — characteristic of LQT1 (KCNQ1 mutation — reduced IKs potassium current)", "D. Events triggered by fever and intercurrent illness — characteristic of Brugada syndrome", "E. Events triggered by eating — characteristic of Andersen-Tawil syndrome (LQT7)"],
        "correctAnswer": "C",
        "explanation": "Long QT syndrome subtypes have characteristic triggers: LQT1 (KCNQ1 mutation — loss of slow outward K+ current IKs): events during exercise or swimming — sympathetic activation during exertion increases QT dispersion in this subtype; swimming drowning is characteristic. LQT2 (HERG/KCNH2 — loss of rapid K+ current IKr): events from sudden auditory stimuli, emotional arousal, postpartum. LQT3 (SCN5A — gain of function late INa): events during rest/sleep (like Brugada). Management: all subtypes benefit from beta-blockers (LQT1 responds best); ICD for high-risk patients; avoid QT-prolonging drugs. Trigger avoidance: LQT1 — competitive swimming restricted."
    },
    {
        "id": "t5-m239", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following CORRECTLY states the maximum safe daily dose of paracetamol in a patient taking warfarin?",
        "options": ["A. Paracetamol should be avoided completely in patients on warfarin — use ibuprofen instead", "B. Maximum 1g (two 500mg tablets) per day — higher doses are contraindicated with warfarin", "C. Up to 4g (eight 500mg tablets) per day is safe with no interaction — paracetamol and warfarin have no interaction", "D. Up to 4g/day is acceptable for acute pain; prolonged use (>3 days) at doses ≥2g/day may modestly raise INR — monitor INR with regular paracetamol use", "E. The maximum dose is 2g/day (four 500mg tablets) as any higher dose causes warfarin to be displaced from albumin"],
        "correctAnswer": "D",
        "explanation": "Paracetamol is the analgesic of choice in warfarin patients. At standard single doses for acute pain, the interaction is clinically negligible. However, regular use of paracetamol at ≥2g/day for several consecutive days can modestly raise the INR (the interaction involves paracetamol metabolites inhibiting vitamin K-dependent carboxylase enzymes). The maximum dose of 4g/day is acceptable for acute pain, but if the patient requires regular paracetamol for more than a few days, the GP/anticoagulant clinic should be informed and the INR checked. The INR rise is usually modest and predictable. This contrasts sharply with NSAIDs (which should be avoided with warfarin)."
    },
    {
        "id": "t5-m240", "theme": 5, "topicTag": "heart-failure",
        "question": "A 71-year-old man with HFrEF is found to have a serum sodium of 128 mmol/L (hyponatraemia). His medications include furosemide and ramipril. Which ONE of the following BEST explains the mechanism of hyponatraemia in heart failure?",
        "options": ["A. Heart failure causes renal sodium loss through increased GFR from high cardiac output", "B. In heart failure, reduced cardiac output activates non-osmotic ADH (vasopressin) release → water retention diluting sodium; RAAS activation adds aldosterone-mediated sodium and water retention but relatively more water → dilutional hyponatraemia", "C. Diuretics directly cause urinary sodium loss faster than water loss — resulting in pure hyponatraemia", "D. ACE inhibitors block aldosterone and prevent all sodium reabsorption, causing primary sodium loss", "E. Hyponatraemia in heart failure is always due to excessive fluid intake from thirst — restricting fluids will correct it completely"],
        "correctAnswer": "B",
        "explanation": "Hyponatraemia in heart failure is primarily dilutional ('euvolaemic relative to the circulation but total body Na+ and water are increased'). Mechanisms: (1) Non-osmotic ADH (vasopressin) release — triggered by low cardiac output (baroreceptor activation) despite low serum osmolality — causes free water retention; (2) RAAS activation — angiotensin stimulates thirst and ADH → additional water intake and retention; (3) Furosemide causes selective sodium loss in some patients. Hyponatraemia in HF is a marker of severity and poor prognosis. Management: fluid restriction; vasopressin V2 receptor antagonists (tolvaptan) in severe resistant cases; optimise cardiac output."
    },
    {
        "id": "t5-m241", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "A patient with confirmed IE develops haematuria and severe flank pain 2 weeks into IV antibiotic therapy. Imaging shows a wedge-shaped infarct in the lower pole of the left kidney. Which ONE of the following BEST explains this complication?",
        "options": ["A. Antibiotic-induced interstitial nephritis from prolonged benzylpenicillin therapy", "B. Immune complex glomerulonephritis from IE depositing IgG-containing complexes in glomeruli", "C. Septic embolism from the mitral valve vegetation to the renal artery, causing renal infarction", "D. Aminoglycoside nephrotoxicity causing acute tubular necrosis presenting as haematuria", "E. Aortic dissection complicating IE, obstructing the left renal artery from the aortic lumen"],
        "correctAnswer": "C",
        "explanation": "Septic embolism is a major complication of IE — vegetations on left-sided valves (aortic, mitral) can fragment and embolise to systemic circulation: brain (stroke — most feared), kidneys (renal infarction), spleen (splenic infarction — left hypochondrial pain), extremities, and coronary arteries (MI). A wedge-shaped (i.e. vascular territory-shaped) renal infarct is the classic imaging finding of arterial embolism to the kidney. It presents with haematuria, flank pain, and raised LDH. Glomerulonephritis (option B) also occurs in IE (type III hypersensitivity) but causes proteinuria and red cell casts, not a wedge infarct on imaging."
    },
    {
        "id": "t5-m242", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly describes the primary dental concern when a patient is taking high-dose aspirin (not low-dose 75mg) for anti-inflammatory purposes?",
        "options": ["A. High-dose aspirin causes gingival overgrowth that needs to be distinguished from drug-induced gingival hyperplasia from other drugs", "B. High-dose aspirin should never be combined with paracetamol for post-operative analgesia", "C. High-dose aspirin irreversibly inhibits platelet COX-1, significantly impairing haemostasis for the platelet lifespan (7–10 days); increases post-operative bleeding risk; and causes gastric irritation", "D. High-dose aspirin inhibits CYP2C9, significantly raising the INR if the patient is also on warfarin", "E. High-dose aspirin causes xerostomia through anticholinergic mechanisms, increasing caries risk"],
        "correctAnswer": "C",
        "explanation": "High-dose aspirin (e.g. 600mg analgesic doses, or 1–4g/day for anti-inflammatory purposes like rheumatic disease) irreversibly acetylates platelet COX-1, completely blocking TXA2 synthesis for the entire platelet lifespan. This significantly impairs primary haemostasis — post-operative bleeding after dental extractions is increased. Unlike low-dose (75mg) cardioprotective aspirin (which should NEVER be stopped for dental procedures), high-dose aspirin could potentially be reviewed with the prescribing physician if major oral surgery is planned. The gastric irritation is an additional concern: aspirin damages the gastric mucosa (inhibits PGE2-mediated gastroprotection), particularly relevant if other NSAIDs are also prescribed."
    },
    {
        "id": "t5-m243", "theme": 5, "topicTag": "cvd-overview",
        "question": "A 68-year-old patient's chest radiograph shows cardiomegaly. Which ONE of the following criteria BEST defines cardiomegaly on a PA (posteroanterior) chest X-ray?",
        "options": ["A. Any visible bulge of the left heart border beyond the midclavicular line", "B. Cardiothoracic ratio (CTR) >0.5 on a PA CXR (cardiac diameter occupies more than half the thoracic diameter)", "C. CTR >0.6 on either a PA or AP chest X-ray — the threshold is the same regardless of projection", "D. Heart shadow extending to the right of the spine on the PA view", "E. LV apical displacement below the level of the 5th rib intercostal space"],
        "correctAnswer": "B",
        "explanation": "Cardiomegaly on a PA (not AP — cardiac silhouette is magnified on AP projection) chest X-ray: cardiothoracic ratio (CTR) >0.5. CTR = maximum cardiac diameter / maximum thoracic diameter (inner rib margins). A CTR >0.5 indicates cardiomegaly. Causes: left ventricular hypertrophy/dilation (hypertension, cardiomyopathy, valvular disease, MI), right ventricular dilation (cor pulmonale, pulmonary hypertension, left-to-right shunts), pericardial effusion (large 'water bottle' silhouette). AP (supine) films over-estimate the heart size due to magnification and increased venous return in supine position — CTR of 0.5 should not be used on AP films."
    },
    {
        "id": "t5-m244", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on warfarin (INR 2.2) requires a routine scale and polish. She asks if her warfarin needs to be adjusted for this procedure. Which ONE of the following is the MOST appropriate response?",
        "options": ["A. Yes — stop warfarin 2 days before to prevent excessive bleeding during scaling", "B. No adjustment needed — warfarin does not affect the bleeding during routine scaling; oral hygiene improvement is the best prevention strategy", "C. Yes — the INR should be reduced to below 1.5 before any periodontal procedure involving the gingival margin", "D. Yes — prescribe tranexamic acid mouthwash for 3 days before the scaling procedure", "E. No — but limit the scaling to one quadrant per visit to minimise bleeding risk"],
        "correctAnswer": "B",
        "explanation": "A routine scale and polish in a patient on warfarin with a therapeutic INR (2.2) requires NO modification of warfarin. Scaling is not listed among the procedures that carry significant haemorrhagic risk in anticoagulated patients — it is a non-invasive procedure that does not penetrate deeper than the gingival sulcus. The gingival bleeding that occurs during scaling in warfarin patients is typically minimal and easily controlled. Stopping warfarin risks thromboembolism. Improving oral hygiene (the root cause of gingival inflammation and increased bleeding) is the most effective strategy. Prophylactic tranexamic acid mouthwash is not indicated for routine scaling."
    },
    {
        "id": "t5-m245", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "A 65-year-old smoker with known PAD presents with rest pain in his right foot that is worse at night and relieved by hanging his leg out of the bed (dependency position). His ABPI is 0.35. Which ONE of the following BEST describes his condition?",
        "options": ["A. Intermittent claudication — treat with exercise and antiplatelet therapy", "B. Critical limb ischaemia — rest pain at ABPI <0.4 indicates limb-threatening ischaemia requiring urgent vascular assessment and revascularisation", "C. Diabetic peripheral neuropathy — rest pain and ABPI may be confounded by calcified vessels", "D. Chronic venous insufficiency causing nocturnal leg cramps — treat with compression and leg elevation", "E. Raynaud's phenomenon — rest pain at night suggests vasospastic disease requiring CCBs"],
        "correctAnswer": "B",
        "explanation": "Rest pain (especially nocturnal rest pain relieved by dependency — hanging the leg down to use gravity to increase blood flow to the ischaemic foot) with ABPI <0.4 defines critical limb ischaemia (CLI/CLTI — chronic limb-threatening ischaemia). The ABPI of 0.35 indicates severe PAD with insufficient blood flow to maintain tissue viability at rest. Without revascularisation, the natural history is tissue loss, gangrene, and amputation within 6 months. Urgent vascular surgical referral for revascularisation assessment (angioplasty, bypass surgery). Dependency position temporarily increases perfusion pressure — a classic sign of CLI."
    },
    {
        "id": "t5-m246", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 60-year-old woman on amiodarone for AF develops heat intolerance, weight loss, palpitations, and fine tremor. Her TSH is suppressed (<0.01 mU/L) with elevated free T4. Which ONE of the following is the MOST likely diagnosis?",
        "options": ["A. Amiodarone-induced hypothyroidism — amiodarone blocks T4 to T3 conversion", "B. Amiodarone-induced thyrotoxicosis (AIT) — amiodarone releases excess iodine or has direct toxic effects on thyroid, causing hyperthyroidism", "C. Primary Graves' disease — coincidental autoimmune thyroid disease unrelated to amiodarone", "D. Amiodarone-induced thyroid adenoma — amiodarone stimulates thyroid nodular growth", "E. This is normal for patients on amiodarone — TSH suppression is expected and does not indicate disease"],
        "correctAnswer": "B",
        "explanation": "Amiodarone contains 37% iodine by weight — approximately 75mg of iodine is released per 200mg amiodarone dose (daily requirement is 150-200 micrograms). Amiodarone-induced thyrotoxicosis (AIT): type 1 AIT — excess iodine drives thyroid hormone synthesis in autonomous nodules (in pre-existing thyroid disease); type 2 AIT — direct amiodarone/iodine-induced destructive thyroiditis releasing stored hormone (in normal thyroid gland). Features: suppressed TSH, elevated T4/T3, symptoms of hyperthyroidism. Management: thyroid function monitoring 6-monthly on amiodarone. AIT treatment: carbimazole (type 1); prednisolone (type 2); combined in type mix. Continue or stop amiodarone — decision weighs arrhythmia vs thyrotoxicosis risk."
    },
    {
        "id": "t5-m247", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A 78-year-old man with severe heart failure (EF 20%) and diabetes is on insulin, furosemide, bisoprolol, ramipril, and spironolactone. He has multiple decayed teeth requiring extensive restorative work. At what time of day should his dental appointments ideally be scheduled?",
        "options": ["A. Early morning (before 9am) — when catecholamine levels are at their daily peak, providing maximum cardiac stimulation", "B. Mid-morning appointments (10am–12pm) — catecholamine and cortisol levels are rising but stable; patients are alert and less fatigued; peak medication effects established; safer for cardiac patients", "C. Late afternoon (4–6pm) — lowest cardiac risk period as catecholamine levels are at their daily nadir", "D. Late evening (after 8pm) — cardiac patients perform best in the evening due to lower sympathetic tone", "E. First thing in the morning to catch the diuretic peak effect and minimise toilet trips during the appointment"],
        "correctAnswer": "B",
        "explanation": "Mid-morning appointments (10am–12pm) are generally recommended for medically compromised cardiac patients: (1) Peak catecholamine/cortisol surge has passed (highest MI risk is in the early morning hours — 6–10am); (2) Patients have taken their morning medications and these have reached therapeutic levels; (3) Patients have had breakfast (relevant for diabetic patients — avoid hypoglycaemia); (4) Patients are alert and less fatigued than afternoon. For insulin-dependent diabetics, ensure they have eaten breakfast before the appointment and blood glucose is checked if the procedure is lengthy. Schedule appointments when the patient's diuretic effect has waned to minimise urgency to urinate during treatment."
    },
    {
        "id": "t5-m248", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 59-year-old woman presents with typical chest pain on minimal exertion. Her exercise treadmill test is equivocal. Which ONE of the following investigations would be MOST appropriate to definitively assess coronary anatomy and severity of disease?",
        "options": ["A. Resting 12-lead ECG — will definitively identify ischaemic coronary artery disease", "B. CT coronary angiogram (CTCA) — provides non-invasive assessment of coronary artery anatomy and stenosis severity", "C. Echocardiography at rest — will demonstrate wall motion abnormalities caused by coronary stenosis", "D. Chest X-ray — will demonstrate coronary calcification indicating significant coronary disease", "E. 24-hour Holter monitor — will detect transient ischaemic ECG changes during daily activity"],
        "correctAnswer": "B",
        "explanation": "CT coronary angiography (CTCA) is now recommended by NICE (2016) as the first-line investigation for stable chest pain that is thought to be of cardiac origin (replacing exercise stress testing as initial investigation). CTCA provides non-invasive assessment of coronary anatomy, degree of stenosis, and plaque characteristics with high sensitivity and specificity. If significant stenosis (>70%) is identified, functional stress testing or invasive coronary angiography with FFR measurement confirms haemodynamic significance. CTCA avoids the risks of invasive angiography (arterial access, contrast, radiation) while providing equivalent anatomical information in most patients with stable symptoms."
    },
    {
        "id": "t5-m249", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "Which ONE of the following correctly describes the Vaughan Williams Class Ic antiarrhythmic mechanism and a key contraindication?",
        "options": ["A. Class Ic drugs (e.g. flecainide) block fast sodium channels with slow kinetics — significant conduction slowing; contraindicated in structural heart disease (post-MI, LV dysfunction) due to pro-arrhythmic effect", "B. Class Ic drugs (e.g. amiodarone) prolong the action potential by blocking potassium channels; safe in structural heart disease", "C. Class Ic drugs (e.g. verapamil) block L-type calcium channels; contraindicated in WPW syndrome", "D. Class Ic drugs (e.g. adenosine) are ultra-short-acting sodium channel blockers used for acute SVT termination", "E. Class Ic drugs (e.g. lidocaine) have use-dependent sodium channel blockade and are the only antiarrhythmics safe in structural heart disease"],
        "correctAnswer": "A",
        "explanation": "Class Ic antiarrhythmics (flecainide, propafenone) block fast inward Na+ channels with slow on/off kinetics — they significantly slow conduction velocity throughout the myocardium (slowing conduction more than Class Ib drugs). They are particularly effective for: AF rhythm control (especially in paroxysmal AF), AVRT, and ventricular arrhythmias. Critical contraindication: structural heart disease (post-MI, LV dysfunction, HF). The CAST trial showed flecainide and encainide INCREASED mortality in patients post-MI with ventricular ectopics — their pro-arrhythmic effect (converting PVCs to sustained VT/VF) is catastrophic in diseased myocardium. Safe only in structurally normal hearts."
    },
    {
        "id": "t5-m250", "theme": 5, "topicTag": "hypertension",
        "question": "A 62-year-old Afro-Caribbean man has hypertension and type 2 diabetes. Which ONE of the following is the MOST appropriate first-line antihypertensive choice?",
        "options": ["A. ACE inhibitor (ramipril) — best choice for diabetic patients due to renoprotective effects", "B. Calcium channel blocker (amlodipine) — first-line for Afro-Caribbean patients (lower renin hypertension); add ACE inhibitor or ARB as second agent, especially given diabetes", "C. Beta-blocker (bisoprolol) — preferred in Afro-Caribbean patients to control the high heart rate", "D. Thiazide diuretic (indapamide) — first-line for all patients regardless of ethnicity and comorbidities", "E. Alpha-blocker (doxazosin) — first-line for Afro-Caribbean patients with metabolic syndrome"],
        "correctAnswer": "B",
        "explanation": "NICE guidelines recommend different first-line antihypertensives based on patient characteristics. For patients of African or Caribbean family origin (any age), a calcium channel blocker (amlodipine) is preferred as first-line — this population has lower-renin hypertension and responds better to CCBs and diuretics than to ACE inhibitors/ARBs as monotherapy. However, given his diabetes (adding nephropathy risk), an ACE inhibitor or ARB should be added early (step 2) for renoprotection. The combination of CCB + ACE inhibitor/ARB is particularly effective in this patient. Beta-blockers are not preferred as they can mask hypoglycaemic symptoms in diabetes."
    },
    {
        "id": "t5-m251", "theme": 5, "topicTag": "heart-failure",
        "question": "A patient with newly diagnosed heart failure (EF 32%) is started on bisoprolol 1.25mg daily. Two weeks later, his breathlessness has worsened. Which ONE of the following BEST explains this clinical deterioration?",
        "options": ["A. Bisoprolol is contraindicated in heart failure and should never have been started", "B. Beta-blockers can initially worsen symptoms when started in HFrEF due to negative inotropy — they must be started at low dose in stable (not decompensated) patients and uptitrated slowly", "C. Bisoprolol 1.25mg is too low a dose — the dose should have been 10mg from the start to see benefit", "D. Bisoprolol has caused complete heart block, explaining the breathlessness from severe bradycardia", "E. Bisoprolol has raised blood pressure, increasing cardiac afterload and worsening heart failure"],
        "correctAnswer": "B",
        "explanation": "Beta-blockers in HFrEF: their long-term benefit (reduce mortality, improve EF) is mediated by blocking harmful chronic sympathetic activation. However, the acute negative inotropic effect of beta-blockade can initially worsen HF symptoms — particularly if started when the patient has some decompensation. Principles: (1) Start only when the patient is STABLE and euvolaemic (not acutely decompensated); (2) Start at very low doses (bisoprolol 1.25mg, carvedilol 3.125mg); (3) Uptitrate slowly every 2 weeks as tolerated; (4) Initial worsening is expected and managed by optimising diuresis — do NOT stop beta-blocker unless the patient decompensates severely. Long-term, bisoprolol significantly reduces mortality and may improve EF."
    },
    {
        "id": "t5-m252", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following statements correctly identifies a situation in which warfarin anticoagulation SHOULD be stopped before a dental procedure?",
        "options": ["A. Before any tooth extraction regardless of INR value", "B. Before a full-arch clearance (20+ extractions) under general anaesthetic in a hospital setting where the surgical and anaesthetic teams agree stopping is necessary and bridging is arranged", "C. Before a routine scale and polish to minimise gingival bleeding", "D. Before placement of a dental implant in a patient with INR 2.5", "E. Before endodontic treatment (root canal) as the file rotation can cause vascular injury"],
        "correctAnswer": "B",
        "explanation": "Warfarin is rarely stopped for dental procedures. For routine simple extractions (INR ≤4): continue warfarin, use local haemostasis. For major oral surgery under GA (full clearance, complex reconstructions), stopping warfarin may be agreed by the medical team — but ONLY with appropriate bridging therapy (LMWH in patients at high thromboembolism risk) and in a hospital environment. This decision requires coordination between the surgeon, anaesthetist, and anticoagulant physician. It would never be done unilaterally by the dentist. Stopping warfarin for routine dental procedures (options A, C, D, E) is never appropriate and carries serious risk of thromboembolism."
    },
    {
        "id": "t5-m253", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "Which ONE of the following correctly identifies the most common cause of aortic stenosis in patients over 70 years of age in developed countries?",
        "options": ["A. Rheumatic fever causing commissural fusion and valve calcification from childhood infection", "B. Calcific (degenerative) aortic stenosis — calcium deposition on normal tricuspid aortic valve leaflets from ageing, similar pathological process to atherosclerosis", "C. Congenital bicuspid aortic valve — most common cause in patients over 70", "D. Infective endocarditis destroying the valve leaflets and causing scarring and stenosis", "E. Marfan syndrome causing aortic root dilation that progressively restricts aortic valve opening"],
        "correctAnswer": "B",
        "explanation": "In patients >70 years, calcific/degenerative aortic stenosis is the most common cause of AS in developed countries. Pathogenesis: risk factors similar to atherosclerosis (age, male sex, hypertension, hyperlipidaemia, smoking) → endothelial injury on the aortic side of valve leaflets → LDL infiltration → oxidation → inflammation → calcium deposition → progressive restriction of leaflet motion → stenosis. This affects normal tricuspid valves and develops over decades. Bicuspid aortic valve (option C) is the most common cause of AS in patients <60–65 years (AS develops earlier due to turbulent flow across the bicuspid valve). Rheumatic AS is now rare in developed countries."
    },
    {
        "id": "t5-m254", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A patient taking metformin and a statin for cardiovascular risk reduction requires investigation for suspected coronary artery disease. Which ONE of the following drug needs to be temporarily stopped before and after CT coronary angiography with IV contrast?",
        "options": ["A. The statin — iodinated contrast inhibits statin metabolism, causing myopathy", "B. Metformin — iodinated contrast reduces renal clearance; if renal function deteriorates, metformin accumulates causing lactic acidosis", "C. Aspirin — contrast agents activate platelets, and aspirin potentiates this leading to systemic thrombosis", "D. ACE inhibitor — contrast agents interact with ACE inhibitors to cause acute anaphylaxis", "E. No drugs need to be stopped — modern low-osmolality contrast agents are safe with all medications"],
        "correctAnswer": "B",
        "explanation": "Metformin must be stopped before iodinated contrast administration (48 hours before, or on the day — check local protocol) and not restarted until 48 hours after, with confirmation that renal function has not deteriorated. The reason: iodinated contrast can cause contrast-induced nephropathy (CIN) — acute deterioration in renal function. If renal function deteriorates, metformin is not cleared renally → accumulates → inhibits mitochondrial complex I → lactic acidosis (potentially fatal). Metformin itself is safe with normal renal function but dangerous if renal clearance is suddenly compromised. This protocol applies to all procedures using IV iodinated contrast (CT scans, cardiac catheterisation, angiography)."
    },
    {
        "id": "t5-m255", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following correctly identifies the Korotkoff sounds used in sphygmomanometric blood pressure measurement?",
        "options": ["A. Phase I — disappearance of sounds = systolic; Phase V — first appearance of sounds = diastolic", "B. Phase I — first appearance of sounds = systolic; Phase V — disappearance of sounds = diastolic", "C. Phase I and V both correspond to systolic BP; diastolic BP is measured by oscillometry only", "D. Korotkoff sounds are heard only with digital blood pressure monitors", "E. Phase III — loudest sounds = systolic; Phase II — first sounds = diastolic"],
        "correctAnswer": "B",
        "explanation": "Korotkoff sounds are heard with a stethoscope over the brachial artery during cuff deflation. Phase I: the first appearance of tapping sounds as cuff pressure falls below systolic BP (blood begins to flow intermittently) = SYSTOLIC BP. Phase II: sounds become softer and swishing. Phase III: sounds become louder/crisper. Phase IV: sounds become muffled. Phase V: sounds disappear completely as cuff pressure falls below diastolic BP (continuous flow) = DIASTOLIC BP. In pregnant women, children, and patients with aortic regurgitation, sounds may never disappear (Phase V absent) — Phase IV (muffling) is used as the diastolic reading in these cases."
    },
    {
        "id": "t5-m256", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 70-year-old woman had a NSTEMI 5 years ago. She is on aspirin 75mg, atorvastatin 80mg, bisoprolol 5mg, and ramipril 10mg. She has had no further cardiac events. She attends for a lower molar extraction. Which ONE of the following BEST describes her dental management?",
        "options": ["A. Continue all medications; use effective LA with judicious adrenaline; local haemostasis for aspirin; morning appointment; short appointment", "B. Stop aspirin 10 days before to normalise platelet function before the extraction", "C. Use only adrenaline-free local anaesthetic as any adrenaline is contraindicated after MI", "D. Defer treatment for 2 further years — extractions should not be performed within 7 years of an MI", "E. Prescribe ibuprofen 400mg post-operatively to manage pain and reduce post-MI inflammation"],
        "correctAnswer": "A",
        "explanation": "5 years post-MI with no further events: this is stable, remote ischaemic heart disease. No restriction on dental treatment in primary care. Management: continue ALL medications including aspirin (never stop for extractions — risk of MI recurrence; also aspirin 75mg has minimal impact on dental surgical haemorrhage). Use adrenaline-containing LA (effective pain control is cardioprotective — pain causes sympathetic catecholamine surge). Aspirin 75mg has minimal effect on post-extraction haemostasis (much less than clopidogrel or warfarin) — local haemostatic measures suffice. Never use NSAIDs post-operatively — ramipril + ibuprofen = 'double whammy' reducing GFR; also ibuprofen can antagonise aspirin's antiplatelet effect."
    },
    {
        "id": "t5-m257", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following CORRECTLY describes the pharmacokinetics of warfarin that make its management complex?",
        "options": ["A. Warfarin has a short half-life of 2 hours, requiring three-times-daily dosing", "B. Warfarin is 98% protein-bound, extensively metabolised by CYP2C9 (S-enantiomer — more potent), has a half-life of 35–45 hours, and is highly sensitive to interactions with drugs, diet (vitamin K), and genetic polymorphisms", "C. Warfarin is renally cleared unchanged — renal function is the primary determinant of dose", "D. Warfarin does not undergo hepatic metabolism — it is cleared entirely by gut bacteria and is unaffected by CYP enzyme inhibitors", "E. Warfarin exists as a single active enantiomer — there is no difference in pharmacokinetics between the two warfarin enantiomers"],
        "correctAnswer": "B",
        "explanation": "Warfarin pharmacokinetic complexity: (1) 98% plasma protein-bound — highly susceptible to displacement interactions; (2) racemic mixture — S-enantiomer (more potent, ×5) metabolised mainly by CYP2C9; R-enantiomer metabolised by CYP1A2 and CYP3A4; (3) Long half-life (35–45h) — slow onset and offset of effect; (4) Narrow therapeutic index — small changes in dose or clearance cause large INR swings; (5) Extensive interactions — CYP2C9 inhibitors (miconazole, fluconazole, metronidazole, amiodarone) raise INR; inducers (rifampicin, carbamazepine) reduce INR; (6) Dietary vitamin K (leafy green vegetables) reduces anticoagulant effect; (7) Genetic polymorphisms in CYP2C9 and VKORC1 influence required dose significantly."
    },
    {
        "id": "t5-m258", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following BEST describes the clinical features and management of acute mesenteric ischaemia?",
        "options": ["A. Intermittent post-prandial abdominal pain ('intestinal angina') from atherosclerotic superior mesenteric artery stenosis; managed with stenting", "B. Sudden onset severe abdominal pain 'out of proportion to examination findings'; often from embolism (AF) or thrombosis of the superior mesenteric artery; surgical emergency — open embolectomy or thrombolysis", "C. Chronic weight loss and diarrhoea from SMA compression by the pancreas; managed conservatively", "D. Right iliac fossa pain from ischaemia of the appendix tip; treated by appendicectomy", "E. Left-sided abdominal pain from inferior mesenteric artery ischaemia presenting identically to diverticulitis"],
        "correctAnswer": "B",
        "explanation": "Acute mesenteric ischaemia (AMI) is a vascular emergency with >70% mortality if not treated rapidly. Mechanism: embolism (most common — from AF/cardiac thrombus to SMA), thrombosis (in-situ SMA atherothrombosis), or non-occlusive mesenteric ischaemia (low-flow state — cardiogenic shock, vasopressors). Classic presentation: severe periumbilical pain with minimal peritoneal signs early ('pain out of proportion to examination'). Progresses rapidly to bowel infarction, peritonitis, and septic shock. CT angiography confirms the diagnosis. Treatment: IV heparin, emergency surgery (embolectomy or bowel resection if infarcted), or thrombolysis/endovascular revascularisation in selected cases. Delay = bowel necrosis = death."
    },
    {
        "id": "t5-m259", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "A patient who had a TIA 3 days ago is now on aspirin 300mg and clopidogrel 75mg. He requires urgent extraction of a painful tooth. Which ONE of the following BEST describes the management of his antiplatelet therapy?",
        "options": ["A. Stop both antiplatelet agents for 7 days — a TIA is equivalent to an MI and both agents must be withheld temporarily", "B. Stop clopidogrel but continue aspirin — single antiplatelet is sufficient during the dental procedure", "C. Continue both antiplatelet agents — stopping either drug in the acute period post-TIA significantly increases risk of recurrent TIA or stroke; use local haemostasis", "D. Defer all dental treatment for 6 months following a TIA", "E. Switch to heparin infusion and stop both antiplatelet agents before the extraction"],
        "correctAnswer": "C",
        "explanation": "After a TIA, the immediate 90-day period carries the highest risk of stroke (up to 10% within 90 days, concentrated in the first few days). Dual antiplatelet therapy (DAPT — aspirin + clopidogrel) in the acute post-TIA period is prescribed specifically to reduce this very high early stroke risk. Stopping either antiplatelet drug for dental procedures would expose the patient to potentially devastating stroke. The dental extraction should proceed with both drugs continued, using local haemostatic measures. Urgent treatment of the dental cause of pain is also important — dental pain causes sympathetic stress that may contribute to cardiovascular risk."
    },
    {
        "id": "t5-m260", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly identifies the CYP enzyme primarily responsible for metabolising the active S-enantiomer of warfarin?",
        "options": ["A. CYP3A4 — the most abundant hepatic CYP enzyme responsible for most drug metabolism", "B. CYP1A2 — responsible for the R-enantiomer of warfarin and caffeine metabolism", "C. CYP2C9 — primarily responsible for the potent S-enantiomer of warfarin; the most important enzyme for warfarin drug interactions", "D. CYP2D6 — responsible for codeine activation and beta-blocker metabolism", "E. CYP2C19 — primarily responsible for clopidogrel activation and omeprazole metabolism"],
        "correctAnswer": "C",
        "explanation": "CYP2C9 is the primary enzyme metabolising the S-enantiomer of warfarin, which has approximately 5× greater anticoagulant potency than the R-enantiomer. This is why CYP2C9 inhibitors (miconazole, fluconazole, metronidazole, amiodarone, trimethoprim, sulphonamides, some SSRIs) cause the most clinically significant and potentially dangerous INR elevations. Genetic polymorphisms in CYP2C9 (poor metabolisers — *2 and *3 alleles) require lower warfarin doses. CYP2C19 metabolises clopidogrel's conversion to its active metabolite — poor metabolisers have 'clopidogrel resistance.' CYP1A2 metabolises the R-enantiomer of warfarin and has fewer interactions with common dental drugs."
    },
    {
        "id": "t5-m261", "theme": 5, "topicTag": "valvular-heart-disease",
        "question": "A 45-year-old woman with rheumatic mitral stenosis develops sudden-onset, very fast (160 bpm) atrial fibrillation. She is breathless and her BP is 85/50 mmHg. Which ONE of the following is the MOST appropriate immediate management?",
        "options": ["A. Start oral digoxin and review in 24 hours", "B. Give IV adenosine 6mg to terminate the arrhythmia", "C. Immediate synchronised DC cardioversion — haemodynamically compromised AF in mitral stenosis requires urgent cardioversion", "D. Start IV diltiazem to slow the ventricular rate", "E. Transfer to the ITU and commence dobutamine infusion to improve cardiac output"],
        "correctAnswer": "C",
        "explanation": "This patient has haemodynamically compromised (hypotensive — BP 85/50 mmHg) new-onset AF. In mitral stenosis, AF is particularly dangerous: loss of atrial kick reduces cardiac output by 20–30% (because MS requires atrial contraction to overcome the obstructed valve); rapid ventricular rate reduces diastolic filling time further → critical reduction in cardiac output → cardiogenic shock. Immediate synchronised DC cardioversion (100–200J biphasic) is life-saving. Synchronised cardioversion delivers the shock on the R-wave (not during the T-wave vulnerable period). Rate control drugs (digoxin, diltiazem) are inadequate in haemodynamic compromise. Adenosine treats SVT not AF."
    },
    {
        "id": "t5-m262", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A patient with hypertension and heart failure asks if she can use a decongestant nasal spray (xylometazoline) for a cold before her dental appointment. She is on amlodipine and furosemide. Which ONE of the following is the MOST appropriate advice?",
        "options": ["A. It is safe — topical decongestants have no cardiovascular effects as they are not absorbed systemically", "B. Avoid nasal decongestants — xylometazoline is an alpha-1 agonist that causes systemic vasoconstriction and increases BP, which is problematic in hypertension and heart failure; saline nasal rinses or steam inhalation are safer alternatives", "C. Short-term use of nasal decongestants is safe in all patients on antihypertensives", "D. Switch her to oral pseudoephedrine instead as it has less cardiovascular effect than topical xylometazoline", "E. She should use the decongestant only at night to minimise cardiovascular effects"],
        "correctAnswer": "B",
        "explanation": "Topical nasal decongestants (xylometazoline, oxymetazoline) are sympathomimetic alpha-1 agonists. Despite topical application, they are absorbed systemically in significant amounts — causing peripheral vasoconstriction and increased blood pressure. In patients with hypertension or heart failure, this vasoconstriction is undesirable — it raises afterload and BP, potentially worsening both conditions. Oral sympathomimetic decongestants (pseudoephedrine, phenylephrine) have even greater systemic effects and are explicitly contraindicated in hypertension and heart failure. Safer alternatives: saline nasal rinse, steam inhalation, intranasal corticosteroids (for allergic rhinitis), or simply waiting for the cold to resolve."
    },
    {
        "id": "t5-m263", "theme": 5, "topicTag": "cvd-overview",
        "question": "A dental student correctly identifies that a patient's irregularly irregular pulse represents atrial fibrillation. The student then measures the radial pulse as 72 bpm, but the ECG shows a ventricular rate of 90 bpm. Which ONE of the following BEST explains this discrepancy?",
        "options": ["A. The ECG is measuring a different parameter — ECG rate represents electrical events while pulse represents mechanical events, and these are always equal", "B. The pulse deficit: in AF, some ventricular contractions occur before adequate ventricular filling — stroke volume is too small to generate a palpable peripheral pulse wave; pulse rate < ECG heart rate", "C. The student counted the radial pulse incorrectly; pulse and ECG rate must always be identical", "D. The ECG heart rate is measured over 10 seconds while the pulse is measured over 60 seconds, causing arithmetic discrepancy", "E. The 18 bpm difference represents the patient's normal resting bradycardia separate from the AF"],
        "correctAnswer": "B",
        "explanation": "Pulse deficit: in AF, the irregularly irregular rhythm means some ventricular contractions occur very early after the previous beat — before the ventricle has filled adequately (insufficient diastolic filling time). These early beats generate insufficient stroke volume to propagate a palpable pulse wave to the radial artery. On the ECG, all ventricular depolarisations are counted (electrical events = 90). At the radial pulse, only those beats with sufficient stroke volume are felt (mechanical events = 72). The difference (90 - 72 = 18) is the pulse deficit. A large pulse deficit indicates poorly controlled AF with many haemodynamically ineffective beats."
    },
    {
        "id": "t5-m264", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on rivaroxaban 20mg once daily for AF presents for extraction of an upper molar. She took her last dose at 8pm last night. It is now 10am. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Postpone the extraction for 24 hours after her last dose to minimise anticoagulant effect during the procedure", "B. Proceed with the extraction; do not alter the rivaroxaban regimen; use local haemostatic measures", "C. Check her anti-Xa level to confirm residual anticoagulant activity before proceeding", "D. Give her andexanet alfa to reverse rivaroxaban before performing the extraction", "E. Ask her to skip her next dose of rivaroxaban and reschedule the appointment for the following morning"],
        "correctAnswer": "B",
        "explanation": "For simple dental extractions in patients on DOACs, current guidance (SDCEP, SDCEP-BCS) recommends proceeding without stopping the DOAC. Rivaroxaban 20mg once daily: half-life ~5–9 hours; 14 hours have passed since her last dose — anti-Xa activity is significantly reduced. For simple extractions (1–3 teeth), proceed with local haemostatic measures. Anti-Xa monitoring is not routinely used for dental decisions. Andexanet alfa reversal is reserved for life-threatening haemorrhage. Skipping doses or delaying until 24 hours (option A, E) increases stroke risk without meaningful benefit for simple extractions. If complex surgery were planned, timing 12–24 hours after the last DOAC dose is appropriate."
    },
    {
        "id": "t5-m265", "theme": 5, "topicTag": "heart-failure",
        "question": "Which ONE of the following correctly describes the key difference between heart failure with preserved ejection fraction (HFpEF) and heart failure with reduced ejection fraction (HFrEF) in terms of pathophysiology?",
        "options": ["A. HFpEF involves systolic dysfunction (reduced contractility); HFrEF involves diastolic dysfunction (impaired relaxation)", "B. HFrEF involves systolic dysfunction (reduced EF, reduced contractility); HFpEF involves diastolic dysfunction (impaired relaxation and increased stiffness of the LV) with preserved systolic function", "C. HFpEF and HFrEF have identical pathophysiology; they are distinguished only by the echocardiographic EF threshold", "D. HFpEF is exclusively caused by pericardial disease; HFrEF is exclusively caused by coronary artery disease", "E. HFpEF always has a better prognosis than HFrEF; survival rates are significantly higher in HFpEF patients"],
        "correctAnswer": "B",
        "explanation": "HFrEF (EF <40%): reduced systolic function — impaired cardiomyocyte contractility (loss of myocardium from MI, dilated cardiomyopathy, chronic ischaemia). EF is reduced. Responds to evidence-based pharmacotherapy (ACE inhibitors, beta-blockers, MRA, SGLT2 inhibitors). HFpEF (EF ≥50%): preserved systolic function — impaired diastolic relaxation and increased LV stiffness (from hypertension-induced LVH, ageing, restrictive cardiomyopathy, infiltrative disease). The LV cannot relax and fill properly → elevated filling pressures → pulmonary congestion with normal EF. Much fewer evidence-based treatments for HFpEF (SGLT2 inhibitors are one of the few showing benefit). Prognosis of HFpEF and HFrEF are similar overall."
    },
    {
        "id": "t5-m266", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 75-year-old man has a resting heart rate of 75 bpm on bisoprolol 10mg but continues to have significant angina symptoms. His BP is well controlled. Which ONE of the following is the MOST appropriate addition to his antianginal regimen?",
        "options": ["A. Add verapamil — combining a rate-limiting CCB with bisoprolol provides synergistic rate control", "B. Add ivabradine — further heart rate reduction in sinus rhythm patients who are already on maximum beta-blocker dose", "C. Add amlodipine (dihydropyridine CCB) — provides additional vasodilation and anti-anginal effect without affecting heart rate", "D. Switch bisoprolol to propranolol — non-selective beta-blockade is more effective for angina", "E. Add digoxin — reduces heart rate further, improving diastolic filling time and reducing angina"],
        "correctAnswer": "C",
        "explanation": "For persistent angina on a beta-blocker, adding a dihydropyridine calcium channel blocker (amlodipine) is the standard step 2 anti-anginal choice. Amlodipine: peripheral arterial vasodilation → reduces afterload → reduces myocardial O2 demand; coronary vasodilation → increases supply; does NOT significantly slow heart rate (safe to combine with beta-blocker). Verapamil/diltiazem (rate-limiting CCBs) are CONTRAINDICATED with beta-blockers — both drugs slow AV conduction → risk of complete heart block and cardiac arrest. Ivabradine (option B) can be used as an add-on but is only appropriate if HR remains >70 bpm (at 75 bpm it's borderline; maximum beta-blocker dose achieved); option C is more standard."
    },
    {
        "id": "t5-m267", "theme": 5, "topicTag": "infective-endocarditis",
        "question": "Splinter haemorrhages under the fingernails are noted in a patient with suspected infective endocarditis. Which ONE of the following BEST describes their clinical significance?",
        "options": ["A. Splinter haemorrhages are pathognomonic for infective endocarditis — the diagnosis can be made on this finding alone", "B. Splinter haemorrhages (>4, in multiple nails) are a minor Duke criterion for IE; however, isolated splinter haemorrhages are common in manual workers and athletes and are not specific", "C. Splinter haemorrhages exclusively indicate a major Duke criterion for IE regardless of their number", "D. Splinter haemorrhages are a sign of coagulation disorders rather than IE and require haematological investigation", "E. Only proximal (near the cuticle) splinter haemorrhages are significant for IE; distal ones are always due to trauma"],
        "correctAnswer": "B",
        "explanation": "Splinter haemorrhages are linear, dark red/brown haemorrhages running longitudinally in the nail bed. In the context of IE, they result from septic microemboli to nail bed capillaries or immune complex vasculitis. They are a minor Duke criterion (vascular phenomena). However, they are non-specific — isolated distal splinter haemorrhages are extremely common in manual labourers, athletes, and following trauma. For IE significance: multiple (typically ≥4), proximal, affecting multiple nails, in a patient with fever and a murmur. They are never pathognomonic alone. Diagnosis of IE requires the full Duke criteria assessment with blood cultures and echocardiography."
    },
    {
        "id": "t5-m268", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A patient describes episodes of regular rapid palpitations that start and stop abruptly. They are not related to exertion and sometimes resolve when she splashes cold water on her face. Her resting ECG shows no delta wave and a normal QTc. Which ONE of the following is the MOST likely diagnosis and mechanism?",
        "options": ["A. AF — typically irregular and does not respond to vagal manoeuvres", "B. Ventricular tachycardia — causes syncope rather than isolated palpitations in a young patient", "C. AVNRT (atrioventricular nodal re-entry tachycardia) — re-entry within the AV node; vagal manoeuvres (cold water face immersion) terminate it by slowing AV node conduction", "D. Sinus tachycardia from anxiety — gradual onset and offset; not terminated by vagal manoeuvres", "E. Wolff-Parkinson-White AVRT — typical presentation requires delta wave on resting ECG to diagnose"],
        "correctAnswer": "C",
        "explanation": "AVNRT is the most common paroxysmal SVT. It occurs due to a re-entry circuit within the AV node (fast and slow pathway dual AV nodal physiology). Features: sudden onset and offset (paroxysmal); regular rapid rate (150–250 bpm); palpitations ± mild dyspnoea ± neck pulsation (cannon A waves from simultaneous atrial and ventricular contraction); no delta wave on resting ECG. Vagal manoeuvres (Valsalva, face immersion in cold water — diving reflex, carotid sinus massage) terminate AVNRT by transiently blocking AV conduction. Adenosine IV is pharmacological treatment. Catheter ablation of the slow pathway is curative (>95% success rate)."
    },
    {
        "id": "t5-m269", "theme": 5, "topicTag": "anticoagulants",
        "question": "Which ONE of the following correctly explains why DOACs have fewer food interactions than warfarin?",
        "options": ["A. DOACs are not metabolised by the liver and therefore food cannot affect their activity", "B. DOACs do not depend on vitamin K-dependent pathways for their anticoagulant effect — dietary vitamin K does not affect their action; warfarin's effect is directly modulated by dietary vitamin K intake", "C. DOACs are synthetic compounds that are immune to dietary effects; warfarin is a naturally occurring compound from sweet clover", "D. DOACs have a wide therapeutic index; small fluctuations from diet are not clinically significant", "E. DOACs are given in such high doses that dietary effects cannot alter plasma levels meaningfully"],
        "correctAnswer": "B",
        "explanation": "Warfarin works by inhibiting vitamin K epoxide reductase (VKORC1) — preventing regeneration of active vitamin K. Dietary vitamin K (from leafy green vegetables — spinach, broccoli, kale) directly competes with warfarin's mechanism by providing substrate that bypasses the blocked enzyme. Changes in vitamin K intake (e.g. starting a green smoothie diet) significantly alter the INR. DOACs (direct thrombin/Xa inhibitors) do not interact with the vitamin K cycle — they directly block specific clotting factors regardless of vitamin K status. This eliminates the major dietary interaction. DOACs still have some food interactions (e.g. rivaroxaban must be taken with food for optimal absorption; some interactions with grapefruit juice), but these are less clinically impactful than warfarin-vitamin K interactions."
    },
    {
        "id": "t5-m270", "theme": 5, "topicTag": "peripheral-vascular-disease",
        "question": "Which ONE of the following correctly describes the pathophysiology of varicose veins?",
        "options": ["A. Primary failure of arterial valve leaflets in lower extremity arteries, causing reflux of blood into the deep venous system", "B. Failure of venous valves (particularly in the great saphenous vein) causing reflux of blood under high pressure into superficial veins → superficial vein dilation, tortuosity, and incompetence", "C. Arteriovenous fistula formation causing abnormally high blood flow through the superficial veins", "D. Deep vein thrombosis causing complete occlusion of the deep system, forcing all venous blood through superficial veins", "E. Lymphatic obstruction causing oedema that compresses superficial veins, causing secondary varicosities"],
        "correctAnswer": "B",
        "explanation": "Varicose veins: the primary abnormality is incompetence of venous valves (typically at the saphenofemoral junction and along the great saphenous vein — but can also involve the small saphenous). Valve failure causes retrograde blood flow (reflux) under gravitational pressure → increased hydrostatic pressure in superficial veins → progressive dilation and tortuosity → further valve incompetence (a vicious cycle). Risk factors: female sex, pregnancy, prolonged standing, obesity, family history. Complications: superficial thrombophlebitis, lipodermatosclerosis, venous eczema, venous ulceration (at the gaiter region). Treatment: compression stockings; saphenous vein ablation (laser, radiofrequency); foam sclerotherapy; surgery."
    },
    {
        "id": "t5-m271", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "A 65-year-old woman is started on chlorothiazide (a thiazide diuretic) for hypertension. Which ONE of the following metabolic side effects should be monitored?",
        "options": ["A. Hyperkalaemia — thiazides cause potassium retention similar to spironolactone", "B. Hypoglycaemia — thiazides directly stimulate pancreatic insulin secretion", "C. Hypokalaemia, hyponatraemia, hyperuricaemia, and worsening of blood glucose control (diabetogenic effect)", "D. Hypocalcaemia — thiazides increase renal calcium excretion", "E. Metabolic acidosis — thiazides inhibit bicarbonate reabsorption in the proximal tubule"],
        "correctAnswer": "C",
        "explanation": "Thiazide diuretic metabolic effects to monitor: (1) Hypokalaemia — increased K+ excretion in exchange for Na+ reabsorption in collecting duct; (2) Hyponatraemia — dilutional (especially in elderly — 'thiazide hyponatraemia' — can be severe and cause confusion/seizures); (3) Hyperuricaemia — reduced uric acid excretion → precipitates gout in susceptible patients; (4) Impaired glucose tolerance/new-onset T2DM — inhibit insulin secretion and increase insulin resistance (especially the beta-blocker + thiazide combination — significant T2DM risk); (5) Hypercalcaemia — thiazides increase renal calcium REABSORPTION (contrast to loop diuretics which cause hypocalcaemia); (6) Hypomagnesaemia — increased magnesium excretion."
    },
    {
        "id": "t5-m272", "theme": 5, "topicTag": "cvd-overview",
        "question": "Which ONE of the following structures forms the anatomical boundary between the right and left heart at the atrioventricular level?",
        "options": ["A. The interventricular septum — separates the two ventricles along the long axis of the heart", "B. The interatrial septum — contains the fossa ovalis (remnant of the foramen ovale)", "C. The tricuspid valve — separates the right atrium from the right ventricle", "D. The fibrous skeleton of the heart (atrioventricular rings) — separates atrial from ventricular myocardium and insulates electrical conduction", "E. The pericardium — the outer fibrous layer that physically separates the left and right heart"],
        "correctAnswer": "D",
        "explanation": "The cardiac fibrous skeleton (fibrous rings/annuli, central fibrous body) surrounds the four cardiac valves and forms the physical and electrical boundary between atrial and ventricular myocardium. It: (1) provides structural support for the valves; (2) electrically insulates the atria from the ventricles — the only normal conduction between them is through the AV node/bundle of His (which penetrates the skeleton). This explains why re-entrant tachycardias using accessory pathways (WPW) are possible — the accessory pathway bridges this insulating barrier. The interventricular septum separates the ventricles; the interatrial septum separates the atria."
    },
    {
        "id": "t5-m273", "theme": 5, "topicTag": "hypertension",
        "question": "Which ONE of the following antihypertensive drugs is specifically recommended for the management of hypertension in patients with concurrent benign prostatic hyperplasia (BPH)?",
        "options": ["A. Bisoprolol — beta-blockers reduce sympathetic outflow and improve urinary flow in BPH", "B. Doxazosin (alpha-1 blocker) — blocks alpha-1 receptors in both arterioles (reducing BP) and the prostate/bladder neck smooth muscle (improving urinary flow)", "C. Amlodipine — the calcium channel-blocking effect relaxes the detrusor muscle in BPH", "D. Indapamide — diuretics reduce the bladder filling rate, helping BPH symptoms", "E. Furosemide — reduces total body fluid, decreasing urine production and relieving BPH symptoms"],
        "correctAnswer": "B",
        "explanation": "Alpha-1 blockers (doxazosin, terazosin, prazosin) have a dual benefit in hypertension + BPH: (1) Antihypertensive: block alpha-1 receptors in vascular smooth muscle → vasodilation → reduced SVR and BP; (2) Urological: block alpha-1 receptors in prostate smooth muscle and bladder neck → reduced urethral resistance → improved urinary flow and reduced BPH symptoms. Doxazosin is the most commonly prescribed alpha-1 blocker for this dual indication in the UK. Side effect: first-dose hypotension (take at night). Note: alpha-blockers are NOT first-line antihypertensives in most patients but have specific advantages in BPH. Tamsulosin (more uroselective alpha-1A blocker) is used for BPH without significant antihypertensive effect."
    },
    {
        "id": "t5-m274", "theme": 5, "topicTag": "ischaemic-heart-disease",
        "question": "A 68-year-old man with a previous CABG (coronary artery bypass graft — saphenous vein graft to RCA and LAD) presents to his dentist with jaw pain that comes on when he walks upstairs. He has no chest pain. Which ONE of the following is the MOST appropriate course of action?",
        "options": ["A. Reassure the patient — jaw pain on exertion is a classic feature of temporomandibular joint dysfunction and unrelated to his cardiac history", "B. Diagnose dental/TMJ pathology clinically and treat with occlusal splint", "C. Recognise the jaw pain as a possible anginal equivalent (cardiac referred pain); refer urgently to his cardiologist before scheduling dental treatment", "D. Prescribe paracetamol and NSAIDs for the jaw pain and review in 4 weeks", "E. Perform a panoramic radiograph to identify any dental source of the jaw pain"],
        "correctAnswer": "C",
        "explanation": "Exertional jaw pain in a patient with known IHD (post-CABG) is a recognised presentation of angina (cardiac referred pain to the jaw via the same C-fibres as cardiac pain travelling via the same dermatomes). The pattern (exertional onset, not related to chewing/biting) in a patient with significant cardiac history requires immediate cardiac assessment to exclude new/progressive ischaemia — graft stenosis, native vessel disease progression. Dental treatment should not proceed until the cardiologist has assessed the patient and excluded active cardiac ischaemia. Diagnosing this as TMD or dental pain without cardiac exclusion could have fatal consequences."
    },
    {
        "id": "t5-m275", "theme": 5, "topicTag": "anticoagulants",
        "question": "A patient on warfarin for mechanical aortic valve (INR target 2.5–3.5) is found to have an INR of 7.8 at her routine check. She reports minor nosebleeds over the past 2 days but no major bleeding. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Admit to hospital immediately for IV fresh frozen plasma transfusion", "B. Stop warfarin; give oral vitamin K 1–5mg; repeat INR in 24 hours; investigate the cause of over-anticoagulation; restart warfarin at a lower dose when INR is back in range", "C. Continue warfarin at the same dose — the INR will self-correct within 48 hours", "D. Give IV protamine sulphate 50mg to immediately reverse warfarin to INR 1.0", "E. Stop warfarin permanently and switch to aspirin to prevent valve thrombosis"],
        "correctAnswer": "B",
        "explanation": "INR 7.8 with minor bleeding (nosebleeds — not haemorrhage): stop 1–2 doses of warfarin; give oral vitamin K 1–5mg (balances partial correction without complete reversal — avoids INR swinging to sub-therapeutic range which would risk valve thrombosis). Repeat INR in 24 hours and adjust warfarin dose accordingly. Investigate the reason for elevated INR (new drug interaction, dietary change, illness). IV FFP or vitamin K 10mg IV are reserved for major haemorrhage (intracranial, GI, haemodynamic compromise). Restarting warfarin at a slightly lower dose once INR returns to range. Protamine reverses heparin — not warfarin. Never switch mechanical valve patients to aspirin alone."
    },
    {
        "id": "t5-m276", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "Which ONE of the following correctly describes the SDCEP (Scottish Dental Clinical Effectiveness Programme) recommendation for the maximum number of extractions that can be performed in one visit in a patient with a therapeutic INR?",
        "options": ["A. Only a single tooth can be extracted per visit to minimise bleeding risk in anticoagulated patients", "B. Up to 3 simple extractions per visit is reasonable in patients with INR ≤4 with appropriate haemostatic measures", "C. There is no limit — up to a full clearance can be performed in one visit if local haemostasis is adequate", "D. The number is determined solely by the INR value — 1 tooth per INR unit above 1.0", "E. All extractions in warfarin patients must be performed in a hospital setting regardless of how many teeth are involved"],
        "correctAnswer": "B",
        "explanation": "SDCEP guidance on dental extractions in patients on warfarin: for patients with INR ≤4.0, simple dental extractions can be performed in primary care with local haemostatic measures. The guidance suggests that up to 3 simple extractions per visit is generally acceptable — more extensive extraction requires more extensive local haemostasis and monitoring. More complex cases (multiple extractions per visit, surgical extractions, patients with very labile INR, or those on additional antiplatelet drugs) may be more appropriately managed in a specialist/hospital setting. The decision is also influenced by the patient's overall medical complexity, not just the INR value alone."
    },
    {
        "id": "t5-m277", "theme": 5, "topicTag": "cardiac-arrhythmias",
        "question": "A 72-year-old man develops complete (third degree) heart block after inferior myocardial infarction. His ventricular escape rate is 35 bpm. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Give IV atropine 0.5mg — this will increase the ventricular escape rate in complete heart block", "B. Start oral bisoprolol to slow the ventricular rate and reduce myocardial oxygen demand", "C. Insert a temporary transvenous pacing wire; assess for recovery; if persistent, insert a permanent pacemaker", "D. Perform immediate cardioversion to restore sinus rhythm from the complete heart block", "E. Give IV adrenaline 1mg to increase the escape rate — the same protocol as cardiac arrest"],
        "correctAnswer": "C",
        "explanation": "Complete (third degree) heart block after inferior MI: the AV node is most commonly damaged (supplied by RCA). The escape rhythm in complete AV block originates below the block (junctional or ventricular) — typically 25–45 bpm. Management: (1) IV atropine may help if the block is at the AV node level (junctional escape — narrow QRS); however, atropine is often ineffective in complete block (the vagus doesn't innervate ventricular escape pacemakers); (2) Temporary transvenous pacing wire is the definitive acute management — paces the ventricles at a safe rate (typically 70 bpm); (3) Monitor — complete heart block after inferior MI often recovers spontaneously within 1–2 weeks; persistent block requires permanent pacemaker. Beta-blockers (option B) would worsen the heart block."
    },
    {
        "id": "t5-m278", "theme": 5, "topicTag": "drugs-for-cvd",
        "question": "Which ONE of the following correctly describes the mechanism by which felypressin (octapressin) — an alternative vasoconstrictor to adrenaline in some LA formulations — works?",
        "options": ["A. Felypressin is a synthetic catecholamine that stimulates both alpha and beta adrenoceptors", "B. Felypressin is a synthetic vasopressin (ADH) analogue that acts on V1 receptors in vascular smooth muscle, causing vasoconstriction without beta-adrenoceptor effects — no direct cardiac effects", "C. Felypressin inhibits nitric oxide synthesis in blood vessels, preventing vasodilation at the injection site", "D. Felypressin activates alpha-1 receptors exclusively in gingival vessels but has no effect on coronary or peripheral arteries", "E. Felypressin blocks adenosine receptors to prevent vasodilation at the injection site"],
        "correctAnswer": "B",
        "explanation": "Felypressin (also known as octapressin) is a synthetic analogue of vasopressin (antidiuretic hormone/ADH). It acts on V1 receptors on vascular smooth muscle cells → phospholipase C activation → IP3/DAG pathway → intracellular Ca2+ release → smooth muscle contraction → vasoconstriction. Unlike adrenaline, felypressin has NO beta-adrenoceptor activity — no direct cardiac stimulation (no increase in HR, contractility, or arrhythmic risk). Available in Citanest with Octapressin (prilocaine 3% + felypressin 0.03 IU/mL). Used as an alternative in patients where adrenaline is relatively contraindicated (e.g. thyrotoxicosis, severe uncontrolled hypertension). Note: felypressin can cause uterine contractions — relatively contraindicated in pregnancy."
    },
    {
        "id": "t5-m279", "theme": 5, "topicTag": "hypertension-stroke",
        "question": "A 58-year-old man has known peripheral arterial disease and hypertension. He is started on an ACE inhibitor (ramipril). Two weeks later, his creatinine has risen by 45% (from 88 to 128 µmol/L). Which ONE of the following BEST explains this rise?",
        "options": ["A. Ramipril is directly nephrotoxic and should always be stopped if creatinine rises by any amount", "B. A rise in creatinine ≤30% is expected and acceptable when starting ACE inhibitors in most patients — it reflects haemodynamic changes; a rise >30–50% should prompt investigation for bilateral renal artery stenosis", "C. The creatinine rise indicates ramipril is successfully improving glomerular filtration and is a positive response to treatment", "D. Ramipril should be continued regardless of creatinine rise — ACE inhibitors are renoprotective in all clinical scenarios", "E. This creatinine rise is caused by muscle wasting from ACE inhibitor-induced myopathy"],
        "correctAnswer": "B",
        "explanation": "ACE inhibitors cause a predictable and acceptable rise in creatinine of up to 20–30% when started — this reflects a reduction in GFR from reduced efferent arteriolar tone (Ang II normally constricts the efferent arteriole; blocking this reduces glomerular filtration pressure). This is haemodynamic, not structural, and is acceptable. A rise >30–50%, or in the context of PAD (which raises suspicion of concurrent renal artery stenosis — renovascular hypertension), requires investigation. Bilateral renal artery stenosis (or stenosis of a solitary kidney) is a contraindication to ACE inhibitors — efferent constriction is critical to maintaining GFR in these patients; removing it causes acute kidney injury (significant creatinine rise)."
    },
    {
        "id": "t5-m280", "theme": 5, "topicTag": "dental-implications-cvd",
        "question": "A 67-year-old man with controlled hypertension on atenolol attends for a routine check-up. The dentist notices a white reticulate pattern on both buccal mucosae bilaterally, with occasional erosions. The patient is unaware of the lesions. Which ONE of the following is the MOST appropriate management?",
        "options": ["A. Perform incisional biopsy immediately as this is suspicious for oral squamous cell carcinoma", "B. Diagnose as oral lichen planus; prescribe chlorhexidine mouthwash; discharge", "C. Recognise this as a likely drug-induced lichenoid reaction to atenolol; photograph; consider biopsy to confirm; liaise with GP about possible drug substitution; referral to oral medicine if symptomatic", "D. Reassure the patient that this is normal variation in the oral mucosa and requires no follow-up", "E. Prescribe a course of oral antifungals as this is likely oral candidosis masquerading as lichen planus"],
        "correctAnswer": "C",
        "explanation": "A bilateral white reticulate pattern on the buccal mucosae is consistent with oral lichen planus or a drug-induced lichenoid reaction. Beta-blockers (atenolol, propranolol) are among the most common drugs causing oral lichenoid reactions, which are clinically and histologically indistinguishable from idiopathic OLP. Management: document and photograph the lesion; biopsy to confirm the diagnosis histologically (dense sub-epithelial lymphocytic infiltrate at the basement membrane zone); liaise with the GP to discuss substituting atenolol with a non-beta-blocker antihypertensive. If the lesion resolves after drug withdrawal, the diagnosis of lichenoid drug reaction is confirmed. Refer to oral medicine for erosive/symptomatic lesions requiring topical corticosteroid therapy."
    }
]

data['mockBank'].extend(new_mock)

with open('data/theme-5.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"mockBank total: {len(data['mockBank'])}")
